# -*- coding: utf-8 -*-
"""Le nouvel écran d'ouverture : mur de couvertures, deux chemins d'entrée.

Trois de ces textes existaient en dur dans le code sans être traduisibles
(les invites de mot de passe, deux messages d'erreur) : ils le sont
maintenant, et ils passent donc ici.

Aucun mot latin dans les langues non latines : « min. » est écrit en toutes
lettres en russe, japonais, coréen et chinois.
"""
from catalogue import ecrire

T = {
    "Rangez vos livres, suivez vos lectures.": {
        "en": "Shelve your books, track your reading.",
        "es": "Ordena tus libros, sigue tus lecturas.",
        "es-419": "Ordena tus libros, sigue tus lecturas.",
        "pt-BR": "Organize seus livros, acompanhe suas leituras.",
        "de": "Ordne deine Bücher, verfolge deine Lektüre.",
        "it": "Ordina i tuoi libri, segui le tue letture.",
        "nl": "Orden je boeken, volg wat je leest.",
        "pl": "Uporządkuj książki, śledź swoje lektury.",
        "sv": "Ordna dina böcker, följ din läsning.",
        "tr": "Kitaplarını düzenle, okumalarını takip et.",
        "ru": "Расставьте книги, следите за чтением.",
        "ja": "本を並べて、読書を記録。",
        "ko": "책을 정리하고, 독서를 기록하세요.",
        "zh-Hans": "整理藏书，记录阅读。",
    },
    "Continuer avec un e-mail": {
        "en": "Continue with email",
        "es": "Continuar con un correo",
        "es-419": "Continuar con un correo",
        "pt-BR": "Continuar com e-mail",
        "de": "Mit E-Mail fortfahren",
        "it": "Continua con un'e-mail",
        "nl": "Doorgaan met e-mail",
        "pl": "Kontynuuj z adresem e-mail",
        "sv": "Fortsätt med e-post",
        "tr": "E-posta ile devam et",
        "ru": "Продолжить по эл. почте",
        "ja": "メールで続ける",
        "ko": "이메일로 계속하기",
        "zh-Hans": "使用邮箱继续",
    },
    "La connexion n'a pas abouti. Réessayez dans un instant.": {
        "en": "Sign-in didn't go through. Try again in a moment.",
        "es": "El inicio de sesión no se completó. Inténtalo de nuevo en un momento.",
        "es-419": "El inicio de sesión no se completó. Vuelve a intentarlo en un momento.",
        "pt-BR": "O login não foi concluído. Tente novamente em instantes.",
        "de": "Die Anmeldung hat nicht geklappt. Versuche es gleich noch einmal.",
        "it": "L'accesso non è andato a buon fine. Riprova tra un istante.",
        "nl": "Het inloggen is niet gelukt. Probeer het zo nog eens.",
        "pl": "Logowanie się nie powiodło. Spróbuj za chwilę.",
        "sv": "Inloggningen gick inte igenom. Försök igen om en stund.",
        "tr": "Giriş tamamlanamadı. Birazdan tekrar dene.",
        "ru": "Не удалось войти. Попробуйте через минуту.",
        "ja": "サインインできませんでした。少ししてからもう一度お試しください。",
        "ko": "로그인하지 못했어요. 잠시 후 다시 시도해 주세요.",
        "zh-Hans": "登录未成功，请稍后再试。",
    },
    "Saisissez d'abord votre adresse e-mail.": {
        "en": "Enter your email address first.",
        "es": "Escribe primero tu correo electrónico.",
        "es-419": "Escribe primero tu correo electrónico.",
        "pt-BR": "Digite primeiro seu e-mail.",
        "de": "Gib zuerst deine E-Mail-Adresse ein.",
        "it": "Inserisci prima il tuo indirizzo e-mail.",
        "nl": "Vul eerst je e-mailadres in.",
        "pl": "Najpierw podaj swój adres e-mail.",
        "sv": "Ange först din e-postadress.",
        "tr": "Önce e-posta adresini gir.",
        "ru": "Сначала введите адрес электронной почты.",
        "ja": "先にメールアドレスを入力してください。",
        "ko": "먼저 이메일 주소를 입력해 주세요.",
        "zh-Hans": "请先输入邮箱地址。",
    },
    "Mot de passe": {
        "en": "Password",
        "es": "Contraseña",
        "es-419": "Contraseña",
        "pt-BR": "Senha",
        "de": "Passwort",
        "it": "Password",
        "nl": "Wachtwoord",
        "pl": "Hasło",
        "sv": "Lösenord",
        "tr": "Şifre",
        "ru": "Пароль",
        "ja": "パスワード",
        "ko": "비밀번호",
        "zh-Hans": "密码",
    },
    "Mot de passe (6 caractères min.)": {
        "en": "Password (6 characters min.)",
        "es": "Contraseña (mín. 6 caracteres)",
        "es-419": "Contraseña (mín. 6 caracteres)",
        "pt-BR": "Senha (mín. 6 caracteres)",
        "de": "Passwort (mind. 6 Zeichen)",
        "it": "Password (min. 6 caratteri)",
        "nl": "Wachtwoord (min. 6 tekens)",
        "pl": "Hasło (min. 6 znaków)",
        "sv": "Lösenord (minst 6 tecken)",
        "tr": "Şifre (en az 6 karakter)",
        "ru": "Пароль (не менее 6 символов)",
        "ja": "パスワード（6文字以上）",
        "ko": "비밀번호 (6자 이상)",
        "zh-Hans": "密码（至少 6 位）",
    },
    "Un courrier vient de partir vers %@.": {
        "en": "An email is on its way to %@.",
        "es": "Acabamos de enviar un correo a %@.",
        "es-419": "Acabamos de enviar un correo a %@.",
        "pt-BR": "Acabamos de enviar um e-mail para %@.",
        "de": "Eine E-Mail ist gerade an %@ unterwegs.",
        "it": "Un'e-mail è appena partita verso %@.",
        "nl": "Er is zojuist een e-mail naar %@ verstuurd.",
        "pl": "Wiadomość właśnie poleciała na %@.",
        "sv": "Ett mejl är på väg till %@.",
        "tr": "%@ adresine bir e-posta yollandı.",
        "ru": "Письмо отправлено на %@.",
        "ja": "%@ にメールを送りました。",
        "ko": "%@ 으로 메일을 보냈어요.",
        "zh-Hans": "已向 %@ 发送邮件。",
    },
}

if __name__ == "__main__":
    ecrire(T)
