# -*- coding: utf-8 -*-
"""Traductions — vague 3 : recherche, scanner, découverte, session, citations."""
from catalogue import ecrire

T = {
    # ------------------------------------------------------------ recherche
    "Titre, auteur, série…": {
        "en": "Title, author, series…", "es": "Título, autor, serie…",
        "es-419": "Título, autor, serie…", "pt-BR": "Título, autor, série…",
        "de": "Titel, Autor, Reihe…", "it": "Titolo, autore, serie…",
        "pl": "Tytuł, autor, seria…", "ja": "タイトル、著者、シリーズ…",
    },
    "Recherche…": {
        "en": "Searching…", "es": "Buscando…", "es-419": "Buscando…",
        "pt-BR": "Buscando…", "de": "Suche läuft…", "it": "Ricerca…",
        "pl": "Szukam…", "ja": "検索中…",
    },
    "Langue des éditions :": {
        "en": "Edition language:", "es": "Idioma de las ediciones:",
        "es-419": "Idioma de las ediciones:", "pt-BR": "Idioma das edições:",
        "de": "Sprache der Ausgaben:", "it": "Lingua delle edizioni:",
        "pl": "Język wydań:", "ja": "版の言語：",
    },
    "Toutes les langues": {
        "en": "All languages", "es": "Todos los idiomas", "es-419": "Todos los idiomas",
        "pt-BR": "Todos os idiomas", "de": "Alle Sprachen", "it": "Tutte le lingue",
        "pl": "Wszystkie języki", "ja": "すべての言語",
    },
    "Ajouter un livre": {
        "en": "Add a book", "es": "Añadir un libro", "es-419": "Agregar un libro",
        "pt-BR": "Adicionar um livro", "de": "Buch hinzufügen",
        "it": "Aggiungi un libro", "pl": "Dodaj książkę", "ja": "本を追加",
    },
    "Populaires en ce moment": {
        "en": "Popular right now", "es": "Populares ahora mismo",
        "es-419": "Populares ahora", "pt-BR": "Populares agora",
        "de": "Gerade beliebt", "it": "Popolari in questo momento",
        "pl": "Teraz popularne", "ja": "いま人気",
    },
    "Tendances des recherches": {
        "en": "Trending searches", "es": "Búsquedas en tendencia",
        "es-419": "Búsquedas en tendencia", "pt-BR": "Buscas em alta",
        "de": "Beliebte Suchen", "it": "Ricerche di tendenza",
        "pl": "Popularne wyszukiwania", "ja": "話題の検索",
    },

    # -------------------------------------------------------------- scanner
    "Scanner un ISBN": {
        "en": "Scan an ISBN", "es": "Escanear un ISBN", "es-419": "Escanear un ISBN",
        "pt-BR": "Escanear um ISBN", "de": "ISBN scannen", "it": "Scansiona un ISBN",
        "pl": "Zeskanuj ISBN", "ja": "ISBNをスキャン",
    },
    "Scannez toute une étagère": {
        "en": "Scan a whole shelf", "es": "Escanea una estantería entera",
        "es-419": "Escanea un estante entero", "pt-BR": "Escaneie uma estante inteira",
        "de": "Scanne ein ganzes Regal", "it": "Scansiona un intero scaffale",
        "pl": "Zeskanuj całą półkę", "ja": "本棚をまるごとスキャン",
    },
    "Visez le code-barres au dos du livre": {
        "en": "Point at the barcode on the back of the book",
        "es": "Apunta al código de barras de la contraportada",
        "es-419": "Apunta al código de barras de la contratapa",
        "pt-BR": "Aponte para o código de barras na contracapa",
        "de": "Ziele auf den Strichcode auf der Buchrückseite",
        "it": "Inquadra il codice a barre sul retro del libro",
        "pl": "Wyceluj w kod kreskowy z tyłu książki",
        "ja": "本の裏の바코드にカメラを向けてください",
    },
    "Le code-barres au dos du livre suffit : titre, couverture et pages arrivent tout seuls, tome après tome.": {
        "en": "The barcode on the back is enough: title, cover and page count arrive on their own, volume after volume.",
        "es": "Basta el código de barras de la contraportada: título, portada y páginas llegan solos, tomo tras tomo.",
        "es-419": "Basta el código de barras de la contratapa: título, portada y páginas llegan solos, tomo tras tomo.",
        "pt-BR": "O código de barras da contracapa basta: título, capa e páginas chegam sozinhos, volume após volume.",
        "de": "Der Strichcode auf der Rückseite genügt: Titel, Cover und Seitenzahl kommen von selbst, Band für Band.",
        "it": "Basta il codice a barre sul retro: titolo, copertina e pagine arrivano da soli, volume dopo volume.",
        "pl": "Wystarczy kod kreskowy z tyłu: tytuł, okładka i liczba stron pojawią się same, tom po tomie.",
        "ja": "裏表紙のバーコードだけで十分。タイトル・表紙・ページ数が一巻ずつ自動で揃います。",
    },
    "Saisissez l'ISBN à la main (13 chiffres, sous le code-barres).": {
        "en": "Type the ISBN by hand (13 digits, under the barcode).",
        "es": "Escribe el ISBN a mano (13 cifras, bajo el código de barras).",
        "es-419": "Escribe el ISBN a mano (13 cifras, debajo del código de barras).",
        "pt-BR": "Digite o ISBN à mão (13 dígitos, sob o código de barras).",
        "de": "Gib die ISBN von Hand ein (13 Ziffern, unter dem Strichcode).",
        "it": "Inserisci l'ISBN a mano (13 cifre, sotto il codice a barre).",
        "pl": "Wpisz ISBN ręcznie (13 cyfr, pod kodem kreskowym).",
        "ja": "ISBNを手入力してください（バーコードの下、13桁）。",
    },
    "9782…": {"en": "9782…", "es": "9782…", "es-419": "9782…", "pt-BR": "9782…",
              "de": "9782…", "it": "9782…", "pl": "9782…", "ja": "9782…"},
    "Caméra indisponible ici": {
        "en": "Camera unavailable here", "es": "Cámara no disponible aquí",
        "es-419": "Cámara no disponible aquí", "pt-BR": "Câmera indisponível aqui",
        "de": "Kamera hier nicht verfügbar", "it": "Fotocamera non disponibile qui",
        "pl": "Aparat niedostępny", "ja": "ここではカメラを使えません",
    },
    "Recherche de %lld ISBN…": {
        "en": "Looking up %lld ISBNs…", "es": "Buscando %lld ISBN…",
        "es-419": "Buscando %lld ISBN…", "pt-BR": "Buscando %lld ISBNs…",
        "de": "%lld ISBNs werden gesucht…", "it": "Ricerca di %lld ISBN…",
        "pl": "Szukam %lld numerów ISBN…", "ja": "%lld件のISBNを検索中…",
    },
    "En attente": {
        "en": "Waiting", "es": "A la espera", "es-419": "A la espera",
        "pt-BR": "Aguardando", "de": "Bereit", "it": "In attesa",
        "pl": "Oczekiwanie", "ja": "待機中",
    },
    "%lld livres reconnus": {
        "en": "%lld books recognised", "es": "%lld libros reconocidos",
        "es-419": "%lld libros reconocidos", "pt-BR": "%lld livros reconhecidos",
        "de": "%lld Bücher erkannt", "it": "%lld libri riconosciuti",
        "pl": "Rozpoznano %lld książek", "ja": "%lld冊を認識",
    },
    "Les livres reconnus apparaîtront ici, prêts à rejoindre la bibliothèque.": {
        "en": "Recognised books appear here, ready to join your library.",
        "es": "Los libros reconocidos aparecerán aquí, listos para tu biblioteca.",
        "es-419": "Los libros reconocidos aparecerán aquí, listos para tu biblioteca.",
        "pt-BR": "Os livros reconhecidos aparecem aqui, prontos para a biblioteca.",
        "de": "Erkannte Bücher erscheinen hier, bereit für deine Bibliothek.",
        "it": "I libri riconosciuti appaiono qui, pronti per la libreria.",
        "pl": "Rozpoznane książki pojawią się tutaj, gotowe do biblioteki.",
        "ja": "認識した本がここに並び、ライブラリに追加できます。",
    },
    "Scannez un ISBN ou cherchez un titre pour poser votre premier livre sur l'étagère.": {
        "en": "Scan an ISBN or search a title to put your first book on the shelf.",
        "es": "Escanea un ISBN o busca un título para poner tu primer libro en la estantería.",
        "es-419": "Escanea un ISBN o busca un título para poner tu primer libro en el estante.",
        "pt-BR": "Escaneie um ISBN ou busque um título para pôr seu primeiro livro na estante.",
        "de": "Scanne eine ISBN oder suche einen Titel, um dein erstes Buch ins Regal zu stellen.",
        "it": "Scansiona un ISBN o cerca un titolo per mettere il tuo primo libro sullo scaffale.",
        "pl": "Zeskanuj ISBN albo wyszukaj tytuł, żeby postawić pierwszą książkę na półce.",
        "ja": "ISBNをスキャンするかタイトルを検索して、最初の一冊を本棚に置きましょう。",
    },

    # ------------------------------------------------------------ découverte
    "Nouveautés et tendances": {
        "en": "New and trending", "es": "Novedades y tendencias",
        "es-419": "Novedades y tendencias", "pt-BR": "Novidades e tendências",
        "de": "Neu und beliebt", "it": "Novità e tendenze",
        "pl": "Nowości i trendy", "ja": "新着と話題",
    },
    "Les incontournables du moment": {
        "en": "The ones everyone's reading", "es": "Los imprescindibles del momento",
        "es-419": "Los imprescindibles del momento", "pt-BR": "Os imperdíveis do momento",
        "de": "Was gerade alle lesen", "it": "Gli imperdibili del momento",
        "pl": "To, co teraz czytają wszyscy", "ja": "いま外せない一冊",
    },
    "Mangas populaires": {
        "en": "Popular manga", "es": "Manga popular", "es-419": "Manga popular",
        "pt-BR": "Mangás populares", "de": "Beliebte Mangas",
        "it": "Manga popolari", "pl": "Popularne mangi", "ja": "人気のマンガ",
    },
    "Polars & thrillers": {
        "en": "Crime & thrillers", "es": "Novela negra y thrillers",
        "es-419": "Novela negra y thrillers", "pt-BR": "Policiais e thrillers",
        "de": "Krimis & Thriller", "it": "Gialli e thriller",
        "pl": "Kryminały i thrillery", "ja": "ミステリー＆スリラー",
    },
    "Polar": {
        "en": "Crime", "es": "Novela negra", "es-419": "Novela negra",
        "pt-BR": "Policial", "de": "Krimi", "it": "Giallo",
        "pl": "Kryminał", "ja": "ミステリー",
    },
    "Romance": {
        "en": "Romance", "es": "Romántica", "es-419": "Romántica",
        "pt-BR": "Romance", "de": "Liebesroman", "it": "Rosa",
        "pl": "Romans", "ja": "恋愛",
    },
    "SF et fantasy": {
        "en": "Sci-fi & fantasy", "es": "Ciencia ficción y fantasía",
        "es-419": "Ciencia ficción y fantasía", "pt-BR": "Ficção científica e fantasia",
        "de": "Science-Fiction & Fantasy", "it": "Fantascienza e fantasy",
        "pl": "Fantastyka", "ja": "SF・ファンタジー",
    },
    "SF & Fantasy": {
        "en": "Sci-fi & fantasy", "es": "Ciencia ficción y fantasía",
        "es-419": "Ciencia ficción y fantasía", "pt-BR": "Ficção científica e fantasia",
        "de": "Science-Fiction & Fantasy", "it": "Fantascienza e fantasy",
        "pl": "Fantastyka", "ja": "SF・ファンタジー",
    },
    "Jeunesse": {
        "en": "Children's", "es": "Infantil y juvenil", "es-419": "Infantil y juvenil",
        "pt-BR": "Infantojuvenil", "de": "Kinder & Jugend", "it": "Per ragazzi",
        "pl": "Dla dzieci i młodzieży", "ja": "児童書",
    },
    "BD & Comics": {
        "en": "Comics & graphic novels", "es": "Cómic y novela gráfica",
        "es-419": "Cómic y novela gráfica", "pt-BR": "HQs e graphic novels",
        "de": "Comics & Graphic Novels", "it": "Fumetti e graphic novel",
        "pl": "Komiksy i powieści graficzne", "ja": "コミック",
    },
    "Dans vos goûts": {
        "en": "In your taste", "es": "A tu gusto", "es-419": "A tu gusto",
        "pt-BR": "No seu gosto", "de": "Nach deinem Geschmack",
        "it": "Nei tuoi gusti", "pl": "W Twoim guście", "ja": "あなた好みの本",
    },
    "Choisi d'après votre bibliothèque": {
        "en": "Chosen from your library", "es": "Elegido según tu biblioteca",
        "es-419": "Elegido según tu biblioteca", "pt-BR": "Escolhido pela sua biblioteca",
        "de": "Aus deiner Bibliothek abgeleitet", "it": "Scelto dalla tua libreria",
        "pl": "Wybrane na podstawie Twojej biblioteki", "ja": "あなたのライブラリから選びました",
    },
    "Bientôt disponibles !": {
        "en": "Coming soon!", "es": "¡Próximamente!", "es-419": "¡Próximamente!",
        "pt-BR": "Em breve!", "de": "Bald erhältlich!", "it": "Prossimamente!",
        "pl": "Już wkrótce!", "ja": "まもなく発売！",
    },
    "Les précommandes du catalogue": {
        "en": "Pre-orders in the catalogue", "es": "Las reservas del catálogo",
        "es-419": "Las preventas del catálogo", "pt-BR": "As pré-vendas do catálogo",
        "de": "Vorbestellungen im Katalog", "it": "I preordini del catalogo",
        "pl": "Przedsprzedaże z katalogu", "ja": "カタログの予約商品",
    },
    "Gratuits en ce moment": {
        "en": "Free right now", "es": "Gratis ahora mismo", "es-419": "Gratis ahora",
        "pt-BR": "Grátis agora", "de": "Gerade kostenlos", "it": "Gratis in questo momento",
        "pl": "Teraz za darmo", "ja": "いま無料",
    },
    "Excellentes lectures à zéro euro": {
        "en": "Excellent reads for nothing", "es": "Excelentes lecturas por cero euros",
        "es-419": "Excelentes lecturas sin costo", "pt-BR": "Ótimas leituras a custo zero",
        "de": "Großartige Bücher für null Euro", "it": "Ottime letture a costo zero",
        "pl": "Świetne lektury za zero złotych", "ja": "0円で読める良書",
    },
    "Classements": {
        "en": "Charts", "es": "Rankings", "es-419": "Rankings",
        "pt-BR": "Rankings", "de": "Charts", "it": "Classifiche",
        "pl": "Rankingi", "ja": "ランキング",
    },
    "Payant": {
        "en": "Paid", "es": "De pago", "es-419": "De pago", "pt-BR": "Pagos",
        "de": "Kostenpflichtig", "it": "A pagamento", "pl": "Płatne", "ja": "有料",
    },
    "Gratuit": {
        "en": "Free", "es": "Gratis", "es-419": "Gratis", "pt-BR": "Grátis",
        "de": "Kostenlos", "it": "Gratis", "pl": "Bezpłatne", "ja": "無料",
    },
    "Parcourir par genre": {
        "en": "Browse by genre", "es": "Explorar por género",
        "es-419": "Explorar por género", "pt-BR": "Explorar por gênero",
        "de": "Nach Genre stöbern", "it": "Sfoglia per genere",
        "pl": "Przeglądaj według gatunku", "ja": "ジャンルで探す",
    },
    "Le libraire installe l'étal…": {
        "en": "The bookseller is setting out the display…",
        "es": "El librero está montando el escaparate…",
        "es-419": "El librero está armando la mesa…",
        "pt-BR": "O livreiro está montando a vitrine…",
        "de": "Der Buchhändler richtet die Auslage ein…",
        "it": "Il libraio sta allestendo il banco…",
        "pl": "Księgarz układa stoisko…",
        "ja": "書店員が棚を並べています…",
    },

    # -------------------------------------------------------------- session
    "Lecture": {
        "en": "Reading", "es": "Lectura", "es-419": "Lectura", "pt-BR": "Leitura",
        "de": "Lesen", "it": "Lettura", "pl": "Czytanie", "ja": "読書",
    },
    "Session de lecture": {
        "en": "Reading session", "es": "Sesión de lectura", "es-419": "Sesión de lectura",
        "pt-BR": "Sessão de leitura", "de": "Lesesitzung", "it": "Sessione di lettura",
        "pl": "Sesja czytania", "ja": "読書セッション",
    },
    "Commencer une lecture": {
        "en": "Start reading", "es": "Empezar a leer", "es-419": "Empezar a leer",
        "pt-BR": "Começar a ler", "de": "Zu lesen beginnen",
        "it": "Inizia a leggere", "pl": "Zacznij czytać", "ja": "読み始める",
    },
    "Continuer la lecture": {
        "en": "Keep reading", "es": "Seguir leyendo", "es-419": "Seguir leyendo",
        "pt-BR": "Continuar lendo", "de": "Weiterlesen", "it": "Continua a leggere",
        "pl": "Czytaj dalej", "ja": "読書を続ける",
    },
    "Continuer à lire": {
        "en": "Keep reading", "es": "Seguir leyendo", "es-419": "Seguir leyendo",
        "pt-BR": "Continuar lendo", "de": "Weiterlesen", "it": "Continua a leggere",
        "pl": "Czytaj dalej", "ja": "読書を続ける",
    },
    "Reprendre": {
        "en": "Resume", "es": "Reanudar", "es-419": "Reanudar", "pt-BR": "Retomar",
        "de": "Fortsetzen", "it": "Riprendi", "pl": "Wznów", "ja": "再開",
    },
    "Reprendre · p. %lld": {
        "en": "Resume · p. %lld", "es": "Reanudar · p. %lld",
        "es-419": "Reanudar · p. %lld", "pt-BR": "Retomar · p. %lld",
        "de": "Fortsetzen · S. %lld", "it": "Riprendi · p. %lld",
        "pl": "Wznów · s. %lld", "ja": "再開・%lldページ",
    },
    "Relire": {
        "en": "Read again", "es": "Releer", "es-419": "Releer", "pt-BR": "Reler",
        "de": "Noch mal lesen", "it": "Rileggi", "pl": "Przeczytaj ponownie",
        "ja": "読み返す",
    },
    "Pause": {
        "en": "Pause", "es": "Pausa", "es-419": "Pausa", "pt-BR": "Pausar",
        "de": "Pause", "it": "Pausa", "pl": "Pauza", "ja": "一時停止",
    },
    "Terminer la session": {
        "en": "End session", "es": "Terminar la sesión", "es-419": "Terminar la sesión",
        "pt-BR": "Encerrar a sessão", "de": "Sitzung beenden",
        "it": "Termina la sessione", "pl": "Zakończ sesję", "ja": "セッションを終える",
    },
    "Abandonner cette session ?": {
        "en": "Discard this session?", "es": "¿Descartar esta sesión?",
        "es-419": "¿Descartar esta sesión?", "pt-BR": "Descartar esta sessão?",
        "de": "Diese Sitzung verwerfen?", "it": "Abbandonare questa sessione?",
        "pl": "Odrzucić tę sesję?", "ja": "このセッションを破棄しますか？",
    },
    "Abandonner sans enregistrer": {
        "en": "Discard without saving", "es": "Descartar sin guardar",
        "es-419": "Descartar sin guardar", "pt-BR": "Descartar sem salvar",
        "de": "Verwerfen, ohne zu sichern", "it": "Abbandona senza salvare",
        "pl": "Odrzuć bez zapisywania", "ja": "保存せずに破棄",
    },
    "L'écran reste allumé pendant la session.": {
        "en": "The screen stays awake during the session.",
        "es": "La pantalla permanece encendida durante la sesión.",
        "es-419": "La pantalla permanece encendida durante la sesión.",
        "pt-BR": "A tela permanece acesa durante a sessão.",
        "de": "Der Bildschirm bleibt während der Sitzung an.",
        "it": "Lo schermo resta acceso durante la sessione.",
        "pl": "Ekran pozostaje włączony przez całą sesję.",
        "ja": "セッション中は画面が消えません。",
    },
    "Où en es-tu ?": {
        "en": "Where are you up to?", "es": "¿Por dónde vas?",
        "es-419": "¿Por dónde vas?", "pt-BR": "Onde você parou?",
        "de": "Wo bist du gerade?", "it": "A che punto sei?",
        "pl": "Gdzie skończyłeś?", "ja": "どこまで読みましたか？",
    },
    "Numéro de page": {
        "en": "Page number", "es": "Número de página", "es-419": "Número de página",
        "pt-BR": "Número da página", "de": "Seitenzahl", "it": "Numero di pagina",
        "pl": "Numer strony", "ja": "ページ番号",
    },
    "Page (optionnel)": {
        "en": "Page (optional)", "es": "Página (opcional)", "es-419": "Página (opcional)",
        "pt-BR": "Página (opcional)", "de": "Seite (optional)",
        "it": "Pagina (facoltativo)", "pl": "Strona (opcjonalnie)",
        "ja": "ページ（任意）",
    },
    "L'humeur de cette session (optionnel)": {
        "en": "How this session felt (optional)",
        "es": "El ánimo de esta sesión (opcional)",
        "es-419": "El ánimo de esta sesión (opcional)",
        "pt-BR": "O clima desta sessão (opcional)",
        "de": "Die Stimmung dieser Sitzung (optional)",
        "it": "L'umore di questa sessione (facoltativo)",
        "pl": "Nastrój tej sesji (opcjonalnie)",
        "ja": "このセッションの気分（任意）",
    },
    "Belle session !": {
        "en": "Good session!", "es": "¡Buena sesión!", "es-419": "¡Buena sesión!",
        "pt-BR": "Boa sessão!", "de": "Schöne Sitzung!", "it": "Bella sessione!",
        "pl": "Udana sesja!", "ja": "いい読書でした！",
    },
    "Mettre à jour": {
        "en": "Update", "es": "Actualizar", "es-419": "Actualizar",
        "pt-BR": "Atualizar", "de": "Aktualisieren", "it": "Aggiorna",
        "pl": "Zaktualizuj", "ja": "更新",
    },
    "J'ai terminé ce livre": {
        "en": "I've finished this book", "es": "He terminado este libro",
        "es-419": "Terminé este libro", "pt-BR": "Terminei este livro",
        "de": "Ich habe dieses Buch beendet", "it": "Ho finito questo libro",
        "pl": "Skończyłem tę książkę", "ja": "この本を読み終えた",
    },
    "Terminé": {
        "en": "Finished", "es": "Terminado", "es-419": "Terminado",
        "pt-BR": "Concluído", "de": "Fertig", "it": "Finito",
        "pl": "Ukończone", "ja": "完了",
    },
    "Terminé !": {
        "en": "Finished!", "es": "¡Terminado!", "es-419": "¡Terminado!",
        "pt-BR": "Concluído!", "de": "Geschafft!", "it": "Finito!",
        "pl": "Ukończone!", "ja": "読了！",
    },
    "p. %lld": {"en": "p. %lld", "es": "p. %lld", "es-419": "p. %lld",
                "pt-BR": "p. %lld", "de": "S. %lld", "it": "p. %lld",
                "pl": "s. %lld", "ja": "%lldページ"},
    "p. %lld sur %lld": {
        "en": "p. %lld of %lld", "es": "p. %lld de %lld", "es-419": "p. %lld de %lld",
        "pt-BR": "p. %lld de %lld", "de": "S. %lld von %lld",
        "it": "p. %lld di %lld", "pl": "s. %lld z %lld", "ja": "%lld / %lldページ",
    },
    "p. %lld sur %lld · %lld %%": {
        "en": "p. %lld of %lld · %lld %%", "es": "p. %lld de %lld · %lld %%",
        "es-419": "p. %lld de %lld · %lld %%", "pt-BR": "p. %lld de %lld · %lld %%",
        "de": "S. %lld von %lld · %lld %%", "it": "p. %lld di %lld · %lld %%",
        "pl": "s. %lld z %lld · %lld %%", "ja": "%lld / %lldページ · %lld %%",
    },
    "Pages lues : %lld": {
        "en": "Pages read: %lld", "es": "Páginas leídas: %lld",
        "es-419": "Páginas leídas: %lld", "pt-BR": "Páginas lidas: %lld",
        "de": "Gelesene Seiten: %lld", "it": "Pagine lette: %lld",
        "pl": "Przeczytane strony: %lld", "ja": "読んだページ：%lld",
    },
    "%lld min au total": {
        "en": "%lld min in total", "es": "%lld min en total",
        "es-419": "%lld min en total", "pt-BR": "%lld min no total",
        "de": "%lld Min. insgesamt", "it": "%lld min in totale",
        "pl": "łącznie %lld min", "ja": "合計%lld分",
    },
    "%lld min · %lld p.": {
        "en": "%lld min · %lld p.", "es": "%lld min · %lld p.",
        "es-419": "%lld min · %lld p.", "pt-BR": "%lld min · %lld p.",
        "de": "%lld Min. · %lld S.", "it": "%lld min · %lld p.",
        "pl": "%lld min · %lld s.", "ja": "%lld分 · %lldページ",
    },
    "%lld min": {
        "en": "%lld min", "es": "%lld min", "es-419": "%lld min",
        "pt-BR": "%lld min", "de": "%lld Min.", "it": "%lld min",
        "pl": "%lld min", "ja": "%lld分",
    },
    "%lld h": {"en": "%lld h", "es": "%lld h", "es-419": "%lld h", "pt-BR": "%lld h",
               "de": "%lld Std.", "it": "%lld h", "pl": "%lld godz.", "ja": "%lld時間"},
    "%lld h %@": {"en": "%lld h %@", "es": "%lld h %@", "es-419": "%lld h %@",
                  "pt-BR": "%lld h %@", "de": "%lld Std. %@", "it": "%lld h %@",
                  "pl": "%lld godz. %@", "ja": "%lld時間%@分"},
    "%lld %@": {"en": "%lld %@", "es": "%lld %@", "es-419": "%lld %@",
                "pt-BR": "%lld %@", "de": "%lld %@", "it": "%lld %@",
                "pl": "%lld %@", "ja": "%lld %@"},
    "%lld": {"en": "%lld", "es": "%lld", "es-419": "%lld", "pt-BR": "%lld",
             "de": "%lld", "it": "%lld", "pl": "%lld", "ja": "%lld"},
    "· %@": {"en": "· %@", "es": "· %@", "es-419": "· %@", "pt-BR": "· %@",
             "de": "· %@", "it": "· %@", "pl": "· %@", "ja": "· %@"},
    "%@ · %lld": {"en": "%@ · %lld", "es": "%@ · %lld", "es-419": "%@ · %lld",
                  "pt-BR": "%@ · %lld", "de": "%@ · %lld", "it": "%@ · %lld",
                  "pl": "%@ · %lld", "ja": "%@ · %lld"},
    "%@ : %lld minutes": {
        "en": "%@: %lld minutes", "es": "%@: %lld minutos", "es-419": "%@: %lld minutos",
        "pt-BR": "%@: %lld minutos", "de": "%@: %lld Minuten",
        "it": "%@: %lld minuti", "pl": "%@: %lld min", "ja": "%@：%lld分",
    },
    "%lld pages": {
        "en": "%lld pages", "es": "%lld páginas", "es-419": "%lld páginas",
        "pt-BR": "%lld páginas", "de": "%lld Seiten", "it": "%lld pagine",
        "pl": "%lld stron", "ja": "%lldページ",
    },
    "%lld pages.": {
        "en": "%lld pages.", "es": "%lld páginas.", "es-419": "%lld páginas.",
        "pt-BR": "%lld páginas.", "de": "%lld Seiten.", "it": "%lld pagine.",
        "pl": "%lld stron.", "ja": "%lldページ。",
    },
    "Lu le %@.": {
        "en": "Read on %@.", "es": "Leído el %@.", "es-419": "Leído el %@.",
        "pt-BR": "Lido em %@.", "de": "Gelesen am %@.", "it": "Letto il %@.",
        "pl": "Przeczytane %@.", "ja": "%@に読了。",
    },

    # ------------------------------------------------------------- citations
    "Citations": {
        "en": "Quotes", "es": "Citas", "es-419": "Citas", "pt-BR": "Citações",
        "de": "Zitate", "it": "Citazioni", "pl": "Cytaty", "ja": "引用",
    },
    "Aucune citation": {
        "en": "No quotes yet", "es": "Ninguna cita todavía",
        "es-419": "Ninguna cita todavía", "pt-BR": "Nenhuma citação ainda",
        "de": "Noch keine Zitate", "it": "Nessuna citazione",
        "pl": "Brak cytatów", "ja": "引用はまだありません",
    },
    "Nouvelle citation": {
        "en": "New quote", "es": "Nueva cita", "es-419": "Nueva cita",
        "pt-BR": "Nova citação", "de": "Neues Zitat", "it": "Nuova citazione",
        "pl": "Nowy cytat", "ja": "新しい引用",
    },
    "La phrase": {
        "en": "The sentence", "es": "La frase", "es-419": "La frase",
        "pt-BR": "A frase", "de": "Der Satz", "it": "La frase",
        "pl": "Zdanie", "ja": "その一文",
    },
    "Recopiez la citation…": {
        "en": "Copy the quote out…", "es": "Copia la cita…", "es-419": "Copia la cita…",
        "pt-BR": "Copie a citação…", "de": "Zitat abschreiben…",
        "it": "Ricopia la citazione…", "pl": "Przepisz cytat…", "ja": "引用を書き写す…",
    },
    "Gardez ici les phrases qui vous ont arrêté.": {
        "en": "Keep here the sentences that stopped you.",
        "es": "Guarda aquí las frases que te hicieron detenerte.",
        "es-419": "Guarda aquí las frases que te hicieron detenerte.",
        "pt-BR": "Guarde aqui as frases que fizeram você parar.",
        "de": "Bewahre hier die Sätze auf, bei denen du innegehalten hast.",
        "it": "Conserva qui le frasi che ti hanno fermato.",
        "pl": "Zbieraj tu zdania, przy których się zatrzymałeś.",
        "ja": "思わず手が止まった一文を、ここに残しましょう。",
    },
    "« %@ »": {"en": "“%@”", "es": "«%@»", "es-419": "«%@»", "pt-BR": "“%@”",
               "de": "„%@“", "it": "«%@»", "pl": "„%@”", "ja": "「%@」"},
}

if __name__ == "__main__":
    ecrire(T)
