# -*- coding: utf-8 -*-
"""Traductions — vague 2 : bibliothèque, fiches, tomes, étagères."""
from catalogue import ecrire

T = {
    # ------------------------------------------------------- bibliothèque
    "Tous": {"en": "All", "es": "Todos", "es-419": "Todos", "pt-BR": "Todos",
             "de": "Alle", "it": "Tutti", "pl": "Wszystkie", "ja": "すべて"},
    "Lus": {"en": "Read", "es": "Leídos", "es-419": "Leídos", "pt-BR": "Lidos",
            "de": "Gelesen", "it": "Letti", "pl": "Przeczytane", "ja": "読了"},
    "Livres": {"en": "Books", "es": "Libros", "es-419": "Libros", "pt-BR": "Livros",
               "de": "Bücher", "it": "Libri", "pl": "Książki", "ja": "書籍"},
    "Mangas": {"en": "Manga", "es": "Manga", "es-419": "Manga", "pt-BR": "Mangás",
               "de": "Mangas", "it": "Manga", "pl": "Mangi", "ja": "マンガ"},
    "Titre": {"en": "Title", "es": "Título", "es-419": "Título", "pt-BR": "Título",
              "de": "Titel", "it": "Titolo", "pl": "Tytuł", "ja": "タイトル"},
    "Ajouts récents": {
        "en": "Recently added", "es": "Añadidos recientemente",
        "es-419": "Agregados recientemente", "pt-BR": "Adicionados recentemente",
        "de": "Zuletzt hinzugefügt", "it": "Aggiunti di recente",
        "pl": "Ostatnio dodane", "ja": "最近追加",
    },
    "Récemment ajoutés": {
        "en": "Recently added", "es": "Añadidos recientemente",
        "es-419": "Agregados recientemente", "pt-BR": "Adicionados recentemente",
        "de": "Zuletzt hinzugefügt", "it": "Aggiunti di recente",
        "pl": "Ostatnio dodane", "ja": "最近追加した本",
    },
    "Afficher en grille": {
        "en": "Show as grid", "es": "Ver en cuadrícula", "es-419": "Ver en cuadrícula",
        "pt-BR": "Ver em grade", "de": "Als Raster", "it": "Vista a griglia",
        "pl": "Widok siatki", "ja": "グリッド表示",
    },
    "Afficher en liste": {
        "en": "Show as list", "es": "Ver en lista", "es-419": "Ver en lista",
        "pt-BR": "Ver em lista", "de": "Als Liste", "it": "Vista a elenco",
        "pl": "Widok listy", "ja": "リスト表示",
    },
    "Rien ici pour l'instant": {
        "en": "Nothing here yet", "es": "Aquí no hay nada todavía",
        "es-419": "Aquí no hay nada todavía", "pt-BR": "Nada aqui ainda",
        "de": "Hier ist noch nichts", "it": "Qui non c'è ancora nulla",
        "pl": "Jeszcze tu pusto", "ja": "まだ何もありません",
    },
    "Ajoutez des envies depuis la recherche.": {
        "en": "Add the ones you want from Search.",
        "es": "Añade tus antojos desde la búsqueda.",
        "es-419": "Agrega tus antojos desde la búsqueda.",
        "pt-BR": "Adicione seus desejos pela busca.",
        "de": "Füge Wünsche über die Suche hinzu.",
        "it": "Aggiungi i tuoi desideri dalla ricerca.",
        "pl": "Dodaj to, na co masz ochotę, przez wyszukiwarkę.",
        "ja": "検索から欲しい本を追加しましょう。",
    },
    "Ajoutez des livres ou des séries depuis la recherche.": {
        "en": "Add books or series from Search.",
        "es": "Añade libros o series desde la búsqueda.",
        "es-419": "Agrega libros o series desde la búsqueda.",
        "pt-BR": "Adicione livros ou séries pela busca.",
        "de": "Füge Bücher oder Reihen über die Suche hinzu.",
        "it": "Aggiungi libri o serie dalla ricerca.",
        "pl": "Dodaj książki lub serie przez wyszukiwarkę.",
        "ja": "検索から本やシリーズを追加しましょう。",
    },
    "Votre bibliothèque est vide": {
        "en": "Your library is empty", "es": "Tu biblioteca está vacía",
        "es-419": "Tu biblioteca está vacía", "pt-BR": "Sua biblioteca está vazia",
        "de": "Deine Bibliothek ist leer", "it": "La tua libreria è vuota",
        "pl": "Twoja biblioteka jest pusta", "ja": "ライブラリは空です",
    },
    "%lld livres": {
        "en": "%lld books", "es": "%lld libros", "es-419": "%lld libros",
        "pt-BR": "%lld livros", "de": "%lld Bücher", "it": "%lld libri",
        "pl": "%lld książek", "ja": "%lld冊",
    },
    "%lld séries": {
        "en": "%lld series", "es": "%lld series", "es-419": "%lld series",
        "pt-BR": "%lld séries", "de": "%lld Reihen", "it": "%lld serie",
        "pl": "%lld serii", "ja": "%lldシリーズ",
    },
    "%lld prêtés": {
        "en": "%lld lent out", "es": "%lld prestados", "es-419": "%lld prestados",
        "pt-BR": "%lld emprestados", "de": "%lld verliehen", "it": "%lld prestati",
        "pl": "%lld wypożyczonych", "ja": "%lld冊貸出中",
    },
    "%lld possédés · %lld lus": {
        "en": "%lld owned · %lld read", "es": "%lld en estantería · %lld leídos",
        "es-419": "%lld en estantería · %lld leídos", "pt-BR": "%lld na estante · %lld lidos",
        "de": "%lld im Regal · %lld gelesen", "it": "%lld posseduti · %lld letti",
        "pl": "%lld na półce · %lld przeczytanych", "ja": "所有%lld · 読了%lld",
    },
    "%lld/%lld": {
        "en": "%lld/%lld", "es": "%lld/%lld", "es-419": "%lld/%lld",
        "pt-BR": "%lld/%lld", "de": "%lld/%lld", "it": "%lld/%lld",
        "pl": "%lld/%lld", "ja": "%lld/%lld",
    },

    # ------------------------------------------------------------ étagères
    "Mes étagères": {
        "en": "My shelves", "es": "Mis estanterías", "es-419": "Mis estantes",
        "pt-BR": "Minhas estantes", "de": "Meine Regale", "it": "I miei scaffali",
        "pl": "Moje półki", "ja": "マイ本棚",
    },
    "Par statut": {
        "en": "By status", "es": "Por estado", "es-419": "Por estado",
        "pt-BR": "Por status", "de": "Nach Status", "it": "Per stato",
        "pl": "Według statusu", "ja": "ステータス別",
    },
    "Automatiques": {
        "en": "Automatic", "es": "Automáticas", "es-419": "Automáticas",
        "pt-BR": "Automáticas", "de": "Automatisch", "it": "Automatici",
        "pl": "Automatyczne", "ja": "自動",
    },
    "Nouvelle étagère": {
        "en": "New shelf", "es": "Nueva estantería", "es-419": "Nuevo estante",
        "pt-BR": "Nova estante", "de": "Neues Regal", "it": "Nuovo scaffale",
        "pl": "Nowa półka", "ja": "新しい本棚",
    },
    "Nouvelle étagère…": {
        "en": "New shelf…", "es": "Nueva estantería…", "es-419": "Nuevo estante…",
        "pt-BR": "Nova estante…", "de": "Neues Regal…", "it": "Nuovo scaffale…",
        "pl": "Nowa półka…", "ja": "新しい本棚…",
    },
    "Nouvelle collection": {
        "en": "New collection", "es": "Nueva colección", "es-419": "Nueva colección",
        "pt-BR": "Nova coleção", "de": "Neue Sammlung", "it": "Nuova raccolta",
        "pl": "Nowa kolekcja", "ja": "新しいコレクション",
    },
    "Ranger dans une étagère": {
        "en": "Put on a shelf", "es": "Colocar en una estantería",
        "es-419": "Poner en un estante", "pt-BR": "Guardar em uma estante",
        "de": "Ins Regal stellen", "it": "Metti su uno scaffale",
        "pl": "Odłóż na półkę", "ja": "本棚に入れる",
    },
    "Son nom": {
        "en": "Its name", "es": "Su nombre", "es-419": "Su nombre",
        "pt-BR": "O nome", "de": "Sein Name", "it": "Il nome",
        "pl": "Nazwa", "ja": "名前",
    },
    "« %@ » y sera rangé aussitôt.": {
        "en": "“%@” will go there right away.",
        "es": "«%@» se colocará ahí enseguida.",
        "es-419": "«%@» se colocará ahí enseguida.",
        "pt-BR": "“%@” vai para lá na hora.",
        "de": "„%@“ wandert sofort hinein.",
        "it": "«%@» ci finirà subito.",
        "pl": "„%@” trafi tam od razu.",
        "ja": "「%@」がすぐに入ります。",
    },
    "Étagère vide": {
        "en": "Empty shelf", "es": "Estantería vacía", "es-419": "Estante vacío",
        "pt-BR": "Estante vazia", "de": "Leeres Regal", "it": "Scaffale vuoto",
        "pl": "Pusta półka", "ja": "空の本棚",
    },
    "Ces étagères se remplissent toutes seules d'après vos statuts, vos notes et vos dates d'achat.": {
        "en": "These shelves fill themselves from your statuses, ratings and purchase dates.",
        "es": "Estas estanterías se llenan solas según tus estados, valoraciones y fechas de compra.",
        "es-419": "Estos estantes se llenan solos según tus estados, calificaciones y fechas de compra.",
        "pt-BR": "Estas estantes se enchem sozinhas a partir dos seus status, avaliações e datas de compra.",
        "de": "Diese Regale füllen sich von selbst — nach Status, Bewertung und Kaufdatum.",
        "it": "Questi scaffali si riempiono da soli in base a stati, voti e date d'acquisto.",
        "pl": "Te półki zapełniają się same — na podstawie statusów, ocen i dat zakupu.",
        "ja": "これらの本棚は、ステータス・評価・購入日から自動で埋まります。",
    },
    "Créez une étagère ici avec « + », puis rangez-y un livre ou une série depuis sa fiche (menu « … ») ou par un appui long dans la bibliothèque.": {
        "en": "Create a shelf here with “+”, then put a book or series on it from its page (the “…” menu) or by pressing and holding in your library.",
        "es": "Crea una estantería aquí con «+» y luego coloca en ella un libro o una serie desde su ficha (menú «…») o manteniendo pulsado en la biblioteca.",
        "es-419": "Crea un estante aquí con «+» y luego pon en él un libro o una serie desde su ficha (menú «…») o manteniendo presionado en la biblioteca.",
        "pt-BR": "Crie uma estante aqui com “+” e depois guarde nela um livro ou série pela ficha (menu “…”) ou segurando o toque na biblioteca.",
        "de": "Lege hier mit „+“ ein Regal an und stelle dann ein Buch oder eine Reihe hinein — über die Detailseite (Menü „…“) oder mit langem Drücken in der Bibliothek.",
        "it": "Crea qui uno scaffale con «+», poi mettici un libro o una serie dalla sua scheda (menu «…») o con un tocco prolungato nella libreria.",
        "pl": "Utwórz tu półkę przyciskiem „+”, a potem odłóż na nią książkę lub serię z jej strony (menu „…”) albo długim przytrzymaniem w bibliotece.",
        "ja": "「+」で本棚を作り、作品ページの「…」メニューかライブラリの長押しから本やシリーズを入れてください。",
    },

    # ------------------------------------------ collections automatiques
    "Séries incomplètes": {
        "en": "Incomplete series", "es": "Series incompletas",
        "es-419": "Series incompletas", "pt-BR": "Séries incompletas",
        "de": "Unvollständige Reihen", "it": "Serie incomplete",
        "pl": "Niekompletne serie", "ja": "未完のシリーズ",
    },
    "Coups de cœur": {
        "en": "Favourites", "es": "Favoritos", "es-419": "Favoritos",
        "pt-BR": "Favoritos", "de": "Lieblingsbücher", "it": "Preferiti",
        "pl": "Ulubione", "ja": "お気に入り",
    },
    "Achetés cette année": {
        "en": "Bought this year", "es": "Comprados este año",
        "es-419": "Comprados este año", "pt-BR": "Comprados este ano",
        "de": "Dieses Jahr gekauft", "it": "Comprati quest'anno",
        "pl": "Kupione w tym roku", "ja": "今年買った本",
    },
    "Jamais ouverts": {
        "en": "Never opened", "es": "Nunca abiertos", "es-419": "Nunca abiertos",
        "pt-BR": "Nunca abertos", "de": "Nie geöffnet", "it": "Mai aperti",
        "pl": "Nigdy nieotwarte", "ja": "未読のまま",
    },
    "Prêtés": {
        "en": "Lent out", "es": "Prestados", "es-419": "Prestados",
        "pt-BR": "Emprestados", "de": "Verliehen", "it": "Prestati",
        "pl": "Wypożyczone", "ja": "貸出中",
    },

    # ------------------------------------------------------------- tomes
    "Tomes parus": {
        "en": "Volumes published", "es": "Tomos publicados", "es-419": "Tomos publicados",
        "pt-BR": "Volumes publicados", "de": "Erschienene Bände",
        "it": "Volumi usciti", "pl": "Wydane tomy", "ja": "既刊",
    },
    "%lld tomes": {
        "en": "%lld volumes", "es": "%lld tomos", "es-419": "%lld tomos",
        "pt-BR": "%lld volumes", "de": "%lld Bände", "it": "%lld volumi",
        "pl": "%lld tomów", "ja": "%lld巻",
    },
    "%lld tomes · %@": {
        "en": "%lld volumes · %@", "es": "%lld tomos · %@", "es-419": "%lld tomos · %@",
        "pt-BR": "%lld volumes · %@", "de": "%lld Bände · %@",
        "it": "%lld volumi · %@", "pl": "%lld tomów · %@", "ja": "%lld巻 · %@",
    },
    "Tome %lld lu": {
        "en": "Volume %lld read", "es": "Tomo %lld leído", "es-419": "Tomo %lld leído",
        "pt-BR": "Volume %lld lido", "de": "Band %lld gelesen",
        "it": "Volume %lld letto", "pl": "Tom %lld przeczytany", "ja": "%lld巻を読了",
    },
    "Tome %lld —": {
        "en": "Volume %lld —", "es": "Tomo %lld —", "es-419": "Tomo %lld —",
        "pt-BR": "Volume %lld —", "de": "Band %lld —", "it": "Volume %lld —",
        "pl": "Tom %lld —", "ja": "%lld巻 —",
    },
    "Retirer ce tome": {
        "en": "Remove this volume", "es": "Quitar este tomo", "es-419": "Quitar este tomo",
        "pt-BR": "Remover este volume", "de": "Diesen Band entfernen",
        "it": "Rimuovi questo volume", "pl": "Usuń ten tom", "ja": "この巻を取り除く",
    },
    "Tout marquer lu jusqu'ici": {
        "en": "Mark all read up to here", "es": "Marcar todo leído hasta aquí",
        "es-419": "Marcar todo leído hasta aquí", "pt-BR": "Marcar tudo lido até aqui",
        "de": "Alle bis hier als gelesen", "it": "Segna tutto letto fin qui",
        "pl": "Oznacz wszystko do tego miejsca jako przeczytane",
        "ja": "ここまですべて読了にする",
    },
    "Toute la série lue": {
        "en": "Whole series read", "es": "Serie entera leída",
        "es-419": "Serie entera leída", "pt-BR": "Série inteira lida",
        "de": "Ganze Reihe gelesen", "it": "Intera serie letta",
        "pl": "Cała seria przeczytana", "ja": "シリーズ全巻を読了",
    },
    "Possédés jusqu'au tome": {
        "en": "Owned up to volume", "es": "En estantería hasta el tomo",
        "es-419": "En estantería hasta el tomo", "pt-BR": "Na estante até o volume",
        "de": "Im Regal bis Band", "it": "Posseduti fino al volume",
        "pl": "Na półce do tomu", "ja": "所有は何巻まで",
    },
    "Lus jusqu'au tome": {
        "en": "Read up to volume", "es": "Leídos hasta el tomo",
        "es-419": "Leídos hasta el tomo", "pt-BR": "Lidos até o volume",
        "de": "Gelesen bis Band", "it": "Letti fino al volume",
        "pl": "Przeczytane do tomu", "ja": "読了は何巻まで",
    },
    "Possédés jusqu'à…": {
        "en": "Owned up to…", "es": "En estantería hasta…",
        "es-419": "En estantería hasta…", "pt-BR": "Na estante até…",
        "de": "Im Regal bis…", "it": "Posseduti fino a…",
        "pl": "Na półce do…", "ja": "所有は…まで",
    },
    "Lus jusqu'à…": {
        "en": "Read up to…", "es": "Leídos hasta…", "es-419": "Leídos hasta…",
        "pt-BR": "Lidos até…", "de": "Gelesen bis…", "it": "Letti fino a…",
        "pl": "Przeczytane do…", "ja": "読了は…まで",
    },
    "Les tomes 1 à %lld seront marqués comme lus — et donc possédés.": {
        "en": "Volumes 1 to %lld will be marked read — and therefore owned.",
        "es": "Los tomos 1 a %lld se marcarán como leídos, y por tanto en tu estantería.",
        "es-419": "Los tomos 1 a %lld se marcarán como leídos, y por lo tanto en tu estantería.",
        "pt-BR": "Os volumes 1 a %lld serão marcados como lidos — e portanto na estante.",
        "de": "Die Bände 1 bis %lld gelten als gelesen — und damit als vorhanden.",
        "it": "I volumi da 1 a %lld saranno segnati come letti, e quindi posseduti.",
        "pl": "Tomy od 1 do %lld zostaną oznaczone jako przeczytane — a więc i posiadane.",
        "ja": "1巻から%lld巻までを読了（したがって所有）にします。",
    },
    "Les tomes 1 à %lld seront marqués comme possédés. Les suivants passent en manquants.": {
        "en": "Volumes 1 to %lld will be marked owned. The rest become missing.",
        "es": "Los tomos 1 a %lld pasarán a tu estantería. Los siguientes quedarán como faltantes.",
        "es-419": "Los tomos 1 a %lld pasarán a tu estantería. Los siguientes quedarán como faltantes.",
        "pt-BR": "Os volumes 1 a %lld irão para a estante. Os seguintes ficam como faltantes.",
        "de": "Die Bände 1 bis %lld stehen im Regal. Die folgenden gelten als fehlend.",
        "it": "I volumi da 1 a %lld saranno posseduti. I successivi diventano mancanti.",
        "pl": "Tomy od 1 do %lld trafią na półkę. Kolejne zostaną oznaczone jako brakujące.",
        "ja": "1巻から%lld巻までを所有にします。それ以降は未所持になります。",
    },
    "Aucun tome pour l'instant — ajoutez-les avec le bouton ci-dessus.": {
        "en": "No volumes yet — add them with the button above.",
        "es": "Aún no hay tomos: añádelos con el botón de arriba.",
        "es-419": "Todavía no hay tomos: agrégalos con el botón de arriba.",
        "pt-BR": "Ainda não há volumes — adicione com o botão acima.",
        "de": "Noch keine Bände — füge sie mit der Taste oben hinzu.",
        "it": "Ancora nessun volume: aggiungili con il pulsante qui sopra.",
        "pl": "Jeszcze żadnych tomów — dodaj je przyciskiem powyżej.",
        "ja": "まだ巻がありません。上のボタンから追加してください。",
    },
    "Prochain à acheter : tome %lld": {
        "en": "Next to buy: volume %lld", "es": "Siguiente por comprar: tomo %lld",
        "es-419": "Siguiente por comprar: tomo %lld", "pt-BR": "Próximo a comprar: volume %lld",
        "de": "Als Nächstes kaufen: Band %lld", "it": "Prossimo da comprare: volume %lld",
        "pl": "Następny do kupienia: tom %lld", "ja": "次に買うのは%lld巻",
    },
    "Date de sortie": {
        "en": "Release date", "es": "Fecha de publicación", "es-419": "Fecha de publicación",
        "pt-BR": "Data de lançamento", "de": "Erscheinungsdatum",
        "it": "Data di uscita", "pl": "Data premiery", "ja": "発売日",
    },
    "Prochaine sortie": {
        "en": "Next release", "es": "Próxima publicación", "es-419": "Próxima publicación",
        "pt-BR": "Próximo lançamento", "de": "Nächste Veröffentlichung",
        "it": "Prossima uscita", "pl": "Następna premiera", "ja": "次の刊行",
    },
    "Rappel de sortie": {
        "en": "Release reminder", "es": "Aviso de publicación",
        "es-419": "Aviso de publicación", "pt-BR": "Lembrete de lançamento",
        "de": "Erinnerung zur Veröffentlichung", "it": "Promemoria di uscita",
        "pl": "Przypomnienie o premierze", "ja": "発売のお知らせ",
    },
    "Non renseignée": {
        "en": "Not set", "es": "Sin definir", "es-419": "Sin definir",
        "pt-BR": "Não informada", "de": "Nicht angegeben", "it": "Non indicata",
        "pl": "Nie podano", "ja": "未設定",
    },

    # ------------------------------------------------------- fiche d'un livre
    "Informations": {
        "en": "Details", "es": "Información", "es-419": "Información",
        "pt-BR": "Informações", "de": "Informationen", "it": "Informazioni",
        "pl": "Informacje", "ja": "情報",
    },
    "Type": {"en": "Type", "es": "Tipo", "es-419": "Tipo", "pt-BR": "Tipo",
             "de": "Art", "it": "Tipo", "pl": "Rodzaj", "ja": "種類"},
    "ISBN": {"en": "ISBN", "es": "ISBN", "es-419": "ISBN", "pt-BR": "ISBN",
             "de": "ISBN", "it": "ISBN", "pl": "ISBN", "ja": "ISBN"},
    "Source": {"en": "Source", "es": "Fuente", "es-419": "Fuente", "pt-BR": "Fonte",
               "de": "Quelle", "it": "Fonte", "pl": "Źródło", "ja": "出典"},
    "Genres": {"en": "Genres", "es": "Géneros", "es-419": "Géneros",
               "pt-BR": "Gêneros", "de": "Genres", "it": "Generi",
               "pl": "Gatunki", "ja": "ジャンル"},
    "Parution": {"en": "Publication", "es": "Publicación", "es-419": "Publicación",
                 "pt-BR": "Publicação", "de": "Erscheinen", "it": "Pubblicazione",
                 "pl": "Wydanie", "ja": "刊行"},
    "Publication": {"en": "Published", "es": "Publicación", "es-419": "Publicación",
                    "pt-BR": "Publicação", "de": "Veröffentlicht",
                    "it": "Pubblicazione", "pl": "Wydanie", "ja": "出版"},
    "Langue": {"en": "Language", "es": "Idioma", "es-419": "Idioma",
               "pt-BR": "Idioma", "de": "Sprache", "it": "Lingua",
               "pl": "Język", "ja": "言語"},
    "Langue de l'édition": {
        "en": "Edition language", "es": "Idioma de la edición",
        "es-419": "Idioma de la edición", "pt-BR": "Idioma da edição",
        "de": "Sprache der Ausgabe", "it": "Lingua dell'edizione",
        "pl": "Język wydania", "ja": "版の言語",
    },
    "De l'éditeur": {
        "en": "From the publisher", "es": "De la editorial", "es-419": "De la editorial",
        "pt-BR": "Da editora", "de": "Vom Verlag", "it": "Dall'editore",
        "pl": "Od wydawcy", "ja": "出版社より",
    },
    "De l’éditeur": {
        "en": "From the publisher", "es": "De la editorial", "es-419": "De la editorial",
        "pt-BR": "Da editora", "de": "Vom Verlag", "it": "Dall'editore",
        "pl": "Od wydawcy", "ja": "出版社より",
    },
    "Plus de livres de : %@": {
        "en": "More books by %@", "es": "Más libros de %@", "es-419": "Más libros de %@",
        "pt-BR": "Mais livros de %@", "de": "Mehr Bücher von %@",
        "it": "Altri libri di %@", "pl": "Więcej książek: %@", "ja": "%@の他の本",
    },
    "Commencé le": {
        "en": "Started on", "es": "Empezado el", "es-419": "Empezado el",
        "pt-BR": "Começado em", "de": "Begonnen am", "it": "Iniziato il",
        "pl": "Rozpoczęte", "ja": "読み始め",
    },
    "Terminé le": {
        "en": "Finished on", "es": "Terminado el", "es-419": "Terminado el",
        "pt-BR": "Terminado em", "de": "Beendet am", "it": "Finito il",
        "pl": "Ukończone", "ja": "読み終わり",
    },
    "Marquer comme lu": {
        "en": "Mark as read", "es": "Marcar como leído", "es-419": "Marcar como leído",
        "pt-BR": "Marcar como lido", "de": "Als gelesen markieren",
        "it": "Segna come letto", "pl": "Oznacz jako przeczytane", "ja": "読了にする",
    },
    "Actualiser les informations": {
        "en": "Refresh information", "es": "Actualizar la información",
        "es-419": "Actualizar la información", "pt-BR": "Atualizar as informações",
        "de": "Informationen aktualisieren", "it": "Aggiorna le informazioni",
        "pl": "Odśwież informacje", "ja": "情報を更新",
    },
    "Retirer la série": {
        "en": "Remove series", "es": "Quitar la serie", "es-419": "Quitar la serie",
        "pt-BR": "Remover a série", "de": "Reihe entfernen",
        "it": "Rimuovi la serie", "pl": "Usuń serię", "ja": "シリーズを取り除く",
    },
    "Retirer de la bibliothèque": {
        "en": "Remove from library", "es": "Quitar de la biblioteca",
        "es-419": "Quitar de la biblioteca", "pt-BR": "Remover da biblioteca",
        "de": "Aus der Bibliothek entfernen", "it": "Rimuovi dalla libreria",
        "pl": "Usuń z biblioteki", "ja": "ライブラリから取り除く",
    },
    "Retirer de ma bibliothèque": {
        "en": "Remove from my library", "es": "Quitar de mi biblioteca",
        "es-419": "Quitar de mi biblioteca", "pt-BR": "Remover da minha biblioteca",
        "de": "Aus meiner Bibliothek entfernen", "it": "Rimuovi dalla mia libreria",
        "pl": "Usuń z mojej biblioteki", "ja": "自分のライブラリから取り除く",
    },
    "Retirer « %@ » de la bibliothèque ?": {
        "en": "Remove “%@” from your library?",
        "es": "¿Quitar «%@» de la biblioteca?",
        "es-419": "¿Quitar «%@» de la biblioteca?",
        "pt-BR": "Remover “%@” da biblioteca?",
        "de": "„%@“ aus der Bibliothek entfernen?",
        "it": "Rimuovere «%@» dalla libreria?",
        "pl": "Usunąć „%@” z biblioteki?",
        "ja": "「%@」をライブラリから取り除きますか？",
    },
    "Retirer « %@ » et tous ses tomes ?": {
        "en": "Remove “%@” and all its volumes?",
        "es": "¿Quitar «%@» y todos sus tomos?",
        "es-419": "¿Quitar «%@» y todos sus tomos?",
        "pt-BR": "Remover “%@” e todos os seus volumes?",
        "de": "„%@“ mit allen Bänden entfernen?",
        "it": "Rimuovere «%@» e tutti i suoi volumi?",
        "pl": "Usunąć „%@” wraz ze wszystkimi tomami?",
        "ja": "「%@」と全巻を取り除きますか？",
    },
    "Ajouter à À suivre": {
        "en": "Add to Watching", "es": "Añadir a Seguimiento",
        "es-419": "Agregar a Seguimiento", "pt-BR": "Adicionar a Acompanhando",
        "de": "Zu „Im Blick“ hinzufügen", "it": "Aggiungi a Da seguire",
        "pl": "Dodaj do Obserwowanych", "ja": "「気になる」に追加",
    },
    "Retirer d'À suivre": {
        "en": "Remove from Watching", "es": "Quitar de Seguimiento",
        "es-419": "Quitar de Seguimiento", "pt-BR": "Remover de Acompanhando",
        "de": "Aus „Im Blick“ entfernen", "it": "Togli da Da seguire",
        "pl": "Usuń z Obserwowanych", "ja": "「気になる」から外す",
    },
    "Prêter": {"en": "Lend", "es": "Prestar", "es-419": "Prestar", "pt-BR": "Emprestar",
               "de": "Verleihen", "it": "Presta", "pl": "Wypożycz", "ja": "貸す"},
    "Prêter…": {"en": "Lend…", "es": "Prestar…", "es-419": "Prestar…",
                "pt-BR": "Emprestar…", "de": "Verleihen…", "it": "Presta…",
                "pl": "Wypożycz…", "ja": "貸す…"},
    "Prêter ce livre": {
        "en": "Lend this book", "es": "Prestar este libro", "es-419": "Prestar este libro",
        "pt-BR": "Emprestar este livro", "de": "Dieses Buch verleihen",
        "it": "Presta questo libro", "pl": "Wypożycz tę książkę", "ja": "この本を貸す",
    },
    "Prêté à": {"en": "Lent to", "es": "Prestado a", "es-419": "Prestado a",
                "pt-BR": "Emprestado a", "de": "Verliehen an", "it": "Prestato a",
                "pl": "Wypożyczone", "ja": "貸出先"},
    "À qui ?": {"en": "To whom?", "es": "¿A quién?", "es-419": "¿A quién?",
                "pt-BR": "Para quem?", "de": "An wen?", "it": "A chi?",
                "pl": "Komu?", "ja": "だれに？"},
    "Rendu": {"en": "Returned", "es": "Devuelto", "es-419": "Devuelto",
              "pt-BR": "Devolvido", "de": "Zurück", "it": "Restituito",
              "pl": "Zwrócone", "ja": "返却済み"},
    "Ajouter cette série": {
        "en": "Add this series", "es": "Añadir esta serie", "es-419": "Agregar esta serie",
        "pt-BR": "Adicionar esta série", "de": "Diese Reihe hinzufügen",
        "it": "Aggiungi questa serie", "pl": "Dodaj tę serię", "ja": "このシリーズを追加",
    },
    "Ajouter la série": {
        "en": "Add the series", "es": "Añadir la serie", "es-419": "Agregar la serie",
        "pt-BR": "Adicionar a série", "de": "Reihe hinzufügen",
        "it": "Aggiungi la serie", "pl": "Dodaj serię", "ja": "シリーズを追加",
    },
    "Ajouter à la bibliothèque": {
        "en": "Add to library", "es": "Añadir a la biblioteca",
        "es-419": "Agregar a la biblioteca", "pt-BR": "Adicionar à biblioteca",
        "de": "Zur Bibliothek hinzufügen", "it": "Aggiungi alla libreria",
        "pl": "Dodaj do biblioteki", "ja": "ライブラリに追加",
    },
    "Ajouter à ma bibliothèque": {
        "en": "Add to my library", "es": "Añadir a mi biblioteca",
        "es-419": "Agregar a mi biblioteca", "pt-BR": "Adicionar à minha biblioteca",
        "de": "Zu meiner Bibliothek hinzufügen", "it": "Aggiungi alla mia libreria",
        "pl": "Dodaj do mojej biblioteki", "ja": "自分のライブラリに追加",
    },
    "Déjà dans la bibliothèque": {
        "en": "Already in your library", "es": "Ya está en la biblioteca",
        "es-419": "Ya está en la biblioteca", "pt-BR": "Já está na biblioteca",
        "de": "Schon in der Bibliothek", "it": "Già nella libreria",
        "pl": "Już w bibliotece", "ja": "すでにライブラリにあります",
    },
    "Déjà dans votre bibliothèque": {
        "en": "Already in your library", "es": "Ya está en tu biblioteca",
        "es-419": "Ya está en tu biblioteca", "pt-BR": "Já está na sua biblioteca",
        "de": "Schon in deiner Bibliothek", "it": "Già nella tua libreria",
        "pl": "Już w Twojej bibliotece", "ja": "すでにライブラリにあります",
    },
    "Je le possède": {
        "en": "I own it", "es": "Lo tengo", "es-419": "Lo tengo",
        "pt-BR": "Eu tenho", "de": "Habe ich", "it": "Ce l'ho",
        "pl": "Mam go", "ja": "持っている",
    },
    "Je le possède · à lire": {
        "en": "I own it · to read", "es": "Lo tengo · por leer",
        "es-419": "Lo tengo · por leer", "pt-BR": "Eu tenho · para ler",
        "de": "Habe ich · ungelesen", "it": "Ce l'ho · da leggere",
        "pl": "Mam go · do przeczytania", "ja": "持っている・未読",
    },
    "Je suis en train de le lire": {
        "en": "I'm reading it", "es": "Lo estoy leyendo", "es-419": "Lo estoy leyendo",
        "pt-BR": "Estou lendo", "de": "Ich lese es gerade", "it": "Lo sto leggendo",
        "pl": "Właśnie to czytam", "ja": "いま読んでいる",
    },
    "Je l'ai lu": {
        "en": "I've read it", "es": "Ya lo he leído", "es-419": "Ya lo leí",
        "pt-BR": "Já li", "de": "Habe ich gelesen", "it": "L'ho letto",
        "pl": "Przeczytałem", "ja": "読み終えた",
    },
}

if __name__ == "__main__":
    ecrire(T)
