# -*- coding: utf-8 -*-
"""Le mot de passe oublié, du code reçu au nouveau mot de passe."""
from catalogue import ecrire

T = {
    "Réinitialiser le mot de passe": {
        "en": "Reset your password", "es": "Restablecer la contraseña",
        "es-419": "Restablecer la contraseña", "pt-BR": "Redefinir a senha",
        "de": "Passwort zurücksetzen", "it": "Reimposta la password",
        "nl": "Wachtwoord opnieuw instellen", "pl": "Zresetuj hasło",
        "sv": "Återställ lösenordet", "tr": "Parolanı sıfırla",
        "ru": "Сбросить пароль", "ja": "パスワードを再設定",
        "ko": "비밀번호 재설정", "zh-Hans": "重设密码",
    },
    "Un code part vers votre adresse, à recopier ici même.": {
        "en": "A code is on its way to your inbox — type it right here.",
        "es": "Te enviamos un código a tu correo; escríbelo aquí mismo.",
        "es-419": "Te enviamos un código a tu correo; escríbelo aquí mismo.",
        "pt-BR": "Um código vai para o seu e-mail; digite-o aqui mesmo.",
        "de": "Ein Code geht an deine Adresse — trag ihn gleich hier ein.",
        "it": "Un codice parte verso la tua casella: riscrivilo qui.",
        "nl": "Er gaat een code naar je e-mail — typ hem hier over.",
        "pl": "Kod trafi na Twój adres — przepisz go tutaj.",
        "sv": "En kod skickas till din adress — skriv in den här.",
        "tr": "Adresine bir kod gidiyor, buraya yaz.",
        "ru": "Код уйдёт на вашу почту — впишите его здесь.",
        "ja": "メールにコードを送ります。ここに入力してください。",
        "ko": "메일로 코드를 보내요. 여기에 입력하세요.",
        "zh-Hans": "验证码会发到你的邮箱，就在这里填。",
    },
    "Recopiez le code reçu, puis choisissez votre nouveau mot de passe.": {
        "en": "Type the code you received, then pick a new password.",
        "es": "Escribe el código recibido y elige una contraseña nueva.",
        "es-419": "Escribe el código recibido y elige una contraseña nueva.",
        "pt-BR": "Digite o código recebido e escolha uma nova senha.",
        "de": "Gib den erhaltenen Code ein und wähle ein neues Passwort.",
        "it": "Riscrivi il codice ricevuto, poi scegli la nuova password.",
        "nl": "Typ de ontvangen code over en kies een nieuw wachtwoord.",
        "pl": "Przepisz otrzymany kod i wybierz nowe hasło.",
        "sv": "Skriv in koden du fick och välj ett nytt lösenord.",
        "tr": "Aldığın kodu yaz, sonra yeni parolanı seç.",
        "ru": "Впишите полученный код и выберите новый пароль.",
        "ja": "届いたコードを入力し、新しいパスワードを決めてください。",
        "ko": "받은 코드를 입력하고 새 비밀번호를 정하세요.",
        "zh-Hans": "填入收到的验证码，然后设置新密码。",
    },
    "Code reçu par courrier": {
        "en": "Code from the email", "es": "Código recibido por correo",
        "es-419": "Código recibido por correo", "pt-BR": "Código recebido por e-mail",
        "de": "Code aus der E-Mail", "it": "Codice ricevuto via e-mail",
        "nl": "Code uit de e-mail", "pl": "Kod z wiadomości",
        "sv": "Koden från mejlet", "tr": "E-postadaki kod",
        "ru": "Код из письма", "ja": "メールのコード",
        "ko": "메일로 받은 코드", "zh-Hans": "邮件里的验证码",
    },
    "Nouveau mot de passe (6 caractères min.)": {
        "en": "New password (6 characters min.)",
        "es": "Nueva contraseña (mín. 6 caracteres)",
        "es-419": "Nueva contraseña (mín. 6 caracteres)",
        "pt-BR": "Nova senha (mín. 6 caracteres)",
        "de": "Neues Passwort (mind. 6 Zeichen)",
        "it": "Nuova password (min. 6 caratteri)",
        "nl": "Nieuw wachtwoord (min. 6 tekens)",
        "pl": "Nowe hasło (min. 6 znaków)",
        "sv": "Nytt lösenord (minst 6 tecken)",
        "tr": "Yeni parola (en az 6 karakter)",
        "ru": "Новый пароль (от 6 символов)",
        "ja": "新しいパスワード（6文字以上）",
        "ko": "새 비밀번호 (6자 이상)",
        "zh-Hans": "新密码（至少 6 位）",
    },
    "Envoyer le code": {
        "en": "Send the code", "es": "Enviar el código",
        "es-419": "Enviar el código", "pt-BR": "Enviar o código",
        "de": "Code senden", "it": "Invia il codice",
        "nl": "Stuur de code", "pl": "Wyślij kod", "sv": "Skicka koden",
        "tr": "Kodu gönder", "ru": "Отправить код", "ja": "コードを送る",
        "ko": "코드 보내기", "zh-Hans": "发送验证码",
    },
    "Renvoyer le code": {
        "en": "Send it again", "es": "Reenviar el código",
        "es-419": "Reenviar el código", "pt-BR": "Reenviar o código",
        "de": "Code erneut senden", "it": "Invia di nuovo il codice",
        "nl": "Code opnieuw sturen", "pl": "Wyślij kod ponownie",
        "sv": "Skicka koden igen", "tr": "Kodu yeniden gönder",
        "ru": "Отправить код ещё раз", "ja": "コードを再送する",
        "ko": "코드 다시 보내기", "zh-Hans": "重新发送验证码",
    },
    "Valider et me connecter": {
        "en": "Confirm and sign in", "es": "Confirmar y entrar",
        "es-419": "Confirmar y entrar", "pt-BR": "Confirmar e entrar",
        "de": "Bestätigen und anmelden", "it": "Conferma ed entra",
        "nl": "Bevestigen en inloggen", "pl": "Zatwierdź i zaloguj",
        "sv": "Bekräfta och logga in", "tr": "Onayla ve giriş yap",
        "ru": "Подтвердить и войти", "ja": "決定してサインイン",
        "ko": "확인하고 로그인", "zh-Hans": "确认并登录",
    },
}

if __name__ == "__main__":
    ecrire(T)
