# -*- coding: utf-8 -*-
"""Traductions — vague 6 : six langues de plus, sur les textes les plus vus.

nl (néerlandais), ko (coréen), zh-Hans (chinois simplifié), tr (turc),
ru (russe), sv (suédois).
"""
from catalogue import ecrire

T = {
    # -------------------------------------------------------------- onglets
    "Aujourd'hui": {"nl": "Vandaag", "ko": "오늘", "zh-Hans": "今天",
                    "tr": "Bugün", "ru": "Сегодня", "sv": "I dag"},
    "Bibliothèque": {"nl": "Bibliotheek", "ko": "서재", "zh-Hans": "书库",
                     "tr": "Kitaplık", "ru": "Библиотека", "sv": "Bibliotek"},
    "Découverte": {"nl": "Ontdekken", "ko": "발견", "zh-Hans": "发现",
                   "tr": "Keşfet", "ru": "Обзор", "sv": "Upptäck"},
    "Stats": {"nl": "Cijfers", "ko": "통계", "zh-Hans": "统计",
              "tr": "İstatistik", "ru": "Статистика", "sv": "Statistik"},
    "Statistiques": {"nl": "Statistieken", "ko": "통계", "zh-Hans": "统计",
                     "tr": "İstatistikler", "ru": "Статистика", "sv": "Statistik"},
    "Recherche": {"nl": "Zoeken", "ko": "검색", "zh-Hans": "搜索",
                  "tr": "Ara", "ru": "Поиск", "sv": "Sök"},
    "Réglages": {"nl": "Instellingen", "ko": "설정", "zh-Hans": "设置",
                 "tr": "Ayarlar", "ru": "Настройки", "sv": "Inställningar"},
    "Collections": {"nl": "Collecties", "ko": "컬렉션", "zh-Hans": "收藏集",
                    "tr": "Koleksiyonlar", "ru": "Коллекции", "sv": "Samlingar"},

    # -------------------------------------------------------------- statuts
    "À lire": {"nl": "Te lezen", "ko": "읽을 책", "zh-Hans": "待读",
               "tr": "Okunacak", "ru": "К прочтению", "sv": "Att läsa"},
    "En cours": {"nl": "Bezig", "ko": "읽는 중", "zh-Hans": "在读",
                 "tr": "Okunuyor", "ru": "Читаю", "sv": "Pågår"},
    "Lu": {"nl": "Gelezen", "ko": "읽음", "zh-Hans": "已读",
           "tr": "Okundu", "ru": "Прочитано", "sv": "Läst"},
    "Abandonné": {"nl": "Afgebroken", "ko": "중단", "zh-Hans": "已弃读",
                  "tr": "Bırakıldı", "ru": "Заброшено", "sv": "Avbruten"},
    "À acheter": {"nl": "Te kopen", "ko": "구매 예정", "zh-Hans": "待购",
                  "tr": "Alınacak", "ru": "Купить", "sv": "Att köpa"},
    "lu": {"nl": "gelezen", "ko": "읽음", "zh-Hans": "已读",
           "tr": "okundu", "ru": "прочитано", "sv": "läst"},
    "possédé": {"nl": "in de kast", "ko": "소장 중", "zh-Hans": "已拥有",
                "tr": "rafta", "ru": "в наличии", "sv": "i hyllan"},
    "manquant": {"nl": "ontbreekt", "ko": "미소장", "zh-Hans": "缺少",
                 "tr": "eksik", "ru": "не хватает", "sv": "saknas"},
    "Tous": {"nl": "Alle", "ko": "전체", "zh-Hans": "全部",
             "tr": "Tümü", "ru": "Все", "sv": "Alla"},
    "Lus": {"nl": "Gelezen", "ko": "읽은 책", "zh-Hans": "已读",
            "tr": "Okunanlar", "ru": "Прочитанные", "sv": "Lästa"},
    "Séries": {"nl": "Reeksen", "ko": "시리즈", "zh-Hans": "系列",
               "tr": "Seriler", "ru": "Серии", "sv": "Serier"},
    "Série": {"nl": "Reeks", "ko": "시리즈", "zh-Hans": "系列",
              "tr": "Seri", "ru": "Серия", "sv": "Serie"},

    # ---------------------------------------------------- types et formats
    "Livre": {"nl": "Boek", "ko": "책", "zh-Hans": "图书",
              "tr": "Kitap", "ru": "Книга", "sv": "Bok"},
    "Livres": {"nl": "Boeken", "ko": "책", "zh-Hans": "图书",
               "tr": "Kitaplar", "ru": "Книги", "sv": "Böcker"},
    "Manga": {"nl": "Manga", "ko": "만화", "zh-Hans": "漫画",
              "tr": "Manga", "ru": "Манга", "sv": "Manga"},
    "Mangas": {"nl": "Manga", "ko": "만화", "zh-Hans": "漫画",
               "tr": "Mangalar", "ru": "Манга", "sv": "Manga"},
    "BD": {"nl": "Strip", "ko": "코믹스", "zh-Hans": "漫画书",
           "tr": "Çizgi roman", "ru": "Комикс", "sv": "Serier"},
    "Poche": {"nl": "Pocket", "ko": "문고본", "zh-Hans": "口袋本",
              "tr": "Cep boy", "ru": "Карманное", "sv": "Pocket"},
    "Grand format": {"nl": "Groot formaat", "ko": "단행본", "zh-Hans": "大开本",
                     "tr": "Büyük boy", "ru": "Большой формат", "sv": "Storformat"},
    "Relié": {"nl": "Gebonden", "ko": "양장본", "zh-Hans": "精装",
              "tr": "Ciltli", "ru": "Твёрдый переплёт", "sv": "Inbunden"},
    "Numérique": {"nl": "Digitaal", "ko": "전자책", "zh-Hans": "电子版",
                  "tr": "Dijital", "ru": "Электронная", "sv": "Digital"},
    "Audio": {"nl": "Luisterboek", "ko": "오디오북", "zh-Hans": "有声书",
              "tr": "Sesli kitap", "ru": "Аудиокнига", "sv": "Ljudbok"},
    "En cours de parution": {"nl": "Loopt nog", "ko": "연재 중", "zh-Hans": "连载中",
                             "tr": "Devam ediyor", "ru": "Выходит", "sv": "Pågående"},
    "Terminée": {"nl": "Afgerond", "ko": "완결", "zh-Hans": "已完结",
                 "tr": "Tamamlandı", "ru": "Завершена", "sv": "Avslutad"},
    "Parution inconnue": {"nl": "Status onbekend", "ko": "간행 상태 미상",
                          "zh-Hans": "刊行状态未知", "tr": "Durum bilinmiyor",
                          "ru": "Статус неизвестен", "sv": "Okänd status"},

    # ------------------------------------------------------------- actions
    "Ajouter": {"nl": "Voeg toe", "ko": "추가", "zh-Hans": "添加",
                "tr": "Ekle", "ru": "Добавить", "sv": "Lägg till"},
    "Annuler": {"nl": "Annuleer", "ko": "취소", "zh-Hans": "取消",
                "tr": "Vazgeç", "ru": "Отменить", "sv": "Avbryt"},
    "OK": {"nl": "OK", "ko": "확인", "zh-Hans": "好", "tr": "Tamam",
           "ru": "OK", "sv": "OK"},
    "Enregistrer": {"nl": "Bewaar", "ko": "저장", "zh-Hans": "存储",
                    "tr": "Kaydet", "ru": "Сохранить", "sv": "Spara"},
    "Modifier": {"nl": "Wijzig", "ko": "편집", "zh-Hans": "编辑",
                 "tr": "Düzenle", "ru": "Изменить", "sv": "Redigera"},
    "Supprimer": {"nl": "Verwijder", "ko": "삭제", "zh-Hans": "删除",
                  "tr": "Sil", "ru": "Удалить", "sv": "Radera"},
    "Retirer": {"nl": "Haal weg", "ko": "제거", "zh-Hans": "移除",
                "tr": "Kaldır", "ru": "Убрать", "sv": "Ta bort"},
    "Continuer": {"nl": "Ga door", "ko": "계속", "zh-Hans": "继续",
                  "tr": "Devam", "ru": "Продолжить", "sv": "Fortsätt"},
    "Ignorer": {"nl": "Sla over", "ko": "건너뛰기", "zh-Hans": "跳过",
                "tr": "Atla", "ru": "Пропустить", "sv": "Hoppa över"},
    "Appliquer": {"nl": "Pas toe", "ko": "적용", "zh-Hans": "应用",
                  "tr": "Uygula", "ru": "Применить", "sv": "Använd"},
    "Créer": {"nl": "Maak aan", "ko": "만들기", "zh-Hans": "创建",
              "tr": "Oluştur", "ru": "Создать", "sv": "Skapa"},
    "Chercher": {"nl": "Zoek", "ko": "검색", "zh-Hans": "搜索",
                 "tr": "Ara", "ru": "Искать", "sv": "Sök"},
    "Tout": {"nl": "Alles", "ko": "전체", "zh-Hans": "全部",
             "tr": "Hepsi", "ru": "Всё", "sv": "Allt"},
    "Tout voir": {"nl": "Toon alles", "ko": "모두 보기", "zh-Hans": "查看全部",
                  "tr": "Tümünü gör", "ru": "Показать всё", "sv": "Visa alla"},
    "Plus": {"nl": "Meer", "ko": "더 보기", "zh-Hans": "更多",
             "tr": "Daha fazla", "ru": "Ещё", "sv": "Mer"},
    "Réduire": {"nl": "Minder", "ko": "접기", "zh-Hans": "收起",
                "tr": "Daha az", "ru": "Свернуть", "sv": "Mindre"},
    "Lire la suite": {"nl": "Lees verder", "ko": "더 읽기", "zh-Hans": "继续阅读",
                      "tr": "Devamını oku", "ru": "Читать дальше", "sv": "Läs mer"},
    "Trier par": {"nl": "Sorteer op", "ko": "정렬 기준", "zh-Hans": "排序方式",
                  "tr": "Sırala", "ru": "Сортировка", "sv": "Sortera efter"},
    "Titre": {"nl": "Titel", "ko": "제목", "zh-Hans": "标题",
              "tr": "Başlık", "ru": "Название", "sv": "Titel"},
    "Statut": {"nl": "Status", "ko": "상태", "zh-Hans": "状态",
               "tr": "Durum", "ru": "Статус", "sv": "Status"},
    "Note": {"nl": "Beoordeling", "ko": "평점", "zh-Hans": "评分",
             "tr": "Puan", "ru": "Оценка", "sv": "Betyg"},
    "Noter": {"nl": "Beoordeel", "ko": "평가하기", "zh-Hans": "评分",
              "tr": "Puanla", "ru": "Оценить", "sv": "Betygsätt"},
    "Pages": {"nl": "Pagina's", "ko": "페이지", "zh-Hans": "页数",
              "tr": "Sayfa", "ru": "Страницы", "sv": "Sidor"},
    "Chapitres": {"nl": "Hoofdstukken", "ko": "화", "zh-Hans": "话数",
                  "tr": "Bölümler", "ru": "Главы", "sv": "Kapitel"},
    "Minutes": {"nl": "Minuten", "ko": "분", "zh-Hans": "分钟",
                "tr": "Dakika", "ru": "Минуты", "sv": "Minuter"},
    "min": {"nl": "min", "ko": "분", "zh-Hans": "分钟",
            "tr": "dk", "ru": "мин", "sv": "min"},
    "Jour": {"nl": "Dag", "ko": "일", "zh-Hans": "日",
             "tr": "Gün", "ru": "День", "sv": "Dag"},
    "Semaine": {"nl": "Week", "ko": "주", "zh-Hans": "周",
                "tr": "Hafta", "ru": "Неделя", "sv": "Vecka"},
    "Mois": {"nl": "Maand", "ko": "월", "zh-Hans": "月",
             "tr": "Ay", "ru": "Месяц", "sv": "Månad"},
    "Année": {"nl": "Jaar", "ko": "연", "zh-Hans": "年",
              "tr": "Yıl", "ru": "Год", "sv": "År"},
    "Période": {"nl": "Periode", "ko": "기간", "zh-Hans": "时间段",
                "tr": "Dönem", "ru": "Период", "sv": "Period"},
    "Portée": {"nl": "Bereik", "ko": "범위", "zh-Hans": "范围",
               "tr": "Kapsam", "ru": "Область", "sv": "Omfång"},
    "Honya": {"nl": "Honya", "ko": "Honya", "zh-Hans": "Honya",
              "tr": "Honya", "ru": "Honya", "sv": "Honya"},
    "Application": {"nl": "App", "ko": "앱", "zh-Hans": "应用",
                    "tr": "Uygulama", "ru": "Программа", "sv": "App"},
    "Version": {"nl": "Versie", "ko": "버전", "zh-Hans": "版本",
                "tr": "Sürüm", "ru": "Версия", "sv": "Version"},

    # ----------------------------------------------------------- tomes clés
    "Tome %lld": {"nl": "Deel %lld", "ko": "%lld권", "zh-Hans": "第%lld卷",
                  "tr": "%lld. cilt", "ru": "Том %lld", "sv": "Del %lld"},
    "Tome %lld lu": {"nl": "Deel %lld gelezen", "ko": "%lld권 읽음",
                     "zh-Hans": "第%lld卷已读", "tr": "%lld. cilt okundu",
                     "ru": "Том %lld прочитан", "sv": "Del %lld läst"},
    "%lld tomes": {"nl": "%lld delen", "ko": "%lld권", "zh-Hans": "%lld卷",
                   "tr": "%lld cilt", "ru": "%lld т.", "sv": "%lld delar"},
    "Tomes": {"nl": "Delen", "ko": "권", "zh-Hans": "卷",
              "tr": "Ciltler", "ru": "Тома", "sv": "Delar"},
    "Tomes parus": {"nl": "Verschenen delen", "ko": "기간행 권수",
                    "zh-Hans": "已出卷数", "tr": "Çıkan ciltler",
                    "ru": "Вышло томов", "sv": "Utgivna delar"},
    "Possédés": {"nl": "In de kast", "ko": "소장", "zh-Hans": "已拥有",
                 "tr": "Rafta", "ru": "В наличии", "sv": "I hyllan"},
    "%lld/%lld": {"nl": "%lld/%lld", "ko": "%lld/%lld", "zh-Hans": "%lld/%lld",
                  "tr": "%lld/%lld", "ru": "%lld/%lld", "sv": "%lld/%lld"},
    "%lld possédés · %lld lus": {
        "nl": "%lld in de kast · %lld gelezen", "ko": "소장 %lld · 읽음 %lld",
        "zh-Hans": "已拥有 %lld · 已读 %lld", "tr": "%lld rafta · %lld okundu",
        "ru": "%lld в наличии · %lld прочитано", "sv": "%lld i hyllan · %lld lästa",
    },
    "Prochaine sortie": {"nl": "Volgende uitgave", "ko": "다음 발매",
                         "zh-Hans": "下次发行", "tr": "Sonraki çıkış",
                         "ru": "Следующий выход", "sv": "Nästa utgivning"},
    "Date de sortie": {"nl": "Verschijningsdatum", "ko": "발매일",
                       "zh-Hans": "发行日期", "tr": "Çıkış tarihi",
                       "ru": "Дата выхода", "sv": "Utgivningsdatum"},

    # ---------------------------------------------------------- lecture
    "Lecture": {"nl": "Lezen", "ko": "독서", "zh-Hans": "阅读",
                "tr": "Okuma", "ru": "Чтение", "sv": "Läsning"},
    "Session de lecture": {"nl": "Leessessie", "ko": "독서 세션",
                           "zh-Hans": "阅读时段", "tr": "Okuma oturumu",
                           "ru": "Сеанс чтения", "sv": "Läspass"},
    "Continuer la lecture": {"nl": "Verder lezen", "ko": "이어 읽기",
                             "zh-Hans": "继续阅读", "tr": "Okumaya devam",
                             "ru": "Продолжить чтение", "sv": "Fortsätt läsa"},
    "Reprendre": {"nl": "Hervat", "ko": "다시 시작", "zh-Hans": "继续",
                  "tr": "Sürdür", "ru": "Продолжить", "sv": "Återuppta"},
    "Relire": {"nl": "Herlees", "ko": "다시 읽기", "zh-Hans": "重读",
               "tr": "Yeniden oku", "ru": "Перечитать", "sv": "Läs om"},
    "Pause": {"nl": "Pauze", "ko": "일시정지", "zh-Hans": "暂停",
              "tr": "Duraklat", "ru": "Пауза", "sv": "Paus"},
    "Terminer la session": {"nl": "Beëindig de sessie", "ko": "세션 마치기",
                            "zh-Hans": "结束本次阅读", "tr": "Oturumu bitir",
                            "ru": "Завершить сеанс", "sv": "Avsluta passet"},
    "Terminé": {"nl": "Klaar", "ko": "완료", "zh-Hans": "完成",
                "tr": "Bitti", "ru": "Готово", "sv": "Klart"},
    "Marquer comme lu": {"nl": "Markeer als gelezen", "ko": "읽음으로 표시",
                         "zh-Hans": "标为已读", "tr": "Okundu olarak işaretle",
                         "ru": "Отметить прочитанным", "sv": "Markera som läst"},
    "Temps de lecture": {"nl": "Leestijd", "ko": "독서 시간", "zh-Hans": "阅读时长",
                         "tr": "Okuma süresi", "ru": "Время чтения", "sv": "Lästid"},
    "Temps de lecture aujourd'hui": {
        "nl": "Leestijd vandaag", "ko": "오늘의 독서 시간", "zh-Hans": "今天的阅读时长",
        "tr": "Bugünkü okuma süresi", "ru": "Время чтения сегодня",
        "sv": "Lästid i dag",
    },
    "%lld min": {"nl": "%lld min", "ko": "%lld분", "zh-Hans": "%lld分钟",
                 "tr": "%lld dk", "ru": "%lld мин", "sv": "%lld min"},
    "%lld h": {"nl": "%lld u", "ko": "%lld시간", "zh-Hans": "%lld小时",
               "tr": "%lld sa", "ru": "%lld ч", "sv": "%lld tim"},
    "%lld h %@": {"nl": "%lld u %@", "ko": "%lld시간 %@분", "zh-Hans": "%lld小时%@分",
                  "tr": "%lld sa %@", "ru": "%lld ч %@", "sv": "%lld tim %@"},
    "p. %lld": {"nl": "p. %lld", "ko": "%lld쪽", "zh-Hans": "第%lld页",
                "tr": "s. %lld", "ru": "с. %lld", "sv": "s. %lld"},
    "%lld pages": {"nl": "%lld pagina's", "ko": "%lld쪽", "zh-Hans": "%lld页",
                   "tr": "%lld sayfa", "ru": "%lld стр.", "sv": "%lld sidor"},

    # --------------------------------------------------------- bibliothèque
    "Votre bibliothèque": {"nl": "Jouw bibliotheek", "ko": "나의 서재",
                           "zh-Hans": "你的书库", "tr": "Kitaplığın",
                           "ru": "Ваша библиотека", "sv": "Ditt bibliotek"},
    "Votre bibliothèque est vide": {
        "nl": "Je bibliotheek is leeg", "ko": "서재가 비어 있습니다",
        "zh-Hans": "书库是空的", "tr": "Kitaplığın boş",
        "ru": "Ваша библиотека пуста", "sv": "Ditt bibliotek är tomt",
    },
    "Rien ici pour l'instant": {
        "nl": "Hier is nog niets", "ko": "아직 아무것도 없습니다",
        "zh-Hans": "这里还什么都没有", "tr": "Burada henüz bir şey yok",
        "ru": "Здесь пока пусто", "sv": "Inget här ännu",
    },
    "Mes étagères": {"nl": "Mijn planken", "ko": "나의 책장", "zh-Hans": "我的书架",
                     "tr": "Raflarım", "ru": "Мои полки", "sv": "Mina hyllor"},
    "Par statut": {"nl": "Op status", "ko": "상태별", "zh-Hans": "按状态",
                   "tr": "Duruma göre", "ru": "По статусу", "sv": "Efter status"},
    "Automatiques": {"nl": "Automatisch", "ko": "자동", "zh-Hans": "自动",
                     "tr": "Otomatik", "ru": "Автоматические", "sv": "Automatiska"},
    "Ranger dans une étagère": {
        "nl": "Op een plank zetten", "ko": "책장에 넣기", "zh-Hans": "放入书架",
        "tr": "Bir rafa koy", "ru": "Поставить на полку", "sv": "Ställ i en hylla",
    },
    "Nouvelle étagère": {"nl": "Nieuwe plank", "ko": "새 책장", "zh-Hans": "新建书架",
                         "tr": "Yeni raf", "ru": "Новая полка", "sv": "Ny hylla"},
    "Étagère vide": {"nl": "Lege plank", "ko": "빈 책장", "zh-Hans": "空书架",
                     "tr": "Boş raf", "ru": "Пустая полка", "sv": "Tom hylla"},

    # ------------------------------------------------------------ découverte
    "Nouveautés et tendances": {
        "nl": "Nieuw en populair", "ko": "신간과 인기작", "zh-Hans": "新书与热门",
        "tr": "Yeni ve popüler", "ru": "Новинки и тренды", "sv": "Nytt och populärt",
    },
    "Mangas populaires": {"nl": "Populaire manga", "ko": "인기 만화",
                          "zh-Hans": "热门漫画", "tr": "Popüler manga",
                          "ru": "Популярная манга", "sv": "Populär manga"},
    "Romance": {"nl": "Romantiek", "ko": "로맨스", "zh-Hans": "言情",
                "tr": "Romantik", "ru": "Романтика", "sv": "Romance"},
    "Polar": {"nl": "Misdaad", "ko": "추리", "zh-Hans": "推理",
              "tr": "Polisiye", "ru": "Детектив", "sv": "Deckare"},
    "Polars & thrillers": {"nl": "Misdaad en thrillers", "ko": "추리·스릴러",
                           "zh-Hans": "推理与惊悚", "tr": "Polisiye ve gerilim",
                           "ru": "Детективы и триллеры", "sv": "Deckare och thrillers"},
    "SF et fantasy": {"nl": "SF en fantasy", "ko": "SF·판타지",
                      "zh-Hans": "科幻与奇幻", "tr": "Bilimkurgu ve fantastik",
                      "ru": "Фантастика и фэнтези", "sv": "Sci-fi och fantasy"},
    "SF & Fantasy": {"nl": "SF en fantasy", "ko": "SF·판타지",
                     "zh-Hans": "科幻与奇幻", "tr": "Bilimkurgu ve fantastik",
                     "ru": "Фантастика и фэнтези", "sv": "Sci-fi och fantasy"},
    "Jeunesse": {"nl": "Jeugd", "ko": "아동·청소년", "zh-Hans": "少儿",
                 "tr": "Çocuk ve gençlik", "ru": "Детское", "sv": "Barn och ungdom"},
    "BD & Comics": {"nl": "Strips en graphic novels", "ko": "코믹스·그래픽노블",
                    "zh-Hans": "漫画与图像小说", "tr": "Çizgi roman",
                    "ru": "Комиксы", "sv": "Serier och grafiska romaner"},
    "Classements": {"nl": "Ranglijsten", "ko": "차트", "zh-Hans": "排行榜",
                    "tr": "Listeler", "ru": "Рейтинги", "sv": "Listor"},
    "Payant": {"nl": "Betaald", "ko": "유료", "zh-Hans": "付费",
               "tr": "Ücretli", "ru": "Платные", "sv": "Betald"},
    "Gratuit": {"nl": "Gratis", "ko": "무료", "zh-Hans": "免费",
                "tr": "Ücretsiz", "ru": "Бесплатно", "sv": "Gratis"},
    "Parcourir par genre": {"nl": "Blader op genre", "ko": "장르로 둘러보기",
                            "zh-Hans": "按类型浏览", "tr": "Türe göre gez",
                            "ru": "По жанрам", "sv": "Bläddra efter genre"},
    "Bientôt disponibles !": {"nl": "Binnenkort!", "ko": "곧 출간!",
                              "zh-Hans": "即将上市！", "tr": "Yakında!",
                              "ru": "Скоро!", "sv": "Snart här!"},
    "Dans vos goûts": {"nl": "In jouw smaak", "ko": "취향에 맞는 책",
                       "zh-Hans": "合你口味", "tr": "Zevkine göre",
                       "ru": "В вашем вкусе", "sv": "I din smak"},

    # ----------------------------------------------------------- compte
    "Compte": {"nl": "Account", "ko": "계정", "zh-Hans": "账户",
               "tr": "Hesap", "ru": "Учётная запись", "sv": "Konto"},
    "Se connecter": {"nl": "Log in", "ko": "로그인", "zh-Hans": "登录",
                     "tr": "Giriş yap", "ru": "Войти", "sv": "Logga in"},
    "Se déconnecter": {"nl": "Log uit", "ko": "로그아웃", "zh-Hans": "退出登录",
                       "tr": "Çıkış yap", "ru": "Выйти", "sv": "Logga ut"},
    "Créer un compte": {"nl": "Maak een account", "ko": "계정 만들기",
                        "zh-Hans": "创建账户", "tr": "Hesap oluştur",
                        "ru": "Создать учётную запись", "sv": "Skapa konto"},
    "Continuer sans compte": {
        "nl": "Ga door zonder account", "ko": "계정 없이 계속하기",
        "zh-Hans": "不创建账户，直接使用", "tr": "Hesapsız devam et",
        "ru": "Продолжить без учётной записи", "sv": "Fortsätt utan konto",
    },
    "Connexion avec Apple": {"nl": "Log in met Apple", "ko": "Apple로 로그인",
                             "zh-Hans": "通过 Apple 登录", "tr": "Apple ile giriş yap",
                             "ru": "Вход с Apple", "sv": "Logga in med Apple"},
    "Adresse e-mail": {"nl": "E-mailadres", "ko": "이메일 주소", "zh-Hans": "电子邮件地址",
                       "tr": "E-posta adresi", "ru": "Адрес эл. почты", "sv": "E-postadress"},
    "Mot de passe oublié ?": {"nl": "Wachtwoord vergeten?", "ko": "비밀번호를 잊으셨나요?",
                              "zh-Hans": "忘记密码？", "tr": "Şifreni mi unuttun?",
                              "ru": "Забыли пароль?", "sv": "Glömt lösenordet?"},
    "Supprimer mon compte": {"nl": "Verwijder mijn account", "ko": "계정 삭제",
                             "zh-Hans": "删除我的账户", "tr": "Hesabımı sil",
                             "ru": "Удалить учётную запись", "sv": "Radera mitt konto"},
    "Aucun compte": {"nl": "Geen account", "ko": "계정 없음", "zh-Hans": "无账户",
                     "tr": "Hesap yok", "ru": "Нет учётной записи", "sv": "Inget konto"},

    # ---------------------------------------------------------- réglages
    "Objectifs": {"nl": "Doelen", "ko": "목표", "zh-Hans": "目标",
                  "tr": "Hedefler", "ru": "Цели", "sv": "Mål"},
    "Lecture quotidienne": {"nl": "Dagelijks lezen", "ko": "하루 독서량",
                            "zh-Hans": "每日阅读", "tr": "Günlük okuma",
                            "ru": "Ежедневное чтение", "sv": "Daglig läsning"},
    "Défi annuel": {"nl": "Jaaruitdaging", "ko": "연간 목표", "zh-Hans": "年度挑战",
                    "tr": "Yıllık meydan okuma", "ru": "Годовой вызов",
                    "sv": "Årsutmaning"},
    "Langues de lecture": {"nl": "Leestalen", "ko": "읽는 언어",
                           "zh-Hans": "阅读语言", "tr": "Okuma dilleri",
                           "ru": "Языки чтения", "sv": "Lässpråk"},
    "Affichage": {"nl": "Weergave", "ko": "표시", "zh-Hans": "显示",
                  "tr": "Görünüm", "ru": "Отображение", "sv": "Visning"},
    "Apparence": {"nl": "Uiterlijk", "ko": "화면 모드", "zh-Hans": "外观",
                  "tr": "Görünüm", "ru": "Оформление", "sv": "Utseende"},
    "Système": {"nl": "Systeem", "ko": "시스템 설정", "zh-Hans": "跟随系统",
                "tr": "Sistem", "ru": "Как в системе", "sv": "System"},
    "Clair": {"nl": "Licht", "ko": "라이트", "zh-Hans": "浅色",
              "tr": "Açık", "ru": "Светлое", "sv": "Ljust"},
    "Sombre": {"nl": "Donker", "ko": "다크", "zh-Hans": "深色",
               "tr": "Koyu", "ru": "Тёмное", "sv": "Mörkt"},
    "Données": {"nl": "Gegevens", "ko": "데이터", "zh-Hans": "数据",
                "tr": "Veriler", "ru": "Данные", "sv": "Data"},
    "Stockage": {"nl": "Opslag", "ko": "저장 위치", "zh-Hans": "存储",
                 "tr": "Depolama", "ru": "Хранение", "sv": "Lagring"},
    "À propos": {"nl": "Over", "ko": "정보", "zh-Hans": "关于",
                 "tr": "Hakkında", "ru": "О программе", "sv": "Om"},
    "Tout effacer": {"nl": "Wis alles", "ko": "전체 삭제", "zh-Hans": "全部清除",
                     "tr": "Hepsini sil", "ru": "Стереть всё", "sv": "Radera allt"},

    # ------------------------------------------------------------- badges
    "Badges": {"nl": "Badges", "ko": "배지", "zh-Hans": "徽章",
               "tr": "Rozetler", "ru": "Значки", "sv": "Märken"},
    "Records": {"nl": "Records", "ko": "기록", "zh-Hans": "纪录",
                "tr": "Rekorlar", "ru": "Рекорды", "sv": "Rekord"},
    "Marathon": {"nl": "Marathon", "ko": "마라톤", "zh-Hans": "马拉松",
                 "tr": "Maraton", "ru": "Марафон", "sv": "Maraton"},
    "Nyctalope": {"nl": "Nachtuil", "ko": "밤샘 독서가", "zh-Hans": "夜猫子",
                  "tr": "Gece kuşu", "ru": "Полуночник", "sv": "Nattuggla"},
    "Complétiste": {"nl": "Verzamelaar", "ko": "완독가", "zh-Hans": "完结控",
                    "tr": "Tamamlayıcı", "ru": "Собиратель", "sv": "Fullbordare"},
    "Dévoreur": {"nl": "Verslinder", "ko": "탐독가", "zh-Hans": "书虫",
                 "tr": "Kitap kurdu", "ru": "Пожиратель книг", "sv": "Bokslukare"},
    "Aube": {"nl": "Dageraad", "ko": "새벽", "zh-Hans": "破晓",
             "tr": "Şafak", "ru": "Рассвет", "sv": "Gryning"},
    "Fidèle": {"nl": "Trouw", "ko": "꾸준함", "zh-Hans": "坚持不懈",
               "tr": "Sadık", "ru": "Постоянство", "sv": "Trogen"},
    "La Grande Pile": {"nl": "De Grote Stapel", "ko": "쌓인 책탑",
                       "zh-Hans": "书堆如山", "tr": "Büyük Yığın",
                       "ru": "Большая стопка", "sv": "Den Stora Högen"},
    "Polygraphe": {"nl": "Alleslezer", "ko": "잡식 독서가", "zh-Hans": "博览群书",
                   "tr": "Çok okuyan", "ru": "Всеядный читатель",
                   "sv": "Allätare"},
}

if __name__ == "__main__":
    ecrire(T)
