# -*- coding: utf-8 -*-
"""Traductions — vague 4 : accueil, statistiques, badges, réglages, compte."""
from catalogue import ecrire

T = {
    # -------------------------------------------------------------- accueil
    "En ce moment": {
        "en": "Right now", "es": "Ahora mismo", "es-419": "Ahora mismo",
        "pt-BR": "Agora", "de": "Gerade jetzt", "it": "In questo momento",
        "pl": "W tej chwili", "ja": "いま読んでいる",
    },
    "À suivre": {
        "en": "Watching", "es": "Seguimiento", "es-419": "Seguimiento",
        "pt-BR": "Acompanhando", "de": "Im Blick", "it": "Da seguire",
        "pl": "Obserwowane", "ja": "気になる",
    },
    "Sorties à venir": {
        "en": "Coming out soon", "es": "Próximas publicaciones",
        "es-419": "Próximas publicaciones", "pt-BR": "Próximos lançamentos",
        "de": "Demnächst", "it": "Prossime uscite",
        "pl": "Nadchodzące premiery", "ja": "これから出る本",
    },
    "Les livres que vous comptez ouvrir bientôt.": {
        "en": "The books you mean to open soon.",
        "es": "Los libros que piensas abrir pronto.",
        "es-419": "Los libros que piensas abrir pronto.",
        "pt-BR": "Os livros que você pretende abrir logo.",
        "de": "Die Bücher, die du bald aufschlagen willst.",
        "it": "I libri che pensi di aprire presto.",
        "pl": "Książki, po które chcesz wkrótce sięgnąć.",
        "ja": "そのうち開こうと思っている本。",
    },
    "Les prochains tomes de vos séries.": {
        "en": "The next volumes in your series.",
        "es": "Los próximos tomos de tus series.",
        "es-419": "Los próximos tomos de tus series.",
        "pt-BR": "Os próximos volumes das suas séries.",
        "de": "Die nächsten Bände deiner Reihen.",
        "it": "I prossimi volumi delle tue serie.",
        "pl": "Kolejne tomy Twoich serii.",
        "ja": "追いかけているシリーズの次の巻。",
    },
    "Temps de lecture aujourd'hui": {
        "en": "Reading time today", "es": "Tiempo de lectura de hoy",
        "es-419": "Tiempo de lectura de hoy", "pt-BR": "Tempo de leitura hoje",
        "de": "Lesezeit heute", "it": "Tempo di lettura oggi",
        "pl": "Czas czytania dzisiaj", "ja": "今日の読書時間",
    },
    "sur votre objectif de %lld minutes": {
        "en": "of your %lld-minute goal", "es": "de tu objetivo de %lld minutos",
        "es-419": "de tu meta de %lld minutos", "pt-BR": "da sua meta de %lld minutos",
        "de": "von deinem Ziel von %lld Minuten", "it": "sul tuo obiettivo di %lld minuti",
        "pl": "z celu %lld minut", "ja": "目標%lld分のうち",
    },
    "objectif du jour atteint ✦": {
        "en": "today's goal reached ✦", "es": "objetivo de hoy cumplido ✦",
        "es-419": "meta de hoy cumplida ✦", "pt-BR": "meta de hoje alcançada ✦",
        "de": "Tagesziel erreicht ✦", "it": "obiettivo di oggi raggiunto ✦",
        "pl": "cel dnia osiągnięty ✦", "ja": "今日の目標達成 ✦",
    },
    "objectif du jour atteint dans %lld min": {
        "en": "today's goal in %lld min", "es": "objetivo de hoy en %lld min",
        "es-419": "meta de hoy en %lld min", "pt-BR": "meta de hoje em %lld min",
        "de": "Tagesziel in %lld Min.", "it": "obiettivo di oggi tra %lld min",
        "pl": "cel dnia za %lld min", "ja": "あと%lld分で今日の目標",
    },
    "%lld minutes lues aujourd'hui — lancer une session": {
        "en": "%lld minutes read today — start a session",
        "es": "%lld minutos leídos hoy: empezar una sesión",
        "es-419": "%lld minutos leídos hoy: empezar una sesión",
        "pt-BR": "%lld minutos lidos hoje — começar uma sessão",
        "de": "Heute %lld Minuten gelesen — Sitzung starten",
        "it": "%lld minuti letti oggi — avvia una sessione",
        "pl": "Dziś przeczytane %lld min — rozpocznij sesję",
        "ja": "今日は%lld分。セッションを始める",
    },
    "%lld minutes de lecture": {
        "en": "%lld minutes of reading", "es": "%lld minutos de lectura",
        "es-419": "%lld minutos de lectura", "pt-BR": "%lld minutos de leitura",
        "de": "%lld Minuten Lesen", "it": "%lld minuti di lettura",
        "pl": "%lld minut czytania", "ja": "%lld分の読書",
    },
    "Votre série de lecture est de": {
        "en": "Your reading streak is", "es": "Tu racha de lectura es de",
        "es-419": "Tu racha de lectura es de", "pt-BR": "Sua sequência de leitura é de",
        "de": "Deine Lesesträhne beträgt", "it": "La tua serie di lettura è di",
        "pl": "Twoja seria czytania to", "ja": "連続読書記録は",
    },
    "Jours de lecture de la semaine": {
        "en": "Reading days this week", "es": "Días de lectura de la semana",
        "es-419": "Días de lectura de la semana", "pt-BR": "Dias de leitura da semana",
        "de": "Lesetage dieser Woche", "it": "Giorni di lettura della settimana",
        "pl": "Dni czytania w tym tygodniu", "ja": "今週の読書日",
    },
    "Ajuster": {"en": "Adjust", "es": "Ajustar", "es-419": "Ajustar",
                "pt-BR": "Ajustar", "de": "Anpassen", "it": "Modifica",
                "pl": "Dostosuj", "ja": "調整"},
    "Ajuster l'objectif": {
        "en": "Adjust the goal", "es": "Ajustar el objetivo", "es-419": "Ajustar la meta",
        "pt-BR": "Ajustar a meta", "de": "Ziel anpassen", "it": "Modifica l'obiettivo",
        "pl": "Dostosuj cel", "ja": "目標を調整",
    },
    "Objectif du jour : %lld minutes sur %lld": {
        "en": "Today's goal: %lld minutes of %lld",
        "es": "Objetivo de hoy: %lld minutos de %lld",
        "es-419": "Meta de hoy: %lld minutos de %lld",
        "pt-BR": "Meta de hoje: %lld minutos de %lld",
        "de": "Tagesziel: %lld von %lld Minuten",
        "it": "Obiettivo di oggi: %lld minuti su %lld",
        "pl": "Cel dnia: %lld z %lld minut",
        "ja": "今日の目標：%lld / %lld分",
    },
    "Nouveau record": {
        "en": "New record", "es": "Nuevo récord", "es-419": "Nuevo récord",
        "pt-BR": "Novo recorde", "de": "Neuer Rekord", "it": "Nuovo record",
        "pl": "Nowy rekord", "ja": "新記録",
    },
    "Tout « À lire »": {
        "en": "All “To read”", "es": "Todo «Por leer»", "es-419": "Todo «Por leer»",
        "pt-BR": "Tudo “Para ler”", "de": "Alles „Ungelesen“",
        "it": "Tutto «Da leggere»", "pl": "Wszystko „Do przeczytania”",
        "ja": "「未読」をすべて",
    },
    "Progression": {
        "en": "Progress", "es": "Progreso", "es-419": "Progreso",
        "pt-BR": "Progresso", "de": "Fortschritt", "it": "Avanzamento",
        "pl": "Postęp", "ja": "進み具合",
    },
    "Résumé": {
        "en": "Summary", "es": "Resumen", "es-419": "Resumen", "pt-BR": "Resumo",
        "de": "Zusammenfassung", "it": "Riassunto", "pl": "Streszczenie",
        "ja": "あらすじ",
    },
    "Détails": {
        "en": "Details", "es": "Detalles", "es-419": "Detalles",
        "pt-BR": "Detalhes", "de": "Details", "it": "Dettagli",
        "pl": "Szczegóły", "ja": "詳細",
    },
    "Tomes": {"en": "Volumes", "es": "Tomos", "es-419": "Tomos",
              "pt-BR": "Volumes", "de": "Bände", "it": "Volumi",
              "pl": "Tomy", "ja": "巻"},
    "Possédés": {"en": "Owned", "es": "En estantería", "es-419": "En estantería",
                 "pt-BR": "Na estante", "de": "Im Regal", "it": "Posseduti",
                 "pl": "Na półce", "ja": "所有"},
    "Possédé": {"en": "Owned", "es": "En estantería", "es-419": "En estantería",
                "pt-BR": "Na estante", "de": "Im Regal", "it": "Posseduto",
                "pl": "Na półce", "ja": "所有"},
    "Manquant": {"en": "Missing", "es": "Falta", "es-419": "Falta",
                 "pt-BR": "Falta", "de": "Fehlt", "it": "Mancante",
                 "pl": "Brakuje", "ja": "未所持"},
    "Ajouter un tome": {
        "en": "Add a volume", "es": "Añadir un tomo", "es-419": "Agregar un tomo",
        "pt-BR": "Adicionar um volume", "de": "Band hinzufügen",
        "it": "Aggiungi un volume", "pl": "Dodaj tom", "ja": "巻を追加",
    },

    # --------------------------------------------------------- statistiques
    "Temps de lecture": {
        "en": "Reading time", "es": "Tiempo de lectura", "es-419": "Tiempo de lectura",
        "pt-BR": "Tempo de leitura", "de": "Lesezeit", "it": "Tempo di lettura",
        "pl": "Czas czytania", "ja": "読書時間",
    },
    "Votre bibliothèque": {
        "en": "Your library", "es": "Tu biblioteca", "es-419": "Tu biblioteca",
        "pt-BR": "Sua biblioteca", "de": "Deine Bibliothek", "it": "La tua libreria",
        "pl": "Twoja biblioteka", "ja": "あなたのライブラリ",
    },
    "Compté tout seul depuis vos étagères": {
        "en": "Counted straight from your shelves",
        "es": "Contado solo desde tus estanterías",
        "es-419": "Contado solo desde tus estantes",
        "pt-BR": "Contado sozinho a partir das suas estantes",
        "de": "Direkt aus deinen Regalen gezählt",
        "it": "Contato da solo dai tuoi scaffali",
        "pl": "Policzone samo z Twoich półek",
        "ja": "本棚から自動で数えています",
    },
    "possédés": {"en": "owned", "es": "en estantería", "es-419": "en estantería",
                 "pt-BR": "na estante", "de": "im Regal", "it": "posseduti",
                 "pl": "na półce", "ja": "所有"},
    "lus": {"en": "read", "es": "leídos", "es-419": "leídos", "pt-BR": "lidos",
            "de": "gelesen", "it": "letti", "pl": "przeczytane", "ja": "読了"},
    "en cours": {"en": "reading", "es": "leyendo", "es-419": "leyendo",
                 "pt-BR": "lendo", "de": "aktuell", "it": "in lettura",
                 "pl": "w trakcie", "ja": "読書中"},
    "à acheter": {"en": "to buy", "es": "por comprar", "es-419": "por comprar",
                  "pt-BR": "para comprar", "de": "zu kaufen", "it": "da comprare",
                  "pl": "do kupienia", "ja": "購入予定"},
    "série finie": {"en": "series finished", "es": "serie terminada",
                    "es-419": "serie terminada", "pt-BR": "série concluída",
                    "de": "Reihe beendet", "it": "serie finita",
                    "pl": "ukończona seria", "ja": "完走シリーズ"},
    "séries finies": {"en": "series finished", "es": "series terminadas",
                      "es-419": "series terminadas", "pt-BR": "séries concluídas",
                      "de": "Reihen beendet", "it": "serie finite",
                      "pl": "ukończone serie", "ja": "完走シリーズ"},
    "pages lues": {"en": "pages read", "es": "páginas leídas",
                   "es-419": "páginas leídas", "pt-BR": "páginas lidas",
                   "de": "gelesene Seiten", "it": "pagine lette",
                   "pl": "przeczytane strony", "ja": "読んだページ"},
    "pages": {"en": "pages", "es": "páginas", "es-419": "páginas",
              "pt-BR": "páginas", "de": "Seiten", "it": "pagine",
              "pl": "strony", "ja": "ページ"},
    "pages / heure": {"en": "pages / hour", "es": "páginas / hora",
                      "es-419": "páginas / hora", "pt-BR": "páginas / hora",
                      "de": "Seiten / Stunde", "it": "pagine / ora",
                      "pl": "stron / godz.", "ja": "ページ／時間"},
    "record · min": {"en": "record · min", "es": "récord · min",
                     "es-419": "récord · min", "pt-BR": "recorde · min",
                     "de": "Rekord · Min.", "it": "record · min",
                     "pl": "rekord · min", "ja": "記録・分"},
    "en rayon": {"en": "on the shelf", "es": "en la estantería",
                 "es-419": "en el estante", "pt-BR": "na estante",
                 "de": "im Regal", "it": "sullo scaffale",
                 "pl": "na półce", "ja": "棚にある"},
    "de lecture": {"en": "of reading", "es": "de lectura", "es-419": "de lectura",
                   "pt-BR": "de leitura", "de": "Lesezeit", "it": "di lettura",
                   "pl": "czytania", "ja": "の読書"},
    "Lancez une session depuis l'accueil : minutes, pages et records se mesurent tout seuls.": {
        "en": "Start a session from Today: minutes, pages and records measure themselves.",
        "es": "Empieza una sesión desde Hoy: minutos, páginas y récords se miden solos.",
        "es-419": "Empieza una sesión desde Hoy: minutos, páginas y récords se miden solos.",
        "pt-BR": "Inicie uma sessão em Hoje: minutos, páginas e recordes se medem sozinhos.",
        "de": "Starte eine Sitzung unter „Heute“: Minuten, Seiten und Rekorde messen sich von selbst.",
        "it": "Avvia una sessione da Oggi: minuti, pagine e record si misurano da soli.",
        "pl": "Rozpocznij sesję z ekranu Dziś: minuty, strony i rekordy liczą się same.",
        "ja": "「今日」からセッションを始めれば、分数もページも記録も自動で計測されます。",
    },
    "Défi %@": {"en": "%@ challenge", "es": "Reto %@", "es-419": "Reto %@",
                "pt-BR": "Desafio %@", "de": "Challenge %@", "it": "Sfida %@",
                "pl": "Wyzwanie %@", "ja": "%@のチャレンジ"},
    "Défi annuel": {
        "en": "Yearly challenge", "es": "Reto anual", "es-419": "Reto anual",
        "pt-BR": "Desafio anual", "de": "Jahres-Challenge", "it": "Sfida annuale",
        "pl": "Wyzwanie roczne", "ja": "年間チャレンジ",
    },
    "Vos lectures terminées, mois par mois": {
        "en": "Your finished reads, month by month",
        "es": "Tus lecturas terminadas, mes a mes",
        "es-419": "Tus lecturas terminadas, mes a mes",
        "pt-BR": "Suas leituras concluídas, mês a mês",
        "de": "Deine beendeten Bücher, Monat für Monat",
        "it": "Le tue letture finite, mese per mese",
        "pl": "Twoje ukończone lektury, miesiąc po miesiącu",
        "ja": "読み終えた本を月ごとに",
    },
    "sur %lld lectures": {
        "en": "of %lld reads", "es": "de %lld lecturas", "es-419": "de %lld lecturas",
        "pt-BR": "de %lld leituras", "de": "von %lld Büchern",
        "it": "su %lld letture", "pl": "z %lld lektur", "ja": "%lld冊のうち",
    },
    "sur %lld %@": {
        "en": "of %lld %@", "es": "de %lld %@", "es-419": "de %lld %@",
        "pt-BR": "de %lld %@", "de": "von %lld %@", "it": "su %lld %@",
        "pl": "z %lld %@", "ja": "%lld %@のうち",
    },
    "en avance de %lld": {
        "en": "%lld ahead", "es": "%lld por delante", "es-419": "%lld por delante",
        "pt-BR": "%lld à frente", "de": "%lld voraus", "it": "%lld in anticipo",
        "pl": "%lld do przodu", "ja": "%lld冊先行",
    },
    "en retard de %lld": {
        "en": "%lld behind", "es": "%lld por detrás", "es-419": "%lld por detrás",
        "pt-BR": "%lld atrás", "de": "%lld im Rückstand", "it": "%lld in ritardo",
        "pl": "%lld do nadrobienia", "ja": "%lld冊遅れ",
    },
    "pile dans le rythme": {
        "en": "right on pace", "es": "justo a ritmo", "es-419": "justo a ritmo",
        "pt-BR": "no ritmo certo", "de": "genau im Takt", "it": "esattamente in linea",
        "pl": "dokładnie w tempie", "ja": "ちょうどいいペース",
    },
    "moins → plus": {
        "en": "less → more", "es": "menos → más", "es-419": "menos → más",
        "pt-BR": "menos → mais", "de": "weniger → mehr", "it": "meno → più",
        "pl": "mniej → więcej", "ja": "少ない → 多い",
    },
    "Vos genres": {
        "en": "Your genres", "es": "Tus géneros", "es-419": "Tus géneros",
        "pt-BR": "Seus gêneros", "de": "Deine Genres", "it": "I tuoi generi",
        "pl": "Twoje gatunki", "ja": "あなたのジャンル",
    },
    "Ce que racontent vos étagères": {
        "en": "What your shelves say about you",
        "es": "Lo que cuentan tus estanterías",
        "es-419": "Lo que cuentan tus estantes",
        "pt-BR": "O que suas estantes contam",
        "de": "Was deine Regale erzählen",
        "it": "Cosa raccontano i tuoi scaffali",
        "pl": "Co mówią Twoje półki",
        "ja": "本棚が語るあなた",
    },
    "Les genres apparaîtront avec vos premiers ajouts.": {
        "en": "Genres appear as soon as you add your first books.",
        "es": "Los géneros aparecerán con tus primeras incorporaciones.",
        "es-419": "Los géneros aparecerán con tus primeras incorporaciones.",
        "pt-BR": "Os gêneros aparecem com suas primeiras adições.",
        "de": "Genres erscheinen mit deinen ersten Büchern.",
        "it": "I generi appariranno con le tue prime aggiunte.",
        "pl": "Gatunki pojawią się po dodaniu pierwszych książek.",
        "ja": "本を追加するとジャンルが表示されます。",
    },
    "Records": {"en": "Records", "es": "Récords", "es-419": "Récords",
                "pt-BR": "Recordes", "de": "Rekorde", "it": "Record",
                "pl": "Rekordy", "ja": "記録"},
    "Meilleur mois": {
        "en": "Best month", "es": "Mejor mes", "es-419": "Mejor mes",
        "pt-BR": "Melhor mês", "de": "Bester Monat", "it": "Mese migliore",
        "pl": "Najlepszy miesiąc", "ja": "ベストな月",
    },
    "Plus longue session": {
        "en": "Longest session", "es": "Sesión más larga", "es-419": "Sesión más larga",
        "pt-BR": "Sessão mais longa", "de": "Längste Sitzung",
        "it": "Sessione più lunga", "pl": "Najdłuższa sesja", "ja": "最長セッション",
    },
    "Série de jours de lecture": {
        "en": "Reading streak", "es": "Racha de días de lectura",
        "es-419": "Racha de días de lectura", "pt-BR": "Sequência de dias de leitura",
        "de": "Lesesträhne", "it": "Serie di giorni di lettura",
        "pl": "Seria dni czytania", "ja": "連続読書日数",
    },
    "Sessions": {"en": "Sessions", "es": "Sesiones", "es-419": "Sesiones",
                 "pt-BR": "Sessões", "de": "Sitzungen", "it": "Sessioni",
                 "pl": "Sesje", "ja": "セッション"},
    "Badges": {"en": "Badges", "es": "Insignias", "es-419": "Insignias",
               "pt-BR": "Emblemas", "de": "Abzeichen", "it": "Distintivi",
               "pl": "Odznaki", "ja": "バッジ"},
    "%lld sur %lld débloqués": {
        "en": "%lld of %lld unlocked", "es": "%lld de %lld desbloqueadas",
        "es-419": "%lld de %lld desbloqueadas", "pt-BR": "%lld de %lld desbloqueados",
        "de": "%lld von %lld freigeschaltet", "it": "%lld su %lld sbloccati",
        "pl": "Odblokowano %lld z %lld", "ja": "%lld / %lld 獲得",
    },
    "Rétrospective %@": {
        "en": "%@ in review", "es": "Retrospectiva %@", "es-419": "Retrospectiva %@",
        "pt-BR": "Retrospectiva %@", "de": "Rückblick %@",
        "it": "Retrospettiva %@", "pl": "Podsumowanie %@", "ja": "%@のふりかえり",
    },
    "Votre année de lecture en cartes partageables — rendez-vous en décembre.": {
        "en": "Your reading year as shareable cards — see you in December.",
        "es": "Tu año de lectura en tarjetas para compartir: nos vemos en diciembre.",
        "es-419": "Tu año de lectura en tarjetas para compartir: nos vemos en diciembre.",
        "pt-BR": "Seu ano de leitura em cartões para compartilhar — até dezembro.",
        "de": "Dein Lesejahr als teilbare Karten — wir sehen uns im Dezember.",
        "it": "Il tuo anno di letture in schede da condividere: ci vediamo a dicembre.",
        "pl": "Twój rok czytania w kartach do udostępnienia — do zobaczenia w grudniu.",
        "ja": "一年の読書をシェアできるカードに。12月にお会いしましょう。",
    },

    # --------------------------------------------------------------- badges
    "Marathon": {"en": "Marathon", "es": "Maratón", "es-419": "Maratón",
                 "pt-BR": "Maratona", "de": "Marathon", "it": "Maratona",
                 "pl": "Maraton", "ja": "マラソン"},
    "Nyctalope": {"en": "Night owl", "es": "Ave nocturna", "es-419": "Ave nocturna",
                  "pt-BR": "Coruja", "de": "Nachteule", "it": "Nottambulo",
                  "pl": "Nocny marek", "ja": "夜ふかし"},
    "Complétiste": {"en": "Completionist", "es": "Completista",
                    "es-419": "Completista", "pt-BR": "Completista",
                    "de": "Vervollständiger", "it": "Completista",
                    "pl": "Kompletysta", "ja": "コンプリート"},
    "Polygraphe": {"en": "Omnivore", "es": "Polígrafo", "es-419": "Polígrafo",
                   "pt-BR": "Polígrafo", "de": "Vielleser", "it": "Poligrafo",
                   "pl": "Wszystkożerca", "ja": "雑食読み"},
    "Dévoreur": {"en": "Devourer", "es": "Devorador", "es-419": "Devorador",
                 "pt-BR": "Devorador", "de": "Verschlinger", "it": "Divoratore",
                 "pl": "Pożeracz", "ja": "むさぼり読み"},
    "La Grande Pile": {"en": "The Big Pile", "es": "La Gran Pila",
                       "es-419": "La Gran Pila", "pt-BR": "A Grande Pilha",
                       "de": "Der große Stapel", "it": "La Grande Pila",
                       "pl": "Wielki Stos", "ja": "積読の山"},
    "Aube": {"en": "Daybreak", "es": "Alba", "es-419": "Alba", "pt-BR": "Amanhecer",
             "de": "Morgengrauen", "it": "Alba", "pl": "Świt", "ja": "夜明け"},
    "Fidèle": {"en": "Faithful", "es": "Constante", "es-419": "Constante",
               "pt-BR": "Constante", "de": "Treu", "it": "Costante",
               "pl": "Wierny", "ja": "皆勤"},
    "2 h de lecture d'affilée": {
        "en": "2 hours of reading in a row", "es": "2 h de lectura seguidas",
        "es-419": "2 h de lectura seguidas", "pt-BR": "2 h de leitura seguidas",
        "de": "2 Stunden am Stück lesen", "it": "2 ore di lettura di fila",
        "pl": "2 godziny czytania z rzędu", "ja": "2時間続けて読む",
    },
    "10 sessions après minuit": {
        "en": "10 sessions after midnight", "es": "10 sesiones después de medianoche",
        "es-419": "10 sesiones después de medianoche", "pt-BR": "10 sessões depois da meia-noite",
        "de": "10 Sitzungen nach Mitternacht", "it": "10 sessioni dopo mezzanotte",
        "pl": "10 sesji po północy", "ja": "深夜0時以降に10セッション",
    },
    "Une série finie à 100 %": {
        "en": "A series finished 100 %", "es": "Una serie terminada al 100 %",
        "es-419": "Una serie terminada al 100 %", "pt-BR": "Uma série 100 % concluída",
        "de": "Eine Reihe zu 100 % beendet", "it": "Una serie finita al 100 %",
        "pl": "Seria ukończona w 100 %", "ja": "シリーズを100 %読破",
    },
    "5 genres dans le même mois": {
        "en": "5 genres in one month", "es": "5 géneros en el mismo mes",
        "es-419": "5 géneros en el mismo mes", "pt-BR": "5 gêneros no mesmo mês",
        "de": "5 Genres in einem Monat", "it": "5 generi nello stesso mese",
        "pl": "5 gatunków w jednym miesiącu", "ja": "同じ月に5ジャンル",
    },
    "5 tomes en un week-end": {
        "en": "5 volumes in one weekend", "es": "5 tomos en un fin de semana",
        "es-419": "5 tomos en un fin de semana", "pt-BR": "5 volumes num fim de semana",
        "de": "5 Bände an einem Wochenende", "it": "5 volumi in un weekend",
        "pl": "5 tomów w jeden weekend", "ja": "週末に5巻",
    },
    "50 livres non lus possédés": {
        "en": "50 unread books owned", "es": "50 libros sin leer en la estantería",
        "es-419": "50 libros sin leer en la estantería", "pt-BR": "50 livros não lidos na estante",
        "de": "50 ungelesene Bücher im Regal", "it": "50 libri non letti posseduti",
        "pl": "50 nieprzeczytanych książek na półce", "ja": "未読の本を50冊所有",
    },
    "Lire avant 7 h, 5 fois": {
        "en": "Read before 7 am, 5 times", "es": "Leer antes de las 7 h, 5 veces",
        "es-419": "Leer antes de las 7 h, 5 veces", "pt-BR": "Ler antes das 7 h, 5 vezes",
        "de": "5-mal vor 7 Uhr lesen", "it": "Leggere prima delle 7, 5 volte",
        "pl": "Czytać przed 7 rano, 5 razy", "ja": "朝7時前に5回読む",
    },
    "Série de 30 jours": {
        "en": "A 30-day streak", "es": "Racha de 30 días", "es-419": "Racha de 30 días",
        "pt-BR": "Sequência de 30 dias", "de": "30 Tage am Stück",
        "it": "Serie di 30 giorni", "pl": "Seria 30 dni", "ja": "30日連続",
    },

    # -------------------------------------------------------------- réglages
    "Objectifs": {"en": "Goals", "es": "Objetivos", "es-419": "Metas",
                  "pt-BR": "Metas", "de": "Ziele", "it": "Obiettivi",
                  "pl": "Cele", "ja": "目標"},
    "Objectif de lecture": {
        "en": "Reading goal", "es": "Objetivo de lectura", "es-419": "Meta de lectura",
        "pt-BR": "Meta de leitura", "de": "Leseziel", "it": "Obiettivo di lettura",
        "pl": "Cel czytania", "ja": "読書の目標",
    },
    "Lecture quotidienne": {
        "en": "Daily reading", "es": "Lectura diaria", "es-419": "Lectura diaria",
        "pt-BR": "Leitura diária", "de": "Tägliches Lesen",
        "it": "Lettura quotidiana", "pl": "Codzienne czytanie", "ja": "毎日の読書",
    },
    "Lectures": {"en": "Reads", "es": "Lecturas", "es-419": "Lecturas",
                 "pt-BR": "Leituras", "de": "Bücher", "it": "Letture",
                 "pl": "Lektury", "ja": "読書数"},
    "Un joker par semaine protège votre série de lecture : une soirée ratée ne brûle pas 40 jours d'effort.": {
        "en": "One free pass a week protects your streak: a missed evening doesn't burn 40 days of effort.",
        "es": "Un comodín por semana protege tu racha: una noche perdida no quema 40 días de esfuerzo.",
        "es-419": "Un comodín por semana protege tu racha: una noche perdida no quema 40 días de esfuerzo.",
        "pt-BR": "Um coringa por semana protege sua sequência: uma noite perdida não queima 40 dias de esforço.",
        "de": "Ein Joker pro Woche schützt deine Strähne: ein verpasster Abend verbrennt nicht 40 Tage Mühe.",
        "it": "Un jolly a settimana protegge la tua serie: una sera saltata non brucia 40 giorni di impegno.",
        "pl": "Jeden joker w tygodniu chroni Twoją serię: jeden opuszczony wieczór nie spali 40 dni starań.",
        "ja": "週に一度のジョーカーが連続記録を守ります。一晩逃しても40日の積み重ねは消えません。",
    },
    "Modifiable à tout moment dans les réglages. Un joker par semaine protège votre série.": {
        "en": "Changeable at any time in Settings. One free pass a week protects your streak.",
        "es": "Modificable en cualquier momento en Ajustes. Un comodín por semana protege tu racha.",
        "es-419": "Modificable en cualquier momento en Configuración. Un comodín por semana protege tu racha.",
        "pt-BR": "Alterável a qualquer momento nos Ajustes. Um coringa por semana protege sua sequência.",
        "de": "Jederzeit in den Einstellungen änderbar. Ein Joker pro Woche schützt deine Strähne.",
        "it": "Modificabile in qualsiasi momento nelle Impostazioni. Un jolly a settimana protegge la tua serie.",
        "pl": "Można zmienić w każdej chwili w Ustawieniach. Jeden joker w tygodniu chroni Twoją serię.",
        "ja": "設定からいつでも変更できます。週に一度のジョーカーが連続記録を守ります。",
    },
    "Langues de lecture": {
        "en": "Reading languages", "es": "Idiomas de lectura",
        "es-419": "Idiomas de lectura", "pt-BR": "Idiomas de leitura",
        "de": "Lesesprachen", "it": "Lingue di lettura",
        "pl": "Języki czytania", "ja": "読む言語",
    },
    "La première langue est la principale : la recherche la privilégie et les titres s'affichent dans leur version officielle publiée dans cette langue — jamais de traduction automatique.": {
        "en": "The first language is the main one: search favours it and titles appear in their official published version in that language — never machine-translated.",
        "es": "El primer idioma es el principal: la búsqueda lo prioriza y los títulos aparecen en su versión oficial publicada en ese idioma, nunca traducidos automáticamente.",
        "es-419": "El primer idioma es el principal: la búsqueda lo prioriza y los títulos aparecen en su versión oficial publicada en ese idioma, nunca traducidos automáticamente.",
        "pt-BR": "O primeiro idioma é o principal: a busca o prioriza e os títulos aparecem na versão oficial publicada nesse idioma — nunca em tradução automática.",
        "de": "Die erste Sprache ist die Hauptsprache: Die Suche bevorzugt sie, und Titel erscheinen in ihrer offiziell veröffentlichten Fassung — nie maschinell übersetzt.",
        "it": "La prima lingua è quella principale: la ricerca la privilegia e i titoli appaiono nella loro versione ufficiale pubblicata in quella lingua, mai tradotti automaticamente.",
        "pl": "Pierwszy język jest głównym: wyszukiwanie go faworyzuje, a tytuły pojawiają się w oficjalnym wydaniu w tym języku — nigdy w tłumaczeniu maszynowym.",
        "ja": "最初の言語が主言語です。検索はそれを優先し、タイトルはその言語で正式に出版された表記で表示されます（機械翻訳は使いません）。",
    },
    "La recherche privilégie les éditions dans vos langues, et les titres s'affichent tels qu'ils sont officiellement publiés.": {
        "en": "Search favours editions in your languages, and titles appear exactly as officially published.",
        "es": "La búsqueda prioriza las ediciones en tus idiomas y los títulos se muestran tal como se publicaron oficialmente.",
        "es-419": "La búsqueda prioriza las ediciones en tus idiomas y los títulos se muestran tal como se publicaron oficialmente.",
        "pt-BR": "A busca prioriza edições nos seus idiomas, e os títulos aparecem exatamente como foram publicados.",
        "de": "Die Suche bevorzugt Ausgaben in deinen Sprachen, und Titel erscheinen genau so, wie sie veröffentlicht wurden.",
        "it": "La ricerca privilegia le edizioni nelle tue lingue e i titoli appaiono così come sono stati pubblicati.",
        "pl": "Wyszukiwanie faworyzuje wydania w Twoich językach, a tytuły pojawiają się dokładnie tak, jak je oficjalnie wydano.",
        "ja": "検索はあなたの言語の版を優先し、タイトルは正式に出版された表記のまま表示されます。",
    },
    "Affichage": {"en": "Display", "es": "Aspecto", "es-419": "Aspecto",
                  "pt-BR": "Exibição", "de": "Darstellung", "it": "Aspetto",
                  "pl": "Wygląd", "ja": "表示"},
    "Apparence": {"en": "Appearance", "es": "Apariencia", "es-419": "Apariencia",
                  "pt-BR": "Aparência", "de": "Erscheinungsbild", "it": "Aspetto",
                  "pl": "Wygląd", "ja": "外観"},
    "Système": {"en": "System", "es": "Sistema", "es-419": "Sistema",
                "pt-BR": "Sistema", "de": "System", "it": "Sistema",
                "pl": "Systemowy", "ja": "システムに従う"},
    "Clair": {"en": "Light", "es": "Claro", "es-419": "Claro", "pt-BR": "Claro",
              "de": "Hell", "it": "Chiaro", "pl": "Jasny", "ja": "ライト"},
    "Sombre": {"en": "Dark", "es": "Oscuro", "es-419": "Oscuro", "pt-BR": "Escuro",
               "de": "Dunkel", "it": "Scuro", "pl": "Ciemny", "ja": "ダーク"},
    "« Système » suit le réglage de votre iPhone.": {
        "en": "“System” follows your iPhone's setting.",
        "es": "«Sistema» sigue el ajuste de tu iPhone.",
        "es-419": "«Sistema» sigue la configuración de tu iPhone.",
        "pt-BR": "“Sistema” segue o ajuste do seu iPhone.",
        "de": "„System“ folgt der Einstellung deines iPhone.",
        "it": "«Sistema» segue l'impostazione del tuo iPhone.",
        "pl": "„Systemowy” podąża za ustawieniem iPhone'a.",
        "ja": "「システムに従う」はiPhoneの設定に合わせます。",
    },
    "Données": {"en": "Data", "es": "Datos", "es-419": "Datos", "pt-BR": "Dados",
                "de": "Daten", "it": "Dati", "pl": "Dane", "ja": "データ"},
    "Stockage": {"en": "Storage", "es": "Almacenamiento", "es-419": "Almacenamiento",
                 "pt-BR": "Armazenamento", "de": "Speicher", "it": "Archiviazione",
                 "pl": "Przechowywanie", "ja": "保存先"},
    "La synchronisation iCloud (CloudKit) arrive dans une prochaine version — vos données restent à vous.": {
        "en": "iCloud sync (CloudKit) is coming in a future version — your data stays yours.",
        "es": "La sincronización con iCloud (CloudKit) llegará en una próxima versión: tus datos siguen siendo tuyos.",
        "es-419": "La sincronización con iCloud (CloudKit) llegará en una próxima versión: tus datos siguen siendo tuyos.",
        "pt-BR": "A sincronização com iCloud (CloudKit) chega numa próxima versão — seus dados continuam seus.",
        "de": "Die iCloud-Synchronisierung (CloudKit) kommt in einer späteren Version — deine Daten bleiben deine.",
        "it": "La sincronizzazione iCloud (CloudKit) arriverà in una prossima versione: i tuoi dati restano tuoi.",
        "pl": "Synchronizacja z iCloud (CloudKit) pojawi się w kolejnej wersji — Twoje dane pozostają Twoje.",
        "ja": "iCloud同期（CloudKit）は今後のバージョンで対応予定です。データはあなたのものです。",
    },
    "Tout effacer": {
        "en": "Erase everything", "es": "Borrarlo todo", "es-419": "Borrar todo",
        "pt-BR": "Apagar tudo", "de": "Alles löschen", "it": "Cancella tutto",
        "pl": "Usuń wszystko", "ja": "すべて消去",
    },
    "Tout effacer…": {
        "en": "Erase everything…", "es": "Borrarlo todo…", "es-419": "Borrar todo…",
        "pt-BR": "Apagar tudo…", "de": "Alles löschen…", "it": "Cancella tutto…",
        "pl": "Usuń wszystko…", "ja": "すべて消去…",
    },
    "Effacer toute la bibliothèque, les sessions et les badges ? Cette action est définitive.": {
        "en": "Erase the whole library, sessions and badges? This cannot be undone.",
        "es": "¿Borrar toda la biblioteca, las sesiones y las insignias? Esta acción es definitiva.",
        "es-419": "¿Borrar toda la biblioteca, las sesiones y las insignias? Esta acción es definitiva.",
        "pt-BR": "Apagar toda a biblioteca, as sessões e os emblemas? Esta ação é definitiva.",
        "de": "Die ganze Bibliothek, Sitzungen und Abzeichen löschen? Das lässt sich nicht rückgängig machen.",
        "it": "Cancellare tutta la libreria, le sessioni e i distintivi? L'azione è definitiva.",
        "pl": "Usunąć całą bibliotekę, sesje i odznaki? Tej operacji nie da się cofnąć.",
        "ja": "ライブラリ・セッション・バッジをすべて消去しますか？ この操作は取り消せません。",
    },
    "À propos": {"en": "About", "es": "Acerca de", "es-419": "Acerca de",
                 "pt-BR": "Sobre", "de": "Über", "it": "Informazioni",
                 "pl": "O aplikacji", "ja": "このアプリについて"},
    "Métadonnées : Google Books, Open Library, AniList. Les couvertures restent la propriété de leurs éditeurs.": {
        "en": "Metadata: Google Books, Open Library, AniList. Covers remain the property of their publishers.",
        "es": "Metadatos: Google Books, Open Library, AniList. Las portadas siguen siendo propiedad de sus editoriales.",
        "es-419": "Metadatos: Google Books, Open Library, AniList. Las portadas siguen siendo propiedad de sus editoriales.",
        "pt-BR": "Metadados: Google Books, Open Library, AniList. As capas continuam sendo propriedade das editoras.",
        "de": "Metadaten: Google Books, Open Library, AniList. Cover bleiben Eigentum der Verlage.",
        "it": "Metadati: Google Books, Open Library, AniList. Le copertine restano di proprietà degli editori.",
        "pl": "Metadane: Google Books, Open Library, AniList. Okładki pozostają własnością wydawców.",
        "ja": "メタデータ：Google Books、Open Library、AniList。表紙は各出版社に帰属します。",
    },

    # ---------------------------------------------------------------- compte
    "Compte": {"en": "Account", "es": "Cuenta", "es-419": "Cuenta",
               "pt-BR": "Conta", "de": "Account", "it": "Account",
               "pl": "Konto", "ja": "アカウント"},
    "Compte Apple": {"en": "Apple Account", "es": "Cuenta de Apple",
                     "es-419": "Cuenta de Apple", "pt-BR": "Conta Apple",
                     "de": "Apple-Account", "it": "Account Apple",
                     "pl": "Konto Apple", "ja": "Appleアカウント"},
    "Compte Honya": {"en": "Honya account", "es": "Cuenta de Honya",
                     "es-419": "Cuenta de Honya", "pt-BR": "Conta Honya",
                     "de": "Honya-Account", "it": "Account Honya",
                     "pl": "Konto Honya", "ja": "Honyaアカウント"},
    "Aucun compte": {"en": "No account", "es": "Sin cuenta", "es-419": "Sin cuenta",
                     "pt-BR": "Sem conta", "de": "Kein Account",
                     "it": "Nessun account", "pl": "Brak konta", "ja": "アカウントなし"},
    "Connexion avec Apple": {
        "en": "Sign in with Apple", "es": "Iniciar sesión con Apple",
        "es-419": "Iniciar sesión con Apple", "pt-BR": "Entrar com a Apple",
        "de": "Mit Apple anmelden", "it": "Accedi con Apple",
        "pl": "Zaloguj się z Apple", "ja": "Appleでサインイン",
    },
    "Adresse e-mail": {
        "en": "Email address", "es": "Correo electrónico", "es-419": "Correo electrónico",
        "pt-BR": "E-mail", "de": "E-Mail-Adresse", "it": "Indirizzo e-mail",
        "pl": "Adres e-mail", "ja": "メールアドレス",
    },
    "Se connecter": {
        "en": "Sign in", "es": "Iniciar sesión", "es-419": "Iniciar sesión",
        "pt-BR": "Entrar", "de": "Anmelden", "it": "Accedi",
        "pl": "Zaloguj się", "ja": "サインイン",
    },
    "Se déconnecter": {
        "en": "Sign out", "es": "Cerrar sesión", "es-419": "Cerrar sesión",
        "pt-BR": "Sair", "de": "Abmelden", "it": "Esci",
        "pl": "Wyloguj się", "ja": "サインアウト",
    },
    "Créer un compte": {
        "en": "Create an account", "es": "Crear una cuenta", "es-419": "Crear una cuenta",
        "pt-BR": "Criar uma conta", "de": "Account erstellen",
        "it": "Crea un account", "pl": "Załóż konto", "ja": "アカウントを作る",
    },
    "Créer mon compte": {
        "en": "Create my account", "es": "Crear mi cuenta", "es-419": "Crear mi cuenta",
        "pt-BR": "Criar minha conta", "de": "Meinen Account erstellen",
        "it": "Crea il mio account", "pl": "Załóż moje konto", "ja": "アカウントを作成",
    },
    "Créer un compte ou se connecter": {
        "en": "Create an account or sign in", "es": "Crear una cuenta o iniciar sesión",
        "es-419": "Crear una cuenta o iniciar sesión", "pt-BR": "Criar uma conta ou entrar",
        "de": "Account erstellen oder anmelden", "it": "Crea un account o accedi",
        "pl": "Załóż konto lub zaloguj się", "ja": "アカウント作成またはサインイン",
    },
    "Continuer sans compte": {
        "en": "Continue without an account", "es": "Continuar sin cuenta",
        "es-419": "Continuar sin cuenta", "pt-BR": "Continuar sem conta",
        "de": "Ohne Account fortfahren", "it": "Continua senza account",
        "pl": "Kontynuuj bez konta", "ja": "アカウントなしで続ける",
    },
    "Utiliser une adresse e-mail": {
        "en": "Use an email address", "es": "Usar un correo electrónico",
        "es-419": "Usar un correo electrónico", "pt-BR": "Usar um e-mail",
        "de": "E-Mail-Adresse verwenden", "it": "Usa un indirizzo e-mail",
        "pl": "Użyj adresu e-mail", "ja": "メールアドレスを使う",
    },
    "Utiliser mon identifiant Apple": {
        "en": "Use my Apple Account", "es": "Usar mi cuenta de Apple",
        "es-419": "Usar mi cuenta de Apple", "pt-BR": "Usar minha conta Apple",
        "de": "Meinen Apple-Account verwenden", "it": "Usa il mio account Apple",
        "pl": "Użyj mojego konta Apple", "ja": "Appleアカウントを使う",
    },
    "Mot de passe oublié ?": {
        "en": "Forgotten your password?", "es": "¿Olvidaste tu contraseña?",
        "es-419": "¿Olvidaste tu contraseña?", "pt-BR": "Esqueceu a senha?",
        "de": "Passwort vergessen?", "it": "Password dimenticata?",
        "pl": "Nie pamiętasz hasła?", "ja": "パスワードをお忘れですか？",
    },
    "Créez votre compte avec une adresse e-mail.": {
        "en": "Create your account with an email address.",
        "es": "Crea tu cuenta con un correo electrónico.",
        "es-419": "Crea tu cuenta con un correo electrónico.",
        "pt-BR": "Crie sua conta com um e-mail.",
        "de": "Erstelle deinen Account mit einer E-Mail-Adresse.",
        "it": "Crea il tuo account con un indirizzo e-mail.",
        "pl": "Załóż konto na adres e-mail.",
        "ja": "メールアドレスでアカウントを作成します。",
    },
    "Content de vous revoir.": {
        "en": "Good to see you again.", "es": "Qué bien volver a verte.",
        "es-419": "Qué bueno verte de nuevo.", "pt-BR": "Que bom te ver de novo.",
        "de": "Schön, dich wiederzusehen.", "it": "Bello rivederti.",
        "pl": "Dobrze Cię znów widzieć.", "ja": "おかえりなさい。",
    },
    "Tous vos tomes, à jour": {
        "en": "Every volume, kept current", "es": "Todos tus tomos, al día",
        "es-419": "Todos tus tomos, al día", "pt-BR": "Todos os seus volumes, em dia",
        "de": "Alle deine Bände, immer aktuell", "it": "Tutti i tuoi volumi, aggiornati",
        "pl": "Wszystkie tomy, zawsze aktualne", "ja": "全巻をいつも最新に",
    },
    "Ajoutez un tome, la série entière apparaît — dates de sortie comprises.": {
        "en": "Add one volume and the whole series appears — release dates included.",
        "es": "Añade un tomo y aparece la serie entera, fechas de publicación incluidas.",
        "es-419": "Agrega un tomo y aparece la serie entera, fechas de publicación incluidas.",
        "pt-BR": "Adicione um volume e a série inteira aparece — datas de lançamento incluídas.",
        "de": "Füge einen Band hinzu, und die ganze Reihe erscheint — samt Erscheinungsdaten.",
        "it": "Aggiungi un volume e appare l'intera serie, date di uscita comprese.",
        "pl": "Dodaj jeden tom, a pojawi się cała seria — razem z datami premier.",
        "ja": "一巻を追加すればシリーズ全体が並びます。発売日も含めて。",
    },
    "Dans votre langue": {
        "en": "In your language", "es": "En tu idioma", "es-419": "En tu idioma",
        "pt-BR": "No seu idioma", "de": "In deiner Sprache", "it": "Nella tua lingua",
        "pl": "W Twoim języku", "ja": "あなたの言語で",
    },
    "Titres, couvertures et résumés dans l'édition de votre pays.": {
        "en": "Titles, covers and blurbs from your country's edition.",
        "es": "Títulos, portadas y resúmenes de la edición de tu país.",
        "es-419": "Títulos, portadas y resúmenes de la edición de tu país.",
        "pt-BR": "Títulos, capas e sinopses da edição do seu país.",
        "de": "Titel, Cover und Klappentexte der Ausgabe deines Landes.",
        "it": "Titoli, copertine e trame dell'edizione del tuo Paese.",
        "pl": "Tytuły, okładki i opisy z wydania w Twoim kraju.",
        "ja": "あなたの国の版のタイトル・表紙・あらすじ。",
    },
    "Vos lectures vous appartiennent": {
        "en": "Your reading is yours", "es": "Tus lecturas son tuyas",
        "es-419": "Tus lecturas son tuyas", "pt-BR": "Suas leituras são suas",
        "de": "Deine Lektüre gehört dir", "it": "Le tue letture sono tue",
        "pl": "Twoje lektury należą do Ciebie", "ja": "読書はあなたのもの",
    },
    "Rien n'est partagé, et votre compte s'efface d'un bouton.": {
        "en": "Nothing is shared, and your account is one button away from being gone.",
        "es": "No se comparte nada, y tu cuenta se borra con un botón.",
        "es-419": "No se comparte nada, y tu cuenta se borra con un botón.",
        "pt-BR": "Nada é compartilhado, e sua conta some com um botão.",
        "de": "Nichts wird geteilt, und dein Account ist mit einem Knopf gelöscht.",
        "it": "Nulla viene condiviso, e il tuo account si cancella con un pulsante.",
        "pl": "Nic nie jest udostępniane, a konto usuwasz jednym przyciskiem.",
        "ja": "何も共有されません。アカウントはボタンひとつで消せます。",
    },
    "Vos lectures restent sur votre appareil. Vous pouvez supprimer votre compte à tout moment depuis les réglages.": {
        "en": "Your reading stays on your device. You can delete your account at any time from Settings.",
        "es": "Tus lecturas se quedan en tu dispositivo. Puedes eliminar tu cuenta cuando quieras desde Ajustes.",
        "es-419": "Tus lecturas se quedan en tu dispositivo. Puedes eliminar tu cuenta cuando quieras desde Configuración.",
        "pt-BR": "Suas leituras ficam no seu aparelho. Você pode excluir sua conta quando quiser nos Ajustes.",
        "de": "Deine Lektüre bleibt auf deinem Gerät. Du kannst deinen Account jederzeit in den Einstellungen löschen.",
        "it": "Le tue letture restano sul tuo dispositivo. Puoi eliminare l'account quando vuoi dalle Impostazioni.",
        "pl": "Twoje lektury zostają na urządzeniu. Konto możesz usunąć w każdej chwili w Ustawieniach.",
        "ja": "読書の記録は端末に残ります。アカウントは設定からいつでも削除できます。",
    },
    "Vous utilisez Honya sans compte : tout reste sur cet appareil.": {
        "en": "You're using Honya without an account: everything stays on this device.",
        "es": "Usas Honya sin cuenta: todo se queda en este dispositivo.",
        "es-419": "Usas Honya sin cuenta: todo se queda en este dispositivo.",
        "pt-BR": "Você usa o Honya sem conta: tudo fica neste aparelho.",
        "de": "Du nutzt Honya ohne Account: Alles bleibt auf diesem Gerät.",
        "it": "Usi Honya senza account: tutto resta su questo dispositivo.",
        "pl": "Używasz Honya bez konta: wszystko zostaje na tym urządzeniu.",
        "ja": "アカウントなしでHonyaを使っています。すべてこの端末に残ります。",
    },
    "Supprimer mon compte": {
        "en": "Delete my account", "es": "Eliminar mi cuenta", "es-419": "Eliminar mi cuenta",
        "pt-BR": "Excluir minha conta", "de": "Meinen Account löschen",
        "it": "Elimina il mio account", "pl": "Usuń moje konto", "ja": "アカウントを削除",
    },
    "Supprimer définitivement": {
        "en": "Delete permanently", "es": "Eliminar definitivamente",
        "es-419": "Eliminar definitivamente", "pt-BR": "Excluir definitivamente",
        "de": "Endgültig löschen", "it": "Elimina definitivamente",
        "pl": "Usuń trwale", "ja": "完全に削除",
    },
    "Supprimer votre compte et toutes vos données ?": {
        "en": "Delete your account and all your data?",
        "es": "¿Eliminar tu cuenta y todos tus datos?",
        "es-419": "¿Eliminar tu cuenta y todos tus datos?",
        "pt-BR": "Excluir sua conta e todos os seus dados?",
        "de": "Deinen Account und alle Daten löschen?",
        "it": "Eliminare il tuo account e tutti i tuoi dati?",
        "pl": "Usunąć konto i wszystkie dane?",
        "ja": "アカウントとすべてのデータを削除しますか？",
    },
    "Votre bibliothèque, vos sessions, vos badges et vos étagères seront effacés. C'est sans retour.": {
        "en": "Your library, sessions, badges and shelves will be erased. There's no going back.",
        "es": "Tu biblioteca, tus sesiones, tus insignias y tus estanterías se borrarán. No hay vuelta atrás.",
        "es-419": "Tu biblioteca, tus sesiones, tus insignias y tus estantes se borrarán. No hay vuelta atrás.",
        "pt-BR": "Sua biblioteca, sessões, emblemas e estantes serão apagados. Não há volta.",
        "de": "Deine Bibliothek, Sitzungen, Abzeichen und Regale werden gelöscht. Ohne Rückweg.",
        "it": "La tua libreria, le sessioni, i distintivi e gli scaffali saranno cancellati. Senza ritorno.",
        "pl": "Twoja biblioteka, sesje, odznaki i półki zostaną usunięte. Bez odwrotu.",
        "ja": "ライブラリ・セッション・バッジ・本棚がすべて消えます。取り消せません。",
    },
    "Supprimer votre compte efface aussi toute votre bibliothèque sur cet appareil. Pour retirer Honya de votre identifiant Apple, allez dans Réglages > votre nom > Connexion avec Apple.": {
        "en": "Deleting your account also erases your whole library on this device. To remove Honya from your Apple Account, go to Settings > your name > Sign in with Apple.",
        "es": "Eliminar tu cuenta también borra toda tu biblioteca en este dispositivo. Para quitar Honya de tu cuenta de Apple, ve a Ajustes > tu nombre > Iniciar sesión con Apple.",
        "es-419": "Eliminar tu cuenta también borra toda tu biblioteca en este dispositivo. Para quitar Honya de tu cuenta de Apple, ve a Configuración > tu nombre > Iniciar sesión con Apple.",
        "pt-BR": "Excluir sua conta também apaga toda a sua biblioteca neste aparelho. Para remover o Honya da sua conta Apple, vá em Ajustes > seu nome > Entrar com a Apple.",
        "de": "Das Löschen deines Accounts löscht auch die gesamte Bibliothek auf diesem Gerät. Um Honya von deinem Apple-Account zu trennen: Einstellungen > dein Name > Mit Apple anmelden.",
        "it": "Eliminare l'account cancella anche tutta la libreria su questo dispositivo. Per togliere Honya dal tuo account Apple, vai in Impostazioni > il tuo nome > Accedi con Apple.",
        "pl": "Usunięcie konta kasuje też całą bibliotekę na tym urządzeniu. Aby odłączyć Honya od konta Apple: Ustawienia > Twoje imię > Zaloguj się z Apple.",
        "ja": "アカウントを削除すると、この端末のライブラリもすべて消えます。AppleアカウントからHonyaを解除するには、設定＞ご自分の名前＞Appleでサインイン へ。",
    },
    "Compte créé. Ouvrez le courrier de confirmation, puis connectez-vous.": {
        "en": "Account created. Open the confirmation email, then sign in.",
        "es": "Cuenta creada. Abre el correo de confirmación y luego inicia sesión.",
        "es-419": "Cuenta creada. Abre el correo de confirmación y luego inicia sesión.",
        "pt-BR": "Conta criada. Abra o e-mail de confirmação e depois entre.",
        "de": "Account erstellt. Öffne die Bestätigungs-E-Mail und melde dich dann an.",
        "it": "Account creato. Apri l'e-mail di conferma, poi accedi.",
        "pl": "Konto utworzone. Otwórz e-mail potwierdzający, a potem zaloguj się.",
        "ja": "アカウントを作成しました。確認メールを開いてからサインインしてください。",
    },
    "Adresse e-mail ou mot de passe incorrect.": {
        "en": "Wrong email address or password.",
        "es": "Correo electrónico o contraseña incorrectos.",
        "es-419": "Correo electrónico o contraseña incorrectos.",
        "pt-BR": "E-mail ou senha incorretos.",
        "de": "E-Mail-Adresse oder Passwort ist falsch.",
        "it": "Indirizzo e-mail o password non corretti.",
        "pl": "Nieprawidłowy adres e-mail lub hasło.",
        "ja": "メールアドレスまたはパスワードが正しくありません。",
    },
    "Un compte existe déjà avec cette adresse. Connectez-vous.": {
        "en": "An account already exists with this address. Sign in.",
        "es": "Ya existe una cuenta con esta dirección. Inicia sesión.",
        "es-419": "Ya existe una cuenta con esta dirección. Inicia sesión.",
        "pt-BR": "Já existe uma conta com este endereço. Entre.",
        "de": "Mit dieser Adresse gibt es bereits einen Account. Melde dich an.",
        "it": "Esiste già un account con questo indirizzo. Accedi.",
        "pl": "Konto z tym adresem już istnieje. Zaloguj się.",
        "ja": "このアドレスのアカウントは既にあります。サインインしてください。",
    },
    "Le mot de passe doit faire au moins 6 caractères.": {
        "en": "The password must be at least 6 characters.",
        "es": "La contraseña debe tener al menos 6 caracteres.",
        "es-419": "La contraseña debe tener al menos 6 caracteres.",
        "pt-BR": "A senha precisa ter pelo menos 6 caracteres.",
        "de": "Das Passwort muss mindestens 6 Zeichen haben.",
        "it": "La password deve avere almeno 6 caratteri.",
        "pl": "Hasło musi mieć co najmniej 6 znaków.",
        "ja": "パスワードは6文字以上にしてください。",
    },
    "Cette adresse e-mail ne semble pas valide.": {
        "en": "That email address doesn't look valid.",
        "es": "Ese correo electrónico no parece válido.",
        "es-419": "Ese correo electrónico no parece válido.",
        "pt-BR": "Esse e-mail não parece válido.",
        "de": "Diese E-Mail-Adresse sieht nicht gültig aus.",
        "it": "Questo indirizzo e-mail non sembra valido.",
        "pl": "Ten adres e-mail nie wygląda poprawnie.",
        "ja": "そのメールアドレスは正しくないようです。",
    },
    "Confirmez d'abord votre adresse : un courrier vous attend.": {
        "en": "Confirm your address first: an email is waiting for you.",
        "es": "Confirma primero tu dirección: te espera un correo.",
        "es-419": "Confirma primero tu dirección: te espera un correo.",
        "pt-BR": "Confirme primeiro seu endereço: um e-mail espera por você.",
        "de": "Bestätige zuerst deine Adresse: Eine E-Mail wartet auf dich.",
        "it": "Conferma prima il tuo indirizzo: ti aspetta un'e-mail.",
        "pl": "Najpierw potwierdź adres: czeka na Ciebie e-mail.",
        "ja": "まずアドレスを確認してください。メールが届いています。",
    },
    "Trop de tentatives. Réessayez dans quelques minutes.": {
        "en": "Too many attempts. Try again in a few minutes.",
        "es": "Demasiados intentos. Inténtalo de nuevo en unos minutos.",
        "es-419": "Demasiados intentos. Inténtalo de nuevo en unos minutos.",
        "pt-BR": "Tentativas demais. Tente de novo em alguns minutos.",
        "de": "Zu viele Versuche. Versuche es in ein paar Minuten erneut.",
        "it": "Troppi tentativi. Riprova tra qualche minuto.",
        "pl": "Zbyt wiele prób. Spróbuj ponownie za kilka minut.",
        "ja": "試行回数が多すぎます。数分後にもう一度お試しください。",
    },
    "Réponse inattendue du serveur.": {
        "en": "Unexpected response from the server.",
        "es": "Respuesta inesperada del servidor.",
        "es-419": "Respuesta inesperada del servidor.",
        "pt-BR": "Resposta inesperada do servidor.",
        "de": "Unerwartete Antwort vom Server.",
        "it": "Risposta inattesa dal server.",
        "pl": "Nieoczekiwana odpowiedź serwera.",
        "ja": "サーバーから予期しない応答がありました。",
    },
    "La connexion a échoué (erreur %lld).": {
        "en": "Connection failed (error %lld).",
        "es": "La conexión ha fallado (error %lld).",
        "es-419": "La conexión falló (error %lld).",
        "pt-BR": "A conexão falhou (erro %lld).",
        "de": "Die Verbindung ist fehlgeschlagen (Fehler %lld).",
        "it": "Connessione non riuscita (errore %lld).",
        "pl": "Połączenie nie powiodło się (błąd %lld).",
        "ja": "接続に失敗しました（エラー %lld）。",
    },
    "Les comptes par adresse e-mail ne sont pas encore configurés dans cette version.": {
        "en": "Email accounts aren't set up in this version yet.",
        "es": "Las cuentas por correo electrónico aún no están configuradas en esta versión.",
        "es-419": "Las cuentas por correo electrónico aún no están configuradas en esta versión.",
        "pt-BR": "As contas por e-mail ainda não estão configuradas nesta versão.",
        "de": "E-Mail-Accounts sind in dieser Version noch nicht eingerichtet.",
        "it": "Gli account via e-mail non sono ancora configurati in questa versione.",
        "pl": "Konta e-mail nie są jeszcze skonfigurowane w tej wersji.",
        "ja": "このバージョンではメールアカウントはまだ利用できません。",
    },

    # ------------------------------------------------------------ onboarding
    "Bienvenue dans Honya": {
        "en": "Welcome to Honya", "es": "Bienvenido a Honya", "es-419": "Bienvenido a Honya",
        "pt-BR": "Bem-vindo ao Honya", "de": "Willkommen bei Honya",
        "it": "Benvenuto in Honya", "pl": "Witaj w Honya", "ja": "Honyaへようこそ",
    },
    "Votre bibliothèque, vivante.\nQue lisez-vous ?": {
        "en": "Your library, alive.\nWhat are you reading?",
        "es": "Tu biblioteca, viva.\n¿Qué estás leyendo?",
        "es-419": "Tu biblioteca, viva.\n¿Qué estás leyendo?",
        "pt-BR": "Sua biblioteca, viva.\nO que você está lendo?",
        "de": "Deine Bibliothek, lebendig.\nWas liest du gerade?",
        "it": "La tua libreria, viva.\nCosa stai leggendo?",
        "pl": "Twoja biblioteka, żywa.\nCo czytasz?",
        "ja": "生きているライブラリ。\n今なにを読んでいますか？",
    },
    "Vos langues\nde lecture": {
        "en": "Your reading\nlanguages", "es": "Tus idiomas\nde lectura",
        "es-419": "Tus idiomas\nde lectura", "pt-BR": "Seus idiomas\nde leitura",
        "de": "Deine\nLesesprachen", "it": "Le tue lingue\ndi lettura",
        "pl": "Twoje języki\nczytania", "ja": "読む言語を\n選ぶ",
    },
    "Un petit objectif\nchaque jour": {
        "en": "A small goal\nevery day", "es": "Un pequeño objetivo\ncada día",
        "es-419": "Una pequeña meta\ncada día", "pt-BR": "Uma pequena meta\ntodos os dias",
        "de": "Ein kleines Ziel\njeden Tag", "it": "Un piccolo obiettivo\nogni giorno",
        "pl": "Mały cel\nkażdego dnia", "ja": "毎日、小さな目標を",
    },
    "Comme dans Apple Books : quelques minutes par jour suffisent à construire une série.": {
        "en": "Like in Apple Books: a few minutes a day are enough to build a streak.",
        "es": "Como en Apple Books: bastan unos minutos al día para construir una racha.",
        "es-419": "Como en Apple Books: bastan unos minutos al día para construir una racha.",
        "pt-BR": "Como no Apple Books: bastam alguns minutos por dia para formar uma sequência.",
        "de": "Wie in Apple Books: Ein paar Minuten am Tag genügen für eine Strähne.",
        "it": "Come in Apple Books: bastano pochi minuti al giorno per costruire una serie.",
        "pl": "Jak w Apple Books: kilka minut dziennie wystarczy, by zbudować serię.",
        "ja": "Appleブックスと同じで、1日数分あれば記録は続きます。",
    },
    "Lisez chaque jour : la série grandit et les statistiques suivent.": {
        "en": "Read every day: the streak grows and the statistics follow.",
        "es": "Lee cada día: la racha crece y las estadísticas la siguen.",
        "es-419": "Lee cada día: la racha crece y las estadísticas la siguen.",
        "pt-BR": "Leia todo dia: a sequência cresce e as estatísticas acompanham.",
        "de": "Lies jeden Tag: Die Strähne wächst, und die Statistik folgt.",
        "it": "Leggi ogni giorno: la serie cresce e le statistiche seguono.",
        "pl": "Czytaj codziennie: seria rośnie, a statystyki nadążają.",
        "ja": "毎日読めば記録は伸び、статистикаもついてきます。",
    },
    "Ouvrir ma bibliothèque": {
        "en": "Open my library", "es": "Abrir mi biblioteca", "es-419": "Abrir mi biblioteca",
        "pt-BR": "Abrir minha biblioteca", "de": "Meine Bibliothek öffnen",
        "it": "Apri la mia libreria", "pl": "Otwórz moją bibliotekę",
        "ja": "ライブラリを開く",
    },

    # ------------------------------------------------- jours de la semaine
    "L": {"en": "M", "es": "L", "es-419": "L", "pt-BR": "S", "de": "M",
          "it": "L", "pl": "P", "ja": "月"},
    "M": {"en": "T", "es": "M", "es-419": "M", "pt-BR": "T", "de": "D",
          "it": "M", "pl": "W", "ja": "火"},
    "J": {"en": "T", "es": "J", "es-419": "J", "pt-BR": "Q", "de": "D",
          "it": "G", "pl": "C", "ja": "木"},
    "V": {"en": "F", "es": "V", "es-419": "V", "pt-BR": "S", "de": "F",
          "it": "V", "pl": "P", "ja": "金"},
    "S": {"en": "S", "es": "S", "es-419": "S", "pt-BR": "S", "de": "S",
          "it": "S", "pl": "S", "ja": "土"},
    "D": {"en": "S", "es": "D", "es-419": "D", "pt-BR": "D", "de": "S",
          "it": "D", "pl": "N", "ja": "日"},
}

if __name__ == "__main__":
    ecrire(T)
