# -*- coding: utf-8 -*-
"""Le prêt de livres et l'écran Honya+."""
from catalogue import ecrire

T = {
    "Prêté": {
        "en": "Lent", "es": "Prestado", "es-419": "Prestado", "pt-BR": "Emprestado",
        "de": "Verliehen", "it": "Prestato", "nl": "Uitgeleend", "pl": "Pożyczona",
        "sv": "Utlånad", "tr": "Ödünç verildi", "ru": "Одолжена",
        "ja": "貸出中", "ko": "빌려줌", "zh-Hans": "已借出",
    },
    "Depuis le %@": {
        "en": "Since %@", "es": "Desde el %@", "es-419": "Desde el %@",
        "pt-BR": "Desde %@", "de": "Seit dem %@", "it": "Dal %@", "nl": "Sinds %@",
        "pl": "Od %@", "sv": "Sedan %@", "tr": "%@ tarihinden beri",
        "ru": "С %@", "ja": "%@から", "ko": "%@부터", "zh-Hans": "自 %@ 起",
    },
    "Le livre rejoint l'étagère « Prêtés » jusqu'à son retour.": {
        "en": "The book joins the “Lent” shelf until it comes home.",
        "es": "El libro pasa a la estantería «Prestados» hasta que vuelva.",
        "es-419": "El libro pasa al estante «Prestados» hasta que vuelva.",
        "pt-BR": "O livro fica na estante “Emprestados” até voltar.",
        "de": "Das Buch steht im Regal „Verliehen“, bis es zurückkommt.",
        "it": "Il libro passa allo scaffale «Prestati» finché non torna.",
        "nl": "Het boek staat op de plank 'Uitgeleend' tot het terug is.",
        "pl": "Książka trafia na półkę „Pożyczone”, aż wróci.",
        "sv": "Boken står på hyllan ”Utlånade” tills den kommer hem.",
        "tr": "Kitap dönene kadar “Ödünç verilenler” rafında durur.",
        "ru": "Книга стоит на полке «Одолженные», пока не вернётся.",
        "ja": "返ってくるまで「貸出中」の棚に並びます。",
        "ko": "돌아올 때까지 '빌려준 책' 책장에 놓여요.",
        "zh-Hans": "书会放在「已借出」书架上，直到归还。",
    },
    "Pour ceux qui vivent dans leur bibliothèque.": {
        "en": "For those who live in their library.",
        "es": "Para quienes viven en su biblioteca.",
        "es-419": "Para quienes viven en su biblioteca.",
        "pt-BR": "Para quem mora na própria estante.",
        "de": "Für alle, die in ihrer Bibliothek leben.",
        "it": "Per chi vive nella propria biblioteca.",
        "nl": "Voor wie in zijn boekenkast woont.",
        "pl": "Dla tych, którzy mieszkają w swojej bibliotece.",
        "sv": "För dig som bor i ditt bibliotek.",
        "tr": "Kitaplığında yaşayanlar için.",
        "ru": "Для тех, кто живёт в своей библиотеке.",
        "ja": "本棚に住む人のために。",
        "ko": "서재에서 살아가는 사람들을 위해.",
        "zh-Hans": "献给以书房为家的人。",
    },
    "Alertes de sortie sur toutes vos séries": {
        "en": "Release alerts for every series you follow",
        "es": "Avisos de salida para todas tus series",
        "es-419": "Avisos de salida para todas tus series",
        "pt-BR": "Alertas de lançamento para todas as suas séries",
        "de": "Erscheinungs-Alarme für alle deine Reihen",
        "it": "Avvisi di uscita per tutte le tue serie",
        "nl": "Verschijningsmeldingen voor al je reeksen",
        "pl": "Powiadomienia o premierach wszystkich Twoich serii",
        "sv": "Utgivningslarm för alla dina serier",
        "tr": "Tüm serilerin için çıkış bildirimleri",
        "ru": "Уведомления о выходе всех ваших серий",
        "ja": "すべてのシリーズの発売通知",
        "ko": "모든 시리즈의 발매 알림",
        "zh-Hans": "所有系列的新卷发售提醒",
    },
    "Prêts de livres : qui a quoi, depuis quand": {
        "en": "Book loans: who has what, since when",
        "es": "Préstamos: quién tiene qué, desde cuándo",
        "es-419": "Préstamos: quién tiene qué, desde cuándo",
        "pt-BR": "Empréstimos: quem está com o quê, desde quando",
        "de": "Verliehene Bücher: wer was hat, seit wann",
        "it": "Prestiti: chi ha cosa, da quando",
        "nl": "Uitgeleend: wie heeft wat, sinds wanneer",
        "pl": "Pożyczki: kto ma co i od kiedy",
        "sv": "Utlånade böcker: vem har vad, sedan när",
        "tr": "Ödünç kitaplar: kimde ne var, ne zamandır",
        "ru": "Одолженные книги: у кого что и с каких пор",
        "ja": "貸した本の記録：誰に、いつから",
        "ko": "빌려준 책: 누가, 무엇을, 언제부터",
        "zh-Hans": "借书记录：谁借了什么，借了多久",
    },
    "Scannez des étagères entières": {
        "en": "Scan whole shelves at once",
        "es": "Escanea estanterías enteras",
        "es-419": "Escanea estantes enteros",
        "pt-BR": "Escaneie estantes inteiras",
        "de": "Ganze Regale auf einmal scannen",
        "it": "Scansiona scaffali interi",
        "nl": "Scan hele planken in één keer",
        "pl": "Skanuj całe półki naraz",
        "sv": "Skanna hela hyllor på en gång",
        "tr": "Rafları tek seferde tara",
        "ru": "Сканируйте целые полки за раз",
        "ja": "本棚まるごとスキャン",
        "ko": "책장 전체를 한 번에 스캔",
        "zh-Hans": "整层书架一次扫完",
    },
    "Vos statistiques sur tout l'historique": {
        "en": "Your stats across all time",
        "es": "Tus estadísticas de todo el historial",
        "es-419": "Tus estadísticas de todo el historial",
        "pt-BR": "Suas estatísticas de todo o histórico",
        "de": "Deine Statistiken über die gesamte Zeit",
        "it": "Le tue statistiche su tutto lo storico",
        "nl": "Je statistieken over de hele geschiedenis",
        "pl": "Twoje statystyki z całej historii",
        "sv": "Din statistik för hela historiken",
        "tr": "Tüm geçmişin istatistikleri",
        "ru": "Ваша статистика за всё время",
        "ja": "全期間の読書統計",
        "ko": "전체 기간의 독서 통계",
        "zh-Hans": "全部时间的阅读统计",
    },
    "Étagères illimitées": {
        "en": "Unlimited shelves",
        "es": "Estanterías ilimitadas", "es-419": "Estantes ilimitados",
        "pt-BR": "Estantes ilimitadas", "de": "Unbegrenzte Regale",
        "it": "Scaffali illimitati", "nl": "Onbeperkt planken",
        "pl": "Półki bez limitu", "sv": "Obegränsade hyllor",
        "tr": "Sınırsız raf", "ru": "Без ограничений на полки",
        "ja": "棚は無制限", "ko": "책장 무제한", "zh-Hans": "不限书架数量",
    },
    "La rétrospective complète de décembre": {
        "en": "The full December wrap-up",
        "es": "La retrospectiva completa de diciembre",
        "es-419": "La retrospectiva completa de diciembre",
        "pt-BR": "A retrospectiva completa de dezembro",
        "de": "Der komplette Jahresrückblick im Dezember",
        "it": "La retrospettiva completa di dicembre",
        "nl": "De volledige terugblik van december",
        "pl": "Pełne podsumowanie roku w grudniu",
        "sv": "Hela årskrönikan i december",
        "tr": "Aralık ayının eksiksiz yıl özeti",
        "ru": "Полные итоги года в декабре",
        "ja": "12月の完全な読書まとめ",
        "ko": "12월의 완전한 결산",
        "zh-Hans": "十二月的完整年度回顾",
    },
    "Les abonnements ouvriront avec la sortie sur l'App Store.": {
        "en": "Subscriptions open with the App Store release.",
        "es": "Las suscripciones llegarán con el lanzamiento en el App Store.",
        "es-419": "Las suscripciones llegarán con el lanzamiento en App Store.",
        "pt-BR": "As assinaturas chegam com o lançamento na App Store.",
        "de": "Abos starten mit der Veröffentlichung im App Store.",
        "it": "Gli abbonamenti arriveranno con l'uscita sull'App Store.",
        "nl": "Abonnementen komen met de App Store-release.",
        "pl": "Subskrypcje ruszą wraz z premierą w App Store.",
        "sv": "Prenumerationer öppnar med App Store-släppet.",
        "tr": "Abonelikler App Store çıkışıyla açılacak.",
        "ru": "Подписки откроются с выходом в App Store.",
        "ja": "サブスクリプションはApp Store公開時に開始します。",
        "ko": "구독은 App Store 출시와 함께 시작돼요.",
        "zh-Hans": "订阅将随 App Store 上架开放。",
    },
    "Débloquer pour l'essai TestFlight": {
        "en": "Unlock for the TestFlight trial",
        "es": "Desbloquear para la prueba de TestFlight",
        "es-419": "Desbloquear para la prueba de TestFlight",
        "pt-BR": "Desbloquear para o teste do TestFlight",
        "de": "Für den TestFlight-Test freischalten",
        "it": "Sblocca per la prova TestFlight",
        "nl": "Ontgrendelen voor de TestFlight-test",
        "pl": "Odblokuj na czas testów TestFlight",
        "sv": "Lås upp för TestFlight-testet",
        "tr": "TestFlight denemesi için aç",
        "ru": "Открыть на время теста TestFlight",
        "ja": "TestFlightテスト用にロック解除",
        "ko": "TestFlight 테스트용으로 잠금 해제",
        "zh-Hans": "为 TestFlight 测试解锁",
    },
    "Plus tard": {
        "en": "Later", "es": "Más tarde", "es-419": "Más tarde",
        "pt-BR": "Mais tarde", "de": "Später", "it": "Più tardi",
        "nl": "Later", "pl": "Później", "sv": "Senare", "tr": "Daha sonra",
        "ru": "Позже", "ja": "あとで", "ko": "나중에", "zh-Hans": "稍后",
    },
}

if __name__ == "__main__":
    ecrire(T)
