# -*- coding: utf-8 -*-
"""L'achat réel : tarifs, essai, restauration, remise de la roue."""
from catalogue import ecrire

T = {
    "l'année entière": {
        "en": "the full year", "es": "el año completo",
        "es-419": "el año completo", "pt-BR": "o ano inteiro",
        "de": "das ganze Jahr", "it": "l'anno intero",
        "nl": "het hele jaar", "pl": "cały rok", "sv": "hela året",
        "tr": "tüm yıl", "ru": "весь год", "ja": "一年分",
        "ko": "1년 전체", "zh-Hans": "整整一年",
    },
    "votre remise appliquée": {
        "en": "your discount applied", "es": "con tu descuento aplicado",
        "es-419": "con tu descuento aplicado", "pt-BR": "com seu desconto aplicado",
        "de": "mit deinem Rabatt", "it": "con il tuo sconto",
        "nl": "met je korting", "pl": "z Twoją zniżką",
        "sv": "med din rabatt", "tr": "indiriminle",
        "ru": "с вашей скидкой", "ja": "割引が適用されます",
        "ko": "할인이 적용돼요", "zh-Hans": "已应用你的折扣",
    },
    "Cette offre n'est pas disponible pour le moment.": {
        "en": "This offer isn't available right now.",
        "es": "Esta oferta no está disponible ahora mismo.",
        "es-419": "Esta oferta no está disponible en este momento.",
        "pt-BR": "Esta oferta não está disponível no momento.",
        "de": "Dieses Angebot ist gerade nicht verfügbar.",
        "it": "Questa offerta non è disponibile al momento.",
        "nl": "Deze aanbieding is nu niet beschikbaar.",
        "pl": "Ta oferta jest teraz niedostępna.",
        "sv": "Erbjudandet är inte tillgängligt just nu.",
        "tr": "Bu teklif şu anda kullanılamıyor.",
        "ru": "Это предложение сейчас недоступно.",
        "ja": "この特典は現在ご利用いただけません。",
        "ko": "지금은 이 혜택을 이용할 수 없어요.",
        "zh-Hans": "此优惠暂时无法使用。",
    },
    "Votre achat attend une validation. Il s'activera tout seul.": {
        "en": "Your purchase is awaiting approval. It'll activate on its own.",
        "es": "Tu compra espera aprobación. Se activará sola.",
        "es-419": "Tu compra espera aprobación. Se activará sola.",
        "pt-BR": "Sua compra aguarda aprovação. Ela será ativada sozinha.",
        "de": "Dein Kauf wartet auf Freigabe. Er wird von selbst aktiv.",
        "it": "Il tuo acquisto attende un'approvazione. Si attiverà da solo.",
        "nl": "Je aankoop wacht op goedkeuring. Hij wordt vanzelf actief.",
        "pl": "Twój zakup czeka na zatwierdzenie. Aktywuje się sam.",
        "sv": "Ditt köp väntar på godkännande. Det aktiveras av sig självt.",
        "tr": "Satın alman onay bekliyor. Kendiliğinden etkinleşecek.",
        "ru": "Покупка ожидает подтверждения. Она активируется сама.",
        "ja": "購入は承認待ちです。承認されると自動で有効になります。",
        "ko": "구매가 승인을 기다리고 있어요. 승인되면 저절로 열려요.",
        "zh-Hans": "购买正在等待批准，通过后会自动生效。",
    },
    "Aucun achat à restaurer sur ce compte.": {
        "en": "No purchase to restore on this account.",
        "es": "No hay compras que restaurar en esta cuenta.",
        "es-419": "No hay compras que restaurar en esta cuenta.",
        "pt-BR": "Nenhuma compra para restaurar nesta conta.",
        "de": "Auf diesem Account gibt es nichts wiederherzustellen.",
        "it": "Nessun acquisto da ripristinare su questo account.",
        "nl": "Geen aankoop om te herstellen op dit account.",
        "pl": "Brak zakupów do przywrócenia na tym koncie.",
        "sv": "Inget köp att återställa på det här kontot.",
        "tr": "Bu hesapta geri yüklenecek satın alma yok.",
        "ru": "На этом аккаунте нечего восстанавливать.",
        "ja": "このアカウントに復元できる購入はありません。",
        "ko": "이 계정에 복원할 구매 내역이 없어요.",
        "zh-Hans": "此账户没有可恢复的购买。",
    },
    "Cet achat n'a pas pu être vérifié auprès de l'App Store.": {
        "en": "This purchase couldn't be verified with the App Store.",
        "es": "No se pudo verificar esta compra con la App Store.",
        "es-419": "No se pudo verificar esta compra con la App Store.",
        "pt-BR": "Não foi possível verificar esta compra na App Store.",
        "de": "Dieser Kauf konnte nicht beim App Store bestätigt werden.",
        "it": "Non è stato possibile verificare questo acquisto con l'App Store.",
        "nl": "Deze aankoop kon niet worden geverifieerd bij de App Store.",
        "pl": "Nie udało się zweryfikować tego zakupu w App Store.",
        "sv": "Köpet kunde inte verifieras hos App Store.",
        "tr": "Bu satın alma App Store'da doğrulanamadı.",
        "ru": "Не удалось подтвердить покупку в App Store.",
        "ja": "この購入は App Store で確認できませんでした。",
        "ko": "App Store에서 이 구매를 확인하지 못했어요.",
        "zh-Hans": "无法在 App Store 验证这笔购买。",
    },
    "%@ par mois": {
        "en": "%@ per month", "es": "%@ al mes", "es-419": "%@ al mes",
        "pt-BR": "%@ por mês", "de": "%@ pro Monat", "it": "%@ al mese",
        "nl": "%@ per maand", "pl": "%@ miesięcznie", "sv": "%@ per månad",
        "tr": "ayda %@", "ru": "%@ в месяц", "ja": "月 %@",
        "ko": "월 %@", "zh-Hans": "每月 %@",
    },
    "%lld jours offerts": {
        "en": "%lld days free", "es": "%lld días gratis",
        "es-419": "%lld días gratis", "pt-BR": "%lld dias grátis",
        "de": "%lld Tage gratis", "it": "%lld giorni gratis",
        "nl": "%lld dagen gratis", "pl": "%lld dni gratis",
        "sv": "%lld dagar gratis", "tr": "%lld gün ücretsiz",
        "ru": "%lld дней бесплатно", "ja": "%lld日間無料",
        "ko": "%lld일 무료", "zh-Hans": "%lld 天免费",
    },
    "Commencer l'essai gratuit": {
        "en": "Start free trial", "es": "Empezar la prueba gratis",
        "es-419": "Empezar la prueba gratis", "pt-BR": "Começar teste grátis",
        "de": "Gratis testen", "it": "Inizia la prova gratuita",
        "nl": "Start gratis proefperiode", "pl": "Rozpocznij bezpłatny okres próbny",
        "sv": "Starta gratisperioden", "tr": "Ücretsiz denemeyi başlat",
        "ru": "Начать бесплатный период", "ja": "無料体験を始める",
        "ko": "무료 체험 시작", "zh-Hans": "开始免费试用",
    },
    "Continuer pour %@": {
        "en": "Continue for %@", "es": "Continuar por %@",
        "es-419": "Continuar por %@", "pt-BR": "Continuar por %@",
        "de": "Weiter für %@", "it": "Continua per %@",
        "nl": "Doorgaan voor %@", "pl": "Kontynuuj za %@",
        "sv": "Fortsätt för %@", "tr": "%@ ile devam et",
        "ru": "Продолжить за %@", "ja": "%@ で続ける",
        "ko": "%@ 결제하고 계속", "zh-Hans": "支付 %@ 继续",
    },
    "Paiement unique, sans renouvellement.": {
        "en": "One-time payment, no renewal.",
        "es": "Pago único, sin renovación.",
        "es-419": "Pago único, sin renovación.",
        "pt-BR": "Pagamento único, sem renovação.",
        "de": "Einmalzahlung, keine Verlängerung.",
        "it": "Pagamento unico, senza rinnovo.",
        "nl": "Eenmalige betaling, geen verlenging.",
        "pl": "Płatność jednorazowa, bez odnawiania.",
        "sv": "Engångsbetalning, ingen förnyelse.",
        "tr": "Tek seferlik ödeme, yenileme yok.",
        "ru": "Разовый платёж, без продления.",
        "ja": "一度きりのお支払い、自動更新なし。",
        "ko": "1회 결제, 자동 갱신 없음.",
        "zh-Hans": "一次性付款，不会续订。",
    },
    "Puis %@. Résiliable à tout moment.": {
        "en": "Then %@. Cancel anytime.",
        "es": "Después %@. Cancela cuando quieras.",
        "es-419": "Después %@. Cancela cuando quieras.",
        "pt-BR": "Depois %@. Cancele quando quiser.",
        "de": "Danach %@. Jederzeit kündbar.",
        "it": "Poi %@. Disdici quando vuoi.",
        "nl": "Daarna %@. Altijd opzegbaar.",
        "pl": "Potem %@. Anuluj w każdej chwili.",
        "sv": "Sedan %@. Avsluta när du vill.",
        "tr": "Sonra %@. İstediğin zaman iptal et.",
        "ru": "Затем %@. Отмена в любой момент.",
        "ja": "以降は %@。いつでも解約できます。",
        "ko": "이후 %@. 언제든 해지할 수 있어요.",
        "zh-Hans": "之后 %@，可随时取消。",
    },
    "Renouvelé automatiquement. Résiliable à tout moment.": {
        "en": "Renews automatically. Cancel anytime.",
        "es": "Se renueva automáticamente. Cancela cuando quieras.",
        "es-419": "Se renueva automáticamente. Cancela cuando quieras.",
        "pt-BR": "Renova automaticamente. Cancele quando quiser.",
        "de": "Verlängert sich automatisch. Jederzeit kündbar.",
        "it": "Si rinnova automaticamente. Disdici quando vuoi.",
        "nl": "Wordt automatisch verlengd. Altijd opzegbaar.",
        "pl": "Odnawia się automatycznie. Anuluj w każdej chwili.",
        "sv": "Förnyas automatiskt. Avsluta när du vill.",
        "tr": "Otomatik yenilenir. İstediğin zaman iptal et.",
        "ru": "Продлевается автоматически. Отмена в любой момент.",
        "ja": "自動更新されます。いつでも解約できます。",
        "ko": "자동으로 갱신돼요. 언제든 해지할 수 있어요.",
        "zh-Hans": "自动续订，可随时取消。",
    },
    "Restaurer mes achats": {
        "en": "Restore purchases", "es": "Restaurar compras",
        "es-419": "Restaurar compras", "pt-BR": "Restaurar compras",
        "de": "Käufe wiederherstellen", "it": "Ripristina acquisti",
        "nl": "Aankopen herstellen", "pl": "Przywróć zakupy",
        "sv": "Återställ köp", "tr": "Satın alımları geri yükle",
        "ru": "Восстановить покупки", "ja": "購入を復元",
        "ko": "구매 복원", "zh-Hans": "恢复购买",
    },
    "Profiter de ma remise": {
        "en": "Claim my discount", "es": "Aprovechar mi descuento",
        "es-419": "Aprovechar mi descuento", "pt-BR": "Aproveitar meu desconto",
        "de": "Rabatt sichern", "it": "Approfitta del mio sconto",
        "nl": "Mijn korting gebruiken", "pl": "Odbierz zniżkę",
        "sv": "Hämta min rabatt", "tr": "İndirimimi kullan",
        "ru": "Забрать скидку", "ja": "割引を受け取る",
        "ko": "할인 받기", "zh-Hans": "领取我的折扣",
    },
    "La première année à %@": {
        "en": "The first year for %@", "es": "El primer año por %@",
        "es-419": "El primer año por %@", "pt-BR": "O primeiro ano por %@",
        "de": "Das erste Jahr für %@", "it": "Il primo anno a %@",
        "nl": "Het eerste jaar voor %@", "pl": "Pierwszy rok za %@",
        "sv": "Första året för %@", "tr": "İlk yıl %@",
        "ru": "Первый год за %@", "ja": "初年度 %@",
        "ko": "첫 해 %@", "zh-Hans": "首年 %@",
    },
}

if __name__ == "__main__":
    ecrire(T)
