# -*- coding: utf-8 -*-
"""Traductions — vague 7 : les six langues, textes courts et libellés."""
from catalogue import ecrire

L = ("nl", "ko", "zh-Hans", "tr", "ru", "sv")


def t(*valeurs):
    """Raccourci : t(nl, ko, zh, tr, ru, sv)."""
    return dict(zip(L, valeurs))


T = {
    # ------------------------------------------------ emplacements purs
    "%lld": t("%lld", "%lld", "%lld", "%lld", "%lld", "%lld"),
    "%lld %@": t("%lld %@", "%lld %@", "%lld %@", "%lld %@", "%lld %@", "%lld %@"),
    "· %@": t("· %@", "· %@", "· %@", "· %@", "· %@", "· %@"),
    "%@ · %lld": t("%@ · %lld", "%@ · %lld", "%@ · %lld", "%@ · %lld", "%@ · %lld", "%@ · %lld"),
    "« %@ »": t("‘%@’", "「%@」", "「%@」", "“%@”", "«%@»", "”%@”"),
    "9782…": t("9782…", "9782…", "9782…", "9782…", "9782…", "9782…"),
    "ISBN": t("ISBN", "ISBN", "ISBN", "ISBN", "ISBN", "ISBN"),

    # ------------------------------------------------ jours de la semaine
    "L": t("M", "월", "一", "P", "Пн", "M"),
    "M": t("D", "화", "二", "S", "Вт", "T"),
    "J": t("D", "목", "四", "P", "Чт", "T"),
    "V": t("V", "금", "五", "C", "Пт", "F"),
    "S": t("Z", "토", "六", "C", "Сб", "L"),
    "D": t("Z", "일", "日", "P", "Вс", "S"),

    # ----------------------------------------------------------- libellés
    "Genres": t("Genres", "장르", "类型", "Türler", "Жанры", "Genrer"),
    "Vos genres": t("Jouw genres", "나의 장르", "你的类型",
                    "Türlerin", "Ваши жанры", "Dina genrer"),
    "Type": t("Soort", "종류", "类型", "Tür", "Тип", "Typ"),
    "Source": t("Bron", "출처", "来源", "Kaynak", "Источник", "Källa"),
    "Parution": t("Verschijning", "간행", "刊行", "Yayın", "Выход", "Utgivning"),
    "Publication": t("Uitgave", "출판", "出版", "Yayım", "Издание", "Publicerad"),
    "Informations": t("Details", "정보", "详细信息", "Bilgiler", "Сведения", "Detaljer"),
    "Détails": t("Details", "상세", "详情", "Ayrıntılar", "Подробности", "Detaljer"),
    "Résumé": t("Samenvatting", "줄거리", "简介", "Özet", "Аннотация", "Sammanfattning"),
    "Progression": t("Voortgang", "진행", "进度", "İlerleme", "Прогресс", "Framsteg"),
    "Langue": t("Taal", "언어", "语言", "Dil", "Язык", "Språk"),
    "Sessions": t("Sessies", "세션", "阅读记录", "Oturumlar", "Сеансы", "Pass"),
    "Citations": t("Citaten", "인용", "摘录", "Alıntılar", "Цитаты", "Citat"),
    "La phrase": t("De zin", "문장", "这句话", "Cümle", "Фраза", "Meningen"),
    "Possédé": t("In de kast", "소장", "已拥有", "Rafta", "В наличии", "I hyllan"),
    "Manquant": t("Ontbreekt", "미소장", "缺少", "Eksik", "Не хватает", "Saknas"),
    "Prêtés": t("Uitgeleend", "대출 중", "已借出", "Ödünçte", "Одолжено", "Utlånade"),
    "Prêter": t("Leen uit", "빌려주기", "借出", "Ödünç ver", "Одолжить", "Låna ut"),
    "Prêter…": t("Leen uit…", "빌려주기…", "借出…", "Ödünç ver…", "Одолжить…", "Låna ut…"),
    "Prêté à": t("Uitgeleend aan", "빌려준 사람", "借给", "Ödünç alan", "Кому одолжено", "Utlånad till"),
    "Rendu": t("Terug", "반납됨", "已归还", "İade edildi", "Возвращено", "Återlämnad"),
    "À qui ?": t("Aan wie?", "누구에게?", "借给谁？", "Kime?", "Кому?", "Till vem?"),
    "Scanner": t("Scan", "스캔", "扫描", "Tara", "Сканировать", "Skanna"),
    "Recherche…": t("Bezig met zoeken…", "검색 중…", "搜索中…",
                    "Aranıyor…", "Идёт поиск…", "Söker…"),
    "En attente": t("Wachten", "대기 중", "等待中", "Bekleniyor", "Ожидание", "Väntar"),
    "Son nom": t("De naam", "이름", "名称", "Adı", "Название", "Namnet"),
    "Ajuster": t("Pas aan", "조정", "调整", "Ayarla", "Настроить", "Justera"),
    "Mettre à jour": t("Werk bij", "업데이트", "更新", "Güncelle", "Обновить", "Uppdatera"),
    "Terminé !": t("Klaar!", "완독!", "读完了！", "Bitti!", "Готово!", "Klart!"),
    "En ce moment": t("Op dit moment", "지금 읽는 중", "此刻",
                      "Şu anda", "Сейчас", "Just nu"),
    "À suivre": t("Volgen", "관심 목록", "关注中", "Takipte", "Слежу", "Bevakade"),
    "Sorties à venir": t("Binnenkort uit", "곧 나올 책", "即将发行",
                         "Yakında çıkacak", "Скоро выйдет", "Kommande utgivningar"),
    "Récemment ajoutés": t("Onlangs toegevoegd", "최근 추가", "最近添加",
                           "Son eklenenler", "Недавно добавленные", "Nyligen tillagda"),
    "Ajouts récents": t("Onlangs toegevoegd", "최근 추가", "最近添加",
                        "Son eklenenler", "Недавно добавленные", "Nyligen tillagda"),
    "Nouveau record": t("Nieuw record", "신기록", "新纪录",
                        "Yeni rekor", "Новый рекорд", "Nytt rekord"),
    "Meilleur mois": t("Beste maand", "최고의 달", "最佳月份",
                       "En iyi ay", "Лучший месяц", "Bästa månaden"),
    "Plus longue session": t("Langste sessie", "가장 긴 세션", "最长阅读时段",
                             "En uzun oturum", "Самый долгий сеанс", "Längsta passet"),
    "Série de jours de lecture": t("Leesreeks", "연속 독서일", "连续阅读天数",
                                   "Okuma serisi", "Серия дней чтения", "Läsrad"),
    "Jours de lecture de la semaine": t(
        "Leesdagen deze week", "이번 주 독서일", "本周阅读天数",
        "Bu haftaki okuma günleri", "Дни чтения за неделю", "Lässdagar denna vecka"),
    "Votre série de lecture est de": t(
        "Je leesreeks is", "연속 독서 기록", "你的连续阅读天数是",
        "Okuma serin", "Ваша серия чтения —", "Din läsrad är"),
    "Lectures": t("Boeken", "읽은 책", "阅读量", "Okumalar", "Прочитано", "Läsningar"),
    "Objectif de lecture": t("Leesdoel", "독서 목표", "阅读目标",
                             "Okuma hedefi", "Цель чтения", "Läsmål"),
    "Numéro de page": t("Paginanummer", "페이지 번호", "页码",
                        "Sayfa numarası", "Номер страницы", "Sidnummer"),
    "Page (optionnel)": t("Pagina (optioneel)", "페이지 (선택)", "页码（可选）",
                          "Sayfa (isteğe bağlı)", "Страница (необязательно)",
                          "Sida (valfritt)"),
    "Où en es-tu ?": t("Waar ben je?", "어디까지 읽었나요?", "读到哪里了？",
                       "Nerede kaldın?", "Docmeste остановились?", "Var är du?"),
    "Belle session !": t("Mooie sessie!", "좋은 독서였어요!", "读得不错！",
                         "Güzel bir oturum!", "Отличный сеанс!", "Bra pass!"),
    "Commencer une lecture": t("Begin met lezen", "독서 시작", "开始阅读",
                               "Okumaya başla", "Начать чтение", "Börja läsa"),
    "Continuer à lire": t("Verder lezen", "이어 읽기", "继续阅读",
                          "Okumaya devam", "Продолжить чтение", "Fortsätt läsa"),
    "Reprendre la lecture": t("Hervat het lezen", "독서 재개", "继续阅读",
                              "Okumayı sürdür", "Продолжить чтение", "Återuppta läsningen"),
    "J'ai terminé ce livre": t("Ik heb dit boek uit", "이 책을 다 읽었어요",
                               "我读完这本书了", "Bu kitabı bitirdim",
                               "Я дочитал эту книгу", "Jag har läst ut boken"),
    "Nouvelle citation": t("Nieuw citaat", "새 인용", "新建摘录",
                           "Yeni alıntı", "Новая цитата", "Nytt citat"),
    "Aucune citation": t("Nog geen citaten", "인용이 없습니다", "还没有摘录",
                         "Henüz alıntı yok", "Цитат пока нет", "Inga citat än"),
    "Nouvelle collection": t("Nieuwe collectie", "새 컬렉션", "新建收藏集",
                             "Yeni koleksiyon", "Новая коллекция", "Ny samling"),
    "Nouvelle étagère…": t("Nieuwe plank…", "새 책장…", "新建书架…",
                           "Yeni raf…", "Новая полка…", "Ny hylla…"),
    "Séries incomplètes": t("Onvolledige reeksen", "미완성 시리즈", "未集齐的系列",
                            "Eksik seriler", "Неполные серии", "Ofullständiga serier"),
    "Coups de cœur": t("Favorieten", "인생책", "心头好",
                       "Favoriler", "Любимое", "Favoriter"),
    "Achetés cette année": t("Dit jaar gekocht", "올해 구매", "今年购入",
                             "Bu yıl alınanlar", "Куплено в этом году", "Köpta i år"),
    "Jamais ouverts": t("Nooit geopend", "펼치지 않은 책", "从未打开",
                        "Hiç açılmamış", "Ни разу не открыты", "Aldrig öppnade"),
    "Possédés jusqu'au tome": t("In de kast tot deel", "소장은 몇 권까지",
                                "已拥有到第几卷", "Rafta kaçıncı cilde kadar",
                                "В наличии до тома", "I hyllan till del"),
    "Lus jusqu'au tome": t("Gelezen tot deel", "읽은 것은 몇 권까지",
                           "已读到第几卷", "Okundu kaçıncı cilde kadar",
                           "Прочитано до тома", "Läst till del"),
    "Possédés jusqu'à…": t("In de kast tot…", "소장은 …까지", "已拥有到…",
                           "Rafta …kadar", "В наличии до…", "I hyllan till…"),
    "Lus jusqu'à…": t("Gelezen tot…", "읽은 것은 …까지", "已读到…",
                      "Okundu …kadar", "Прочитано до…", "Läst till…"),
    "Ajouter un tome": t("Voeg een deel toe", "권 추가", "添加一卷",
                         "Cilt ekle", "Добавить том", "Lägg till en del"),
    "Retirer ce tome": t("Haal dit deel weg", "이 권 제거", "移除此卷",
                         "Bu cildi kaldır", "Убрать этот том", "Ta bort den här delen"),
    "Retirer la série": t("Haal de reeks weg", "시리즈 제거", "移除系列",
                          "Seriyi kaldır", "Убрать серию", "Ta bort serien"),
    "Retirer de la bibliothèque": t(
        "Uit de bibliotheek halen", "서재에서 제거", "从书库移除",
        "Kitaplıktan kaldır", "Убрать из библиотеки", "Ta bort från biblioteket"),
    "Retirer de ma bibliothèque": t(
        "Uit mijn bibliotheek halen", "내 서재에서 제거", "从我的书库移除",
        "Kitaplığımdan kaldır", "Убрать из моей библиотеки", "Ta bort från mitt bibliotek"),
    "Ajouter à la bibliothèque": t(
        "Aan de bibliotheek toevoegen", "서재에 추가", "加入书库",
        "Kitaplığa ekle", "Добавить в библиотеку", "Lägg till i biblioteket"),
    "Ajouter à ma bibliothèque": t(
        "Aan mijn bibliotheek toevoegen", "내 서재에 추가", "加入我的书库",
        "Kitaplığıma ekle", "Добавить в мою библиотеку", "Lägg till i mitt bibliotek"),
    "Ajouter cette série": t("Voeg deze reeks toe", "이 시리즈 추가", "添加此系列",
                             "Bu seriyi ekle", "Добавить эту серию", "Lägg till serien"),
    "Ajouter la série": t("Voeg de reeks toe", "시리즈 추가", "添加系列",
                          "Seriyi ekle", "Добавить серию", "Lägg till serien"),
    "Ajouter un livre": t("Voeg een boek toe", "책 추가", "添加图书",
                          "Kitap ekle", "Добавить книгу", "Lägg till en bok"),
    "Ajouter à À suivre": t("Aan Volgen toevoegen", "관심 목록에 추가", "加入关注",
                            "Takibe ekle", "Добавить в «Слежу»", "Lägg till i Bevakade"),
    "Retirer d'À suivre": t("Uit Volgen halen", "관심 목록에서 제거", "取消关注",
                            "Takipten çıkar", "Убрать из «Слежу»", "Ta bort från Bevakade"),
    "Déjà dans la bibliothèque": t(
        "Al in de bibliotheek", "이미 서재에 있음", "已在书库中",
        "Zaten kitaplıkta", "Уже в библиотеке", "Redan i biblioteket"),
    "Déjà dans votre bibliothèque": t(
        "Al in je bibliotheek", "이미 서재에 있습니다", "已在你的书库中",
        "Zaten kitaplığında", "Уже в вашей библиотеке", "Redan i ditt bibliotek"),
    "Je le possède": t("Ik heb hem", "가지고 있어요", "我有这本",
                       "Bende var", "У меня есть", "Jag har den"),
    "Je le possède · à lire": t("Ik heb hem · te lezen", "소장 · 읽을 예정",
                                "已拥有 · 待读", "Bende var · okunacak",
                                "У меня есть · к прочтению", "Jag har den · att läsa"),
    "Je suis en train de le lire": t("Ik lees hem nu", "지금 읽고 있어요",
                                     "我正在读", "Şu an okuyorum",
                                     "Сейчас читаю", "Jag läser den nu"),
    "Je l'ai lu": t("Ik heb hem gelezen", "다 읽었어요", "我读过了",
                    "Okudum", "Я прочитал", "Jag har läst den"),
    "Marquer comme lu": t("Markeer als gelezen", "읽음으로 표시", "标为已读",
                          "Okundu olarak işaretle", "Отметить прочитанным",
                          "Markera som läst"),
    "Tout marquer lu jusqu'ici": t(
        "Alles tot hier als gelezen", "여기까지 모두 읽음", "标记到此为止全部已读",
        "Buraya kadar hepsini okundu yap", "Отметить всё до этого места",
        "Markera allt hit som läst"),
    "Toute la série lue": t("Hele reeks gelezen", "시리즈 전권 읽음", "整个系列已读",
                            "Tüm seri okundu", "Вся серия прочитана", "Hela serien läst"),
    "Actualiser les informations": t(
        "Gegevens verversen", "정보 새로 고침", "刷新信息",
        "Bilgileri yenile", "Обновить сведения", "Uppdatera informationen"),
    "Afficher en grille": t("Toon als raster", "그리드로 보기", "网格显示",
                            "Izgara görünümü", "Сеткой", "Visa som rutnät"),
    "Afficher en liste": t("Toon als lijst", "목록으로 보기", "列表显示",
                           "Liste görünümü", "Списком", "Visa som lista"),
    "Toutes les langues": t("Alle talen", "모든 언어", "所有语言",
                            "Tüm diller", "Все языки", "Alla språk"),
    "Langue des éditions :": t("Taal van de uitgaven:", "판의 언어:", "版本语言：",
                               "Baskı dili:", "Язык изданий:", "Utgåvornas språk:"),
    "Langue de l'édition": t("Taal van de uitgave", "판의 언어", "版本语言",
                             "Baskı dili", "Язык издания", "Utgåvans språk"),
    "Titre, auteur, série…": t("Titel, auteur, reeks…", "제목, 저자, 시리즈…",
                               "书名、作者、系列…", "Başlık, yazar, seri…",
                               "Название, автор, серия…", "Titel, författare, serie…"),
    "Scanner un ISBN": t("Scan een ISBN", "ISBN 스캔", "扫描 ISBN",
                         "ISBN tara", "Сканировать ISBN", "Skanna en ISBN"),
    "Caméra indisponible ici": t("Camera hier niet beschikbaar", "여기서는 카메라를 쓸 수 없습니다",
                                 "此处无法使用相机", "Burada kamera kullanılamıyor",
                                 "Камера здесь недоступна", "Kameran är inte tillgänglig här"),
    "Populaires en ce moment": t("Nu populair", "지금 인기", "当下热门",
                                 "Şu an popüler", "Сейчас популярно", "Populärt just nu"),
    "Tendances des recherches": t("Populaire zoekopdrachten", "인기 검색어",
                                  "热门搜索", "Popüler aramalar",
                                  "Популярные запросы", "Populära sökningar"),
    "Les précommandes du catalogue": t(
        "Voorbestellingen uit de catalogus", "카탈로그의 예약 상품", "书目中的预订书",
        "Katalogdaki ön siparişler", "Предзаказы каталога", "Förhandsbokningar i katalogen"),
    "Gratuits en ce moment": t("Nu gratis", "지금 무료", "现在免费",
                               "Şu an ücretsiz", "Сейчас бесплатно", "Gratis just nu"),
    "Choisi d'après votre bibliothèque": t(
        "Gekozen op basis van je bibliotheek", "서재를 바탕으로 고른 책",
        "根据你的书库挑选", "Kitaplığına göre seçildi",
        "Подобрано по вашей библиотеке", "Valt utifrån ditt bibliotek"),
    "Compte Apple": t("Apple-account", "Apple 계정", "Apple 账户",
                      "Apple hesabı", "Учётная запись Apple", "Apple-konto"),
    "Compte Honya": t("Honya-account", "Honya 계정", "Honya 账户",
                      "Honya hesabı", "Учётная запись Honya", "Honya-konto"),
    "Créer mon compte": t("Maak mijn account", "내 계정 만들기", "创建我的账户",
                          "Hesabımı oluştur", "Создать мою учётную запись",
                          "Skapa mitt konto"),
    "Créer un compte ou se connecter": t(
        "Maak een account of log in", "계정 만들기 또는 로그인", "创建账户或登录",
        "Hesap oluştur veya giriş yap", "Создать учётную запись или войти",
        "Skapa konto eller logga in"),
    "Utiliser une adresse e-mail": t(
        "Gebruik een e-mailadres", "이메일 주소 사용", "使用电子邮件地址",
        "E-posta adresi kullan", "Использовать эл. почту", "Använd en e-postadress"),
    "Utiliser mon identifiant Apple": t(
        "Gebruik mijn Apple-account", "내 Apple 계정 사용", "使用我的 Apple 账户",
        "Apple hesabımı kullan", "Использовать учётную запись Apple",
        "Använd mitt Apple-konto"),
    "Supprimer définitivement": t("Definitief verwijderen", "완전히 삭제", "永久删除",
                                  "Kalıcı olarak sil", "Удалить навсегда",
                                  "Radera permanent"),
    "Tout effacer…": t("Wis alles…", "전체 삭제…", "全部清除…",
                       "Hepsini sil…", "Стереть всё…", "Radera allt…"),
    "Non renseignée": t("Niet ingesteld", "미설정", "未填写",
                        "Belirtilmemiş", "Не указано", "Ej angiven"),
    "Rappel de sortie": t("Herinnering bij uitgave", "발매 알림", "发行提醒",
                          "Çıkış hatırlatması", "Напоминание о выходе",
                          "Påminnelse vid utgivning"),
    "Ouvrir ma bibliothèque": t("Open mijn bibliotheek", "내 서재 열기", "打开我的书库",
                                "Kitaplığımı aç", "Открыть мою библиотеку",
                                "Öppna mitt bibliotek"),
    "Bienvenue dans Honya": t("Welkom bij Honya", "Honya에 오신 것을 환영합니다",
                              "欢迎使用 Honya", "Honya'ya hoş geldin",
                              "Добро пожаловать в Honya", "Välkommen till Honya"),

    # ------------------------------------------------------------- unités
    "pages": t("pagina's", "페이지", "页", "sayfa", "стр.", "sidor"),
    "pages lues": t("gelezen pagina's", "읽은 페이지", "已读页数",
                    "okunan sayfa", "прочитано страниц", "lästa sidor"),
    "pages / heure": t("pagina's / uur", "페이지/시간", "页/小时",
                       "sayfa / saat", "стр. / час", "sidor / timme"),
    "record · min": t("record · min", "최고 기록 · 분", "纪录 · 分钟",
                      "rekor · dk", "рекорд · мин", "rekord · min"),
    "lus": t("gelezen", "읽음", "已读", "okunan", "прочитано", "lästa"),
    "possédés": t("in de kast", "소장", "已拥有", "rafta", "в наличии", "i hyllan"),
    "en cours": t("bezig", "읽는 중", "在读", "okunuyor", "читаю", "pågår"),
    "à acheter": t("te kopen", "구매 예정", "待购", "alınacak", "купить", "att köpa"),
    "série finie": t("reeks af", "완독 시리즈", "完成的系列",
                     "biten seri", "серия завершена", "avslutad serie"),
    "séries finies": t("reeksen af", "완독 시리즈", "完成的系列",
                       "biten seri", "серий завершено", "avslutade serier"),
    "en rayon": t("in de kast", "책장에", "在架上", "rafta", "на полке", "i hyllan"),
    "de lecture": t("leestijd", "독서", "阅读", "okuma", "чтения", "lästid"),
    "moins → plus": t("minder → meer", "적음 → 많음", "少 → 多",
                      "az → çok", "меньше → больше", "mindre → mer"),
    "pile dans le rythme": t("precies op schema", "딱 알맞은 속도", "刚好跟上进度",
                             "tam gidişatta", "точно в графике", "precis i takt"),
}

if __name__ == "__main__":
    ecrire(T)
